MM-28296 Fix Android @mention render
mattermost/mattermost-mobile pull request #4764
Opened 2020-09-03 23:03 UTC by enahum

#### Summary
Fix mention rendering on the screen when turning on or off the setting for Notification > Mentions & Replies & non-case sensitive username 

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-28296

2020-09-03 23:10 UTC, wiggin77 approved these changes
LGTM :+1:     Moving the logic out of the ternary operator makes sense, but I'm curious if replacing the "null" with "mentionStyle" would have worked.

2020-09-03 23:11 UTC, enahum commented
@wiggin77 it would have.. and I'm going to simplify it a little bit more

2020-09-03 23:55 UTC, mattermod commented
Building app in separate branch.

2020-09-04 00:04 UTC, mattermod commented
Successfully building:  
https://circleci.com/gh/mattermost/mattermost-mobile/10050  
https://circleci.com/gh/mattermost/mattermost-mobile/10048

2020-09-04 00:24 UTC, mattermod commented
Artifact links:  
https://10050-70265724-gh.circle-artifacts.com/0/%7E/mattermost-mobile/Mattermost_Beta.ipa  
https://10048-70265724-gh.circle-artifacts.com/0/%7E/mattermost-mobile/Mattermost_Beta.apk

2020-09-04 00:31 UTC, josephbaylon commented
@enahum I'm seeing 2 incorrect behaviors introduced, at least when compared to https://github.com/mattermost/mattermost-mobile/pull/4754 and the web.
1. The `@all`, `@channel`, `@here` are never highlighted anymore.
2. When user turns off the non-case sensitive username, the highlight on the `@username` of the currently logged-in user goes away.

Note: This now affects both iOS and Android.

|mobile|web|
|:---|:---|
|![image-ecd5500e-ee0b-4609-846e-360ccea495c6](https://user-images.githubusercontent.com/487991/92186061-6cc2a280-ee0a-11ea-8fc0-7c4e6a31fc39.jpg)|![Screen Shot 2020-09-03 at 5 28 02 PM](https://user-images.githubusercontent.com/487991/92186259-10ac4e00-ee0b-11ea-9cef-c04bae6d3b0c.png)|

2020-09-04 02:14 UTC, enahum commented
@josephbaylon PTAL

2020-09-08 15:06 UTC, josephbaylon requested changes
@enahum Issues found here https://github.com/mattermost/mattermost-mobile/pull/4764#issuecomment-686832096 look fixed. However, existing users other than current user are not link colored (see `@jgbaylon` and `@baylonjoseph` below). User is still able to tap on those users to see profile

Happens on both iOS and Android,

![image-fffa6480-c25e-4811-9bba-6c193fede903](https://user-images.githubusercontent.com/487991/92493836-d562a400-f1a9-11ea-92a6-7ad2241e2601.jpg)

2020-09-08 15:08 UTC, enahum commented
Go on and on and on pain in the b..tt, let me see what I can do here.

2020-09-08 16:07 UTC, josephbaylon approved these changes
LGTM. Issue found here https://github.com/mattermost/mattermost-mobile/pull/4764#issuecomment-688941898 has been fixed. Also retested various at-mention test cases with different notification settings.

Tested on both iPhone X (14.0) and Pixel 3 XL (10) devices.

2020-09-08 16:09 UTC, merged