Gallery Improvements
mattermost/mattermost-mobile pull request #4837
Opened 2020-09-24 15:33 UTC by enahum

#### Summary
Improvements to the Gallery to view files (Images, Videos, Docs & Others) Re-built from the ground up.

Images have a shared element transition (janky at the end when opening on Android, this is not our fault but the nav lib), Videos and other files slide in from the bottom.

When downloading a file it presents the ability to share, if preview for a file is enabled it can display it (on Android remains the same and you need to have a viewer)

Added support for Keynote, Numbers & Pages on iOS

Added the ability to copy the public link of a file (in the gallery) this one respects the setting for EMM copyPasteProtection

File downloads & previews other than images & videos respect the server setting for `Allow mobile file download`

Gallery can be closed by sliding up/down the items.

#### Ticket Link
* https://mattermost.atlassian.net/browse/MM-22195
* https://mattermost.atlassian.net/browse/MM-13320
* https://mattermost.atlassian.net/browse/MM-20231
* https://mattermost.atlassian.net/browse/MM-22009

#### Checklist
- [x] Added or updated unit tests (required for all new features)
- [x] Has UI changes
- [x] Includes text changes and localization file updates

#### Device Information
This PR was tested on: iPhone XS and iPad 11 Pro (iOS & iPadOS 14), Android Pixel 4 (Android 11)

#### Testing
Manual testing ok, but I have no clue how to write some meaningful E2E tests for this.

2020-09-24 15:33 UTC, mattermod commented
Building app in separate branch.

2020-09-24 15:42 UTC, mattermod commented
Successfully building:  
https://circleci.com/gh/mattermost/mattermost-mobile/10671  
https://circleci.com/gh/mattermost/mattermost-mobile/10670

2020-09-24 16:12 UTC, mattermod commented
Artifact links:  
https://10671-70265724-gh.circle-artifacts.com/0/%7E/mattermost-mobile/Mattermost_Beta.apk  
https://10670-70265724-gh.circle-artifacts.com/0/%7E/mattermost-mobile/Mattermost_Beta.ipa

2020-10-08 12:56 UTC, mattermod commented
Building app in separate branch.

2020-10-08 13:03 UTC, mattermod commented
Successfully building:  
https://circleci.com/gh/mattermost/mattermost-mobile/10985  
https://circleci.com/gh/mattermost/mattermost-mobile/10984

2020-10-08 13:33 UTC, mattermod commented
Artifact links:  
https://10985-70265724-gh.circle-artifacts.com/0/%7E/mattermost-mobile/Mattermost_Beta.apk  
https://10984-70265724-gh.circle-artifacts.com/0/%7E/mattermost-mobile/Mattermost_Beta.ipa

2020-10-09 13:01 UTC, mattermod commented
Building app in separate branch.

2020-10-09 13:08 UTC, mattermod commented
Successfully building:  
https://circleci.com/gh/mattermost/mattermost-mobile/11013  
https://circleci.com/gh/mattermost/mattermost-mobile/11012

2020-10-09 13:31 UTC, mattermod commented
Artifact links:  
https://11013-70265724-gh.circle-artifacts.com/0/%7E/mattermost-mobile/Mattermost_Beta.apk  
https://11012-70265724-gh.circle-artifacts.com/0/%7E/mattermost-mobile/Mattermost_Beta.ipa

2020-10-15 20:53 UTC, enahum commented on app/components/combined_system_message/combined_system_message.js
> +                disableGallery={true}
It is not, but it is explicit that a gallery should not be able to open as the default is to allow it

2020-10-15 20:54 UTC, enahum commented on app/screens/gallery/gallery.js
> +                    postId={files[0].post_id}
It definitely is, check the connected component

2020-10-15 20:55 UTC, enahum commented
As for the progress bar it starts as soon as the download starts, maybe is not visible until some progress have been reported?

2020-10-15 21:30 UTC, enahum commented on app/components/post_body_additional_content/post_body_additional_content.js
> +        let filename = parseUrl(url.substr(url.lastIndexOf('/'))).pathname.replace('/', '');
out of scope from this PR, that code already existed there.

2020-10-15 21:32 UTC, enahum commented on app/components/post_attachment_image/index.js
> +                <View>
probably not.

2020-10-15 23:20 UTC, enahum commented on app/screens/gallery/gallery.js
> +                    postId={files[0].post_id}
you are right, is using the post_id in the file prop. will remove

2020-10-15 23:21 UTC, enahum commented
> Hmm, I wonder if we should start it at some value (1%?) initially?

I can give it a try and see... I need to merge master here anyway :S

2020-10-16 03:17 UTC, enahum commented on app/components/post_attachment_image/index.js
> +                <View>
Yes, is needed... without it `TouchableWithFeedback` won't capture the tap

2020-10-27 17:03 UTC, mattermod commented
Building app in separate branch.

2020-10-27 17:12 UTC, mattermod commented
Successfully building:  
https://circleci.com/gh/mattermost/mattermost-mobile/11481  
https://circleci.com/gh/mattermost/mattermost-mobile/11480

2020-10-27 17:28 UTC, mattermod commented
Artifact links:  
https://11481-70265724-gh.circle-artifacts.com/0/tmp/artifacts/Mattermost_Beta.apk  
https://11480-70265724-gh.circle-artifacts.com/0/tmp/artifacts/Mattermost_Beta.ipa

2020-10-28 19:47 UTC, mattermod commented
Building app in separate branch.

2020-10-28 19:52 UTC, mattermod commented
Successfully building:  
https://circleci.com/gh/mattermost/mattermost-mobile/11526  
https://circleci.com/gh/mattermost/mattermost-mobile/11524

2020-10-28 20:11 UTC, mattermod commented
Artifact links:  
https://11526-70265724-gh.circle-artifacts.com/0/tmp/artifacts/Mattermost_Beta.ipa  
https://11524-70265724-gh.circle-artifacts.com/0/tmp/artifacts/Mattermost_Beta.apk

2020-10-28 22:30 UTC, enahum commented
@josephbaylon when you post the video it takes the local file and plays it, when deleting cache is gets the video from the server, the question here is if the server is serving the video file right and if it is able to buffer. One of the major issues here will be how the server serves the video, we have nothing to tweak the video for playback based on devices and bandwidth as other platform have. I would say a lot of work is needed on the server side to get video playback optimal including transcoding and determine bitrate and other values.

If you try other videos you may get it to play it without issues, even the same video

2020-10-29 16:52 UTC, matthewbirtch requested changes
Awesome work on this @enahum. It's definitely going to be an improvement. I've done a thorough review and have identified the following issues to address. You tell me which ones you can fit in to this PR and which ones you think we should address in separate PR.

1. Images in the gallery don't appear to go fully edge-to-edge. There appears to be black space on either side

<img src="https://user-images.githubusercontent.com/2040554/97600652-a6192800-19df-11eb-95df-a8adcb5f0de6.png" width="414">

2. We should maybe update the 'share' icon so that it more appropriately represents sharing instead of downloading. I've added this icon to the compass [icon font folder on google drive](https://drive.google.com/open?id=1PbbhRVmXOI5BzC305qa42OjMtaVlLEYM&authuser=matthew.birtch%40mattermost.com&usp=drive_fs).

![image](https://user-images.githubusercontent.com/2040554/97594120-baa5f200-19d8-11eb-9048-4165710f8bb4.png)

3. In the gallery footer, the link and and share icon do not quite vertically align with the content on the left.

![image](https://user-images.githubusercontent.com/2040554/97600539-8bdf4a00-19df-11eb-93f8-087454cb0ecc.png)

4. Not sure if this was introduced in this PR, but border around the `x` icon on attachments in the post draft seems to be positioned off slightly. (Screenshot below zoomed in so you can see the misalignment).

![image](https://user-images.githubusercontent.com/2040554/97602288-8256e180-19e1-11eb-9d46-7429c7d7bd7f.png)

5. Also related to the attachment, can we update the position of the progress loader on the attachment so it is inset like below?
![image](https://user-images.githubusercontent.com/2040554/97603432-d3b3a080-19e2-11eb-9a92-d64bcf602262.png)

6. When I tap the share icon, instead of 'Saving' can we change the language to say 'Preparing'?

7. For the video player, can we remove the blue outline on the scrubber control and make it a touch larger and add the shadow?
![image](https://user-images.githubusercontent.com/2040554/97605311-ddd69e80-19e4-11eb-8022-e4c80257a1ad.png)

8. For the preview of a document, can we add spacing as per the below and adjust the button height?
<img src="https://user-images.githubusercontent.com/2040554/97607002-cb5d6480-19e6-11eb-94d2-4b6d6ace8615.png" width="414">

2020-10-29 18:37 UTC, enahum commented
Thread with convo around UX feedback here https://community.mattermost.com/core/pl/ud8ogcx9ib859f7u4hammtyuyy

2020-10-29 18:50 UTC, mattermod commented
Building app in separate branch.

2020-10-29 18:57 UTC, mattermod commented
Successfully building:  
https://circleci.com/gh/mattermost/mattermost-mobile/11569  
https://circleci.com/gh/mattermost/mattermost-mobile/11567

2020-10-29 19:14 UTC, mattermod commented
Artifact links:  
https://11569-70265724-gh.circle-artifacts.com/0/tmp/artifacts/Mattermost_Beta.ipa  
https://11567-70265724-gh.circle-artifacts.com/0/tmp/artifacts/Mattermost_Beta.apk

2020-10-29 22:34 UTC, josephbaylon commented
@enahum I noticed a minor inconsistency for supported document file types. When user taps on the name from the attachment, the app opens the file preview gallery with `Open file` button which is expected. But when user taps on the icon, the app opens the doc right away bypassing the preview gallery.

2020-10-29 22:36 UTC, enahum commented
@josephbaylon that is done on purpose and has always been like that

2020-10-30 20:57 UTC, josephbaylon approved these changes
LGTM. Went through the different areas indicated in the summary and also the JIRA tickets. Also, went through existing TM4J test cases and marked some for update and others for archive. Also added new TM4J test cases based on the changes.

All in all looks good aside from the expected minor issues I brought up last time.

Tested on iPhone X (14.1) and Pixel 3 XL (11) devices.

Regarding e2e, the TM4J test cases found in the JIRA tickets should be enough as guide. However, I'm not sure about the file attachment automation in Detox in general. I have to discuss with @saturninoabril if this is possible for both Android and iOS.

2020-11-07 00:17 UTC, merged

2020-11-07 00:23 UTC, esethna commented
YAY! Nice work all! @enahum @migbot @matthewbirtch