MM-24119 ui update reaction list
mattermost/mattermost-mobile pull request #4854
Opened 2020-10-01 06:02 UTC by josephk96

#### Summary
This PR changed the UI and logic of the reaction list modal and updated the related unit tests.

#### Ticket Link
https://github.com/mattermost/mattermost-server/issues/15492

#### Checklist

- [x] Added or updated unit tests (required for all new features)
- [x] Has UI changes
- [x] Includes text changes and localization file updates

#### Device Information
This PR was tested on:
- iPhone 11 | iOS 14
- iPad Pro (12.9-inch) (4th generation) | iOS 14
- Nexus 6P | Android 10.0 +

#### Screenshots

Screenshot 1: iPhone 11 Portrait
<img width="362" alt="Screen Shot 2020-10-01 at 2 59 55 PM" src="https://user-images.githubusercontent.com/44601888/94773464-c5c82b00-03f6-11eb-80f0-31f105145efc.png">

Screenshot 2: iPhone 11 Landscape
<img width="736" alt="Screen Shot 2020-10-01 at 3 01 01 PM" src="https://user-images.githubusercontent.com/44601888/94773532-ed1ef800-03f6-11eb-8cec-20980ceb1d68.png">

Screenshot 3: Nexus 6P Portrait
<img width="413" alt="Screen Shot 2020-10-01 at 3 00 31 PM" src="https://user-images.githubusercontent.com/44601888/94773502-db3d5500-03f6-11eb-8437-dfe2487e7d3b.png">

Screenshot 4: Nexus 6P Landscape
<img width="835" alt="Screen Shot 2020-10-01 at 3 01 31 PM" src="https://user-images.githubusercontent.com/44601888/94773571-0031c800-03f7-11eb-8c8c-e9a8797e8f92.png">

2020-10-01 06:04 UTC, josephk96 commented
This PR is related to https://github.com/mattermost/mattermost-server/issues/15491 
I'm planning to take this issue, but should I do it after this PR has been merged or should I implement the changes together with this PR?

On another note, regarding e2e testing, I was planning on creating some tests but would it be okay if I create them after test cases for the reaction list component have been defined? However, if you want, I can implement them together with this PR :)

2020-10-08 14:21 UTC, enahum commented
@josephk96 can you revert the changes in non-english translation files ?

2020-10-12 05:57 UTC, josephk96 commented
@enahum done! :)

2020-10-12 14:20 UTC, enahum requested changes
@josephk96 see my comments.

Also I have a few changes to avoid duplicate reactions like `:+1:` and `:thumbsup:` not required for this PR but we could include it ;) let me know

2020-10-12 14:20 UTC, enahum commented on app/screens/reaction_list/reaction_header.js
> +                onLayout={(e) => this.handleOnLayout(e, reaction)}
please refactor this in a way that you don't have anonymous functions here, perhaps the onLayout function from `reaction_header_item` should include the `reaction` in the event or as a second argument as you have here.

2020-10-12 14:20 UTC, enahum commented on app/screens/reaction_list/reaction_header.js
> +                        ref={(ref) => {
use React.createRef instead.

2020-10-12 14:20 UTC, enahum commented on app/screens/reaction_list/reaction_header_item.js
> +            <View onLayout={onLayout}>
see above comment..

2020-10-12 14:20 UTC, enahum commented on app/screens/reaction_list/reaction_list.js
> +    if (isLandscape && DeviceInfo.isTablet()) {
you could use `DeviceTypes` from constants instead of `DeviceInfo` to avoid having to look through the codebase to change it.

2020-10-12 14:20 UTC, enahum commented on app/screens/reaction_list/reaction_list.js
> +            paddingLeft: '5.5%',
why are we using percentages ?

2020-10-12 14:20 UTC, enahum commented on app/screens/reaction_list/reaction_list.js
> +            paddingLeft: DeviceInfo.isTablet() ? '5%' : '3.5%',
same  here

2020-10-12 14:20 UTC, enahum commented on app/screens/reaction_list/reaction_row/reaction_row.js
> +import {getFullName} from '@mm-redux/utils/user_utils';
why are we changing this? the display name should follow my preferences, right ?

2020-10-12 14:55 UTC, enahum commented
@josephk96 also the spacing in landscape seems wrong

2020-10-15 01:17 UTC, matthewbirtch requested changes
Thanks for taking this one on @josephk96. A few things I'm hoping you can help to improve:

1. Would you be able to take another stab at the tabbed UI for this? It looks like it's still using the old styles for the tabbed area. The new design has a different active state, and the spacing and tap areas are larger in the [new design](https://www.figma.com/file/57di9tKmNamEF9TpldBdnY/MM-24119-Mobile-Reactions-List?node-id=1%3A2) to match the updated reaction component. See below for the comparison.

![image](https://user-images.githubusercontent.com/2040554/96060857-a225cb80-0e5f-11eb-97a2-f9b4a8818390.png)

2. Can we adjust the height that the bottom sheet comes up to initially? (see Figma file and screenshot comparison above)

3. In cases where there is no display name and just a user name, It looks like there is extra space to the left of the username causing things to be misaligned (screenshot below)

<img src="https://user-images.githubusercontent.com/2040554/96061643-c71b3e00-0e61-11eb-8071-e9b599858c1c.png" width="380">

Let me know if you need help with the Figma design files to get dimensions or any other values.

I'll take another look at things in detail again when the above is updated. Thanks again!

2020-10-15 06:20 UTC, josephk96 commented
Thanks @enahum and @matthewbirtch for the feedback :) 
@enahum , for the landscape spacing issue, I did not change the spacing there - please refer to the screenshot below, which is taken on my phone in the Community channel. If you would like though, I can reduce the spacing to make it look more consistent with the portrait spacing.

![image](https://user-images.githubusercontent.com/44601888/96084303-d6e66100-0ef9-11eb-846b-cc5546460c1d.png)

@matthewbirtch I did not implement the new UI for the tabbed area because it was a separate Jira issue, but I can make changes and implement it into this PR if it makes more sense to do so.

2020-10-15 13:38 UTC, matthewbirtch commented
> @matthewbirtch I did not implement the new UI for the tabbed area because it was a separate Jira issue, but I can make changes and implement it into this PR if it makes more sense to do so.

Are you referring to [this ticket](https://github.com/mattermost/mattermost-server/issues/15491)? I don't know if you need to wait for this to be done before updating the UI style in the tabs. Unless you're planning on using the exact same component? I think the note in the original ticket about being consistent with the new reaction style is more of an aesthetic reference point rather than being a blocker. But if you're taking that other ticket too, maybe it makes sense to complete that one first before completing this one?

2020-10-26 01:00 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

/cc @jasonblais @jfrerich

2020-10-26 21:28 UTC, jfrerich commented
Hi @josephk96! There is a merge conflict that needs to be resolved, but I just want to check in and see if you need any assistance from one of our developers.  It looks like you've got quite a lot of changes and close to finishing this PR.  Do you need any help?

2020-11-25 13:31 UTC, josephk96 commented
> Hi @josephk96! There is a merge conflict that needs to be resolved, but I just want to check in and see if you need any assistance from one of our developers. It looks like you've got quite a lot of changes and close to finishing this PR. Do you need any help?

Hi @jfrerich ! Sorry for the late reply, I've been quite busy these days. I'm having a hard time finding time to resolve the comments for this PR, let alone https://github.com/mattermost/mattermost-server/issues/15491 . Do you think I should close this PR or wait until someone finishes the issue I linked (it's quite related to this one) and then I finish resolving the comments left here?

2021-05-26 09:05 UTC, lindy65 commented
Hi @josephk96 - I'm helping review stale PRs and see you're waiting on https://github.com/mattermost/mattermost-server/issues/15491 to be fixed before continuing.  For now, I'll close this PR - feel free to re-open at any time in the future :)

I've re-added the "Up for Grabs" label on https://github.com/mattermost/mattermost-server/issues/15492

//cc @enahum @matthewbirtch

2021-05-26 09:05 UTC, closed without merging