MM-28653 Detox/E2E: Add jest-junit, jest-html-reporters and pathbuilders for test report/artifacts
mattermost/mattermost-mobile pull request #4888
Opened 2020-10-13 09:46 UTC by saturninoabril

#### Summary
Add jest-junit, jest-html-reporters and pathbuilders for test report/artifacts

#### Ticket Link
Jira ticket - https://mattermost.atlassian.net/browse/MM-28653

#### Screenshots
<img width="506" alt="Screen Shot 2020-10-13 at 5 37 38 PM" src="https://user-images.githubusercontent.com/5334504/95844511-92cd5200-0d7b-11eb-9286-35a4fce108fc.png">
![Screen Shot 2020-10-13 at 5 40 13 PM](https://user-images.githubusercontent.com/5334504/95844534-995bc980-0d7b-11eb-8d6a-519f56e1c764.png)

2020-10-13 10:13 UTC, enahum approved these changes
LGTM.

Question, the reports only run for release mode, right?

2020-10-13 10:14 UTC, enahum commented
looking forward to have this enabled with CI builds 🎉

2020-10-13 10:15 UTC, saturninoabril commented
Yes, that's correct and that's most likely to run in CI.

2020-10-13 16:11 UTC, josephbaylon requested changes
@saturninoabril Not sure what the issue is but I'm getting an error when building in this PR which I'm not getting when I build on master. I made sure to delete my `detox/node_modules` and did another `npm install` but still getting the error below,
```
josephbaylon@Josephs-MacBook-Pro detox % npm run e2e:android-build-release

> mattermost-mobile-e2e@ e2e:android-build-release /Users/josephbaylon/Projects/original/mattermost-mobile/detox
> detox build -c android.emu.release

detox[78210] ERROR: [cli.js] SyntaxError: Unexpected token .

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mattermost-mobile-e2e@ e2e:android-build-release: `detox build -c android.emu.release`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mattermost-mobile-e2e@ e2e:android-build-release script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/josephbaylon/.npm/_logs/2020-10-13T16_07_28_083Z-debug.log
```


Here's the content of the log file,
```
josephbaylon@Josephs-MacBook-Pro detox % cat /Users/josephbaylon/.npm/_logs/2020-10-13T16_07_28_083Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/Users/josephbaylon/.nvm/versions/node/v10.19.0/bin/node',
1 verbose cli   '/Users/josephbaylon/.nvm/versions/node/v10.19.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'e2e:android-build-release' ]
2 info using npm@6.14.8
3 info using node@v10.19.0
4 verbose run-script [ 'pree2e:android-build-release',
4 verbose run-script   'e2e:android-build-release',
4 verbose run-script   'poste2e:android-build-release' ]
5 info lifecycle mattermost-mobile-e2e@~pree2e:android-build-release: mattermost-mobile-e2e@
6 info lifecycle mattermost-mobile-e2e@~e2e:android-build-release: mattermost-mobile-e2e@
7 verbose lifecycle mattermost-mobile-e2e@~e2e:android-build-release: unsafe-perm in lifecycle true
8 verbose lifecycle mattermost-mobile-e2e@~e2e:android-build-release: PATH: /Users/josephbaylon/.nvm/versions/node/v10.19.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/josephbaylon/Projects/original/mattermost-mobile/detox/node_modules/.bin:/Users/josephbaylon/.rvm/gems/ruby-2.7.0/bin:/Users/josephbaylon/.rvm/gems/ruby-2.7.0@global/bin:/Users/josephbaylon/.rvm/rubies/ruby-2.7.0/bin:/Users/josephbaylon/Library/Android/sdk/emulator:/Users/josephbaylon/Library/Android/sdk/platform-tools:/Users/josephbaylon/Library/Android/sdk/tools:/Users/josephbaylon/Library/Android/sdk/tools/bin:/Users/josephbaylon/.nvm/versions/node/v10.19.0/bin:/Users/josephbaylon/Library/Android/sdk/emulator:/Users/josephbaylon/Library/Android/sdk/platform-tools:/Users/josephbaylon/Library/Android/sdk/tools:/Users/josephbaylon/Library/Android/sdk/tools/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Library/Apple/usr/bin:/Users/josephbaylon/go/bin:/usr/local/go/bin:/Users/josephbaylon/.rvm/bin:/Users/josephbaylon/go/bin:/usr/local/go/bin:/Users/josephbaylon/.rvm/bin
9 verbose lifecycle mattermost-mobile-e2e@~e2e:android-build-release: CWD: /Users/josephbaylon/Projects/original/mattermost-mobile/detox
10 silly lifecycle mattermost-mobile-e2e@~e2e:android-build-release: Args: [ '-c', 'detox build -c android.emu.release' ]
11 silly lifecycle mattermost-mobile-e2e@~e2e:android-build-release: Returned: code: 1  signal: null
12 info lifecycle mattermost-mobile-e2e@~e2e:android-build-release: Failed to exec e2e:android-build-release script
13 verbose stack Error: mattermost-mobile-e2e@ e2e:android-build-release: `detox build -c android.emu.release`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/Users/josephbaylon/.nvm/versions/node/v10.19.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/Users/josephbaylon/.nvm/versions/node/v10.19.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid mattermost-mobile-e2e@
15 verbose cwd /Users/josephbaylon/Projects/original/mattermost-mobile/detox
16 verbose Darwin 19.6.0
17 verbose argv "/Users/josephbaylon/.nvm/versions/node/v10.19.0/bin/node" "/Users/josephbaylon/.nvm/versions/node/v10.19.0/bin/npm" "run" "e2e:android-build-release"
18 verbose node v10.19.0
19 verbose npm  v6.14.8
20 error code ELIFECYCLE
21 error errno 1
22 error mattermost-mobile-e2e@ e2e:android-build-release: `detox build -c android.emu.release`
22 error Exit status 1
23 error Failed at the mattermost-mobile-e2e@ e2e:android-build-release script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

2020-10-14 16:15 UTC, saturninoabril commented
Weird, honestly I can't see the problem as it's working fine on me. I don't think the changes here have anything to do with Detox Android build.
Miguel or Elias, can you help us validate the issue if Android test is broken or working with you?  Thanks in advance!

2020-10-14 17:30 UTC, josephbaylon approved these changes
LGTM. It is now building successfully for me locally once I upgraded to node v14.13.1. Will probably need to figure out the minimum version as this would require some devs to upgrade.

2020-10-14 18:09 UTC, saturninoabril commented
Sorry for the hassle. It's due to the optional chaining operator at `path_builder.js` which is not supported for node v13 and below. `babel` works during test but not on build. I've changed the implementation and tested to be working with v10. Thanks for testing @josephbaylon!

2020-10-14 18:27 UTC, merged

2020-10-14 18:33 UTC, josephbaylon commented
@saturninoabril No worries! I retested with both node v10 and v14 and they seem to work fine now. Thanks for the changes!

2020-10-14 18:34 UTC, saturninoabril commented
Awesome, thanks for testing again!