[MM-23391] Sort sidebar teams order by user preference
mattermost/mattermost-mobile pull request #4911
Opened 2020-10-20 23:28 UTC by edtrist

#### Summary
Sorts the teams list in the mobile app by the order specified by the user in the webapp (in the `teams_order` preference). Other teams not included in the preference list (i.e. teams joined after the order is set) are sorted by their display name. Uses a very similar method to the webapp.

Added/updated unit tests to reflect the new functionality.

#### Ticket Link
Fixes https://github.com/mattermost/mattermost-server/issues/14200
https://mattermost.atlassian.net/browse/MM-23391

#### Checklist
- [x] Added or updated unit tests (required for all new features)

#### Device Information
iPhone 11 (simulator) - iOS 14.0
Pixel 3a (emulator) - Android 10

#### Screenshots
(below video: android on left - webapp on right)
<img src="https://user-images.githubusercontent.com/6654758/96654094-693f9800-1332-11eb-8b6a-b53e157be945.gif"   width=45% alt="Android">&nbsp;<img src="https://user-images.githubusercontent.com/6654758/96654092-68a70180-1332-11eb-86e1-d400fb1f10ab.png" width=50% alt="iOS">

2020-10-20 23:28 UTC, mattermod commented
Hello @edtrist,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2020-10-20 23:40 UTC, esethna approved these changes
Awesome!

2020-10-20 23:48 UTC, esethna commented
@edtrist let us know if you're interested in any of these other mobile tickets up for grabs! For example:

https://github.com/mattermost/mattermost-server/issues/14157
https://github.com/mattermost/mattermost-server/issues/14142
https://github.com/mattermost/mattermost-server/issues/14604
or [others](https://github.com/mattermost/mattermost-server/issues?q=is%3Aopen+is%3Aissue+label%3A%22Area%2FEnd+User+Feature%22+label%3A%22Tech%2FReact+Native%22+label%3A%22Up+For+Grabs%22)

2020-10-28 12:57 UTC, enahum requested changes

2020-10-28 12:57 UTC, enahum commented on app/mm-redux/selectors/entities/teams.test.js
> +import {General, Preferences} from '../../constants';
```suggestion
import {General, Preferences} from '@mm-redux/constants';
```

2020-10-28 12:57 UTC, enahum commented on app/mm-redux/selectors/entities/teams.ts
> +import {Permissions, Preferences} from '../../constants';
```suggestion
import {Permissions, Preferences} from '@mm-redux/constants';
```

2020-11-02 23:30 UTC, edtrist commented on app/mm-redux/selectors/entities/teams.ts
> +    (state: GlobalState) => state,
Done - thanks :)

2020-11-06 11:01 UTC, enahum requested changes
Code looks good, but I think we are missing the fact that when a person logs in the first team being selected should match the first ordered team, don't you agree?

relevant code here: https://github.com/mattermost/mattermost-mobile/blob/master/app/actions/views/select_team.js#L52

@esethna can  you comment if that would be the expected behavior?

2020-11-07 00:19 UTC, esethna commented
@enahum agree with that

2020-11-07 20:58 UTC, edtrist commented
@enahum @esethna Sounds good - I've made some changes to do that. Let me know what you think!

2020-11-18 01:00 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

/cc @jasonblais @jfrerich @emilyacook

2020-11-18 11:14 UTC, enahum requested changes
almost there

2020-11-18 11:14 UTC, enahum commented on app/mm-redux/utils/team_utils.ts
> +    if (!teams) {
```suggestion
    if (!teams?.length) {
```

2020-11-18 11:14 UTC, enahum commented on app/mm-redux/utils/team_utils.ts
> +    });
I guess this block should execute only if `teamsOrder` has values

2020-12-07 01:00 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

/cc @jasonblais @jfrerich @emilyacook

2020-12-09 19:24 UTC, jasonblais commented
@enahum looks like this is ready for review

2020-12-10 12:15 UTC, enahum approved these changes

2020-12-10 16:09 UTC, mattermod commented
Building app in separate branch.

2020-12-10 16:15 UTC, mattermod commented
Successfully building:  
https://circleci.com/gh/mattermost/mattermost-mobile/12489  
https://circleci.com/gh/mattermost/mattermost-mobile/12488

2020-12-10 16:58 UTC, mattermod commented
Building app in separate branch.

2020-12-10 16:58 UTC, mattermod commented
Successfully building:  
https://circleci.com/gh/mattermost/mattermost-mobile/12489  
https://circleci.com/gh/mattermost/mattermost-mobile/12488

2020-12-10 17:21 UTC, josephbaylon commented
@edtrist @enahum This is getting compilation error when building apk. Please take a look. Thanks.

2020-12-10 17:23 UTC, enahum commented
@Adovenmuehle looks like rudder messed up again?

2020-12-10 17:24 UTC, Adovenmuehle commented
I don't have access, what's the error?

2020-12-10 17:26 UTC, josephbaylon commented
@Adovenmuehle 
```
> Task :rudderstack_rudder-sdk-react-native:compileReleaseJavaWithJavac FAILED
/home/circleci/*****************/node_modules/@rudderstack/rudder-sdk-react-native/android/src/main/java/com/rudderstack/react/android/RNRudderSdkModule.java:102: error: putDeviceToken(String) is not public in RudderContext; cannot be accessed from outside package
            rudderContext.putDeviceToken(token);
                         ^
Note: /home/circleci/*****************/node_modules/@rudderstack/rudder-sdk-react-native/android/src/main/java/com/rudderstack/react/android/RNRudderSdkModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error
```

2020-12-10 17:26 UTC, enahum commented
@Adovenmuehle 

```

Task :rudderstack_rudder-sdk-react-native:processReleaseManifest
> Task :rudderstack_rudder-sdk-react-native:generateReleaseRFile
> Task :rn-fetch-blob:bundleLibCompileRelease
> Task :sentry_react-native:checkReleaseManifest
> Task :sentry_react-native:compileReleaseRenderscript NO-SOURCE
> Task :sentry_react-native:generateReleaseBuildConfig
> Task :rudderstack_rudder-sdk-react-native:javaPreCompileRelease

> Task :rudderstack_rudder-sdk-react-native:compileReleaseJavaWithJavac FAILED
/home/circleci/*****************/node_modules/@rudderstack/rudder-sdk-react-native/android/src/main/java/com/rudderstack/react/android/RNRudderSdkModule.java:102: error: putDeviceToken(String) is not public in RudderContext; cannot be accessed from outside package
            rudderContext.putDeviceToken(token);
                         ^
Note: /home/circleci/*****************/node_modules/@rudderstack/rudder-sdk-react-native/android/src/main/java/com/rudderstack/react/android/RNRudderSdkModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error
```

2020-12-10 17:26 UTC, Adovenmuehle commented
Forwarding to Rudder now.

2020-12-10 18:33 UTC, Adovenmuehle commented
Rudder got back to me. They said it's been fixed in a newer release and recommended upgrading to the latest.

2020-12-10 18:34 UTC, enahum commented
@migbot can you submit a PR upgrading Rudder, then we can update this PR.

Thanks bruv.

2020-12-10 18:52 UTC, enahum commented
@Adovenmuehle we are already using the latest

2020-12-10 18:54 UTC, enahum commented
/update-branch

2020-12-10 19:14 UTC, mattermod commented
Building app in separate branch.

2020-12-10 19:22 UTC, mattermod commented
Successfully building:  
https://circleci.com/gh/mattermost/mattermost-mobile/12509  
https://circleci.com/gh/mattermost/mattermost-mobile/12507

2020-12-10 19:32 UTC, mattermod commented
Artifact links:  
https://12509-70265724-gh.circle-artifacts.com/0/tmp/artifacts/Mattermost_Beta.apk  
https://12507-70265724-gh.circle-artifacts.com/0/tmp/artifacts/Mattermost_Beta.ipa

2020-12-10 20:13 UTC, josephbaylon approved these changes
LGTM. Mobile teams list now follows team order preference, sorts accordingly when order is updated, and sorts alphabetically when new teams are added.

This is a good candidate to automate for e2e. However, teams list and select team e2e components are currently being updated in https://github.com/mattermost/mattermost-mobile/pull/4990 so we can table the e2e for now. I created a JIRA task [MM-31272](https://mattermost.atlassian.net/browse/MM-31272) and a corresponding TM4J test case, in case you or somebody else wants to pick up later once other PRs are merged.

2020-12-10 20:35 UTC, merged