MM-30076 Detox/E2E: Update UI test structure for reusability
mattermost/mattermost-mobile pull request #4931
Opened 2020-10-28 15:34 UTC by saturninoabril

#### Summary
Update UI test structure for reusability.

Move all UI screen/component at `@support/ui`
  - `screen` should match the `screen` we're using in the app to easily follow UI flow and make more readable
  - `components` are unit/screen of the screen which may be used in different screen/component
  - all `testID`s should be placed either in screen/component and not in the test (`*.e2e.js`) file as much as possible.
  - UI text can be in the screen/component or in the test file. No strict requirement currently.

Docs to follow.

Other changes:
- testIDs

#### Ticket Link
Jira ticket - https://mattermost.atlassian.net/browse/MM-30076

#### Device Information
This PR was tested on: iOS simulator and Android emulator (both debug and release)

2020-10-28 18:38 UTC, josephbaylon requested changes
@saturninoabril Yay for page objects!! 🎉  

Can you please check the 4 tests below?

A. Android
I'm getting these two failures consistently on Android (iOS passes on both),
![Screen Shot 2020-10-28 at 10 57 35 AM](https://user-images.githubusercontent.com/487991/97478065-ab0da700-190d-11eb-9822-5fa73d6684f9.png)
![Screen Shot 2020-10-28 at 10 57 11 AM](https://user-images.githubusercontent.com/487991/97478074-af39c480-190d-11eb-9a98-590c352488fe.png)

B. iOS
I'm getting these two failures consistently on iOS (Android passes on both),
![Screen Shot 2020-10-28 at 11 34 16 AM](https://user-images.githubusercontent.com/487991/97481232-bcf14900-1911-11eb-9f23-db41465247a2.png)
![Screen Shot 2020-10-28 at 11 37 17 AM](https://user-images.githubusercontent.com/487991/97481428-0b9ee300-1912-11eb-9f88-129ec2f6762b.png)

2020-10-29 10:53 UTC, saturninoabril commented
@josephbaylon Thanks for testing! Android failing tests should be fixed by https://github.com/mattermost/mattermost-mobile/pull/4931/commits/1edf38b81bc393d453c8cf608aeac3a34cc3178b. I can't repro the failing tests on iOS. It's consistently passing on me. I did a cleanup in Autocomplete - https://github.com/mattermost/mattermost-mobile/pull/4931/commits/d674ba6414c81826a231a1cc216568f900484f97. Please try again.

2020-10-29 17:05 UTC, josephbaylon approved these changes
LGTM. Awesome work standardizing and implementing page objects! All tests passed locally.

I'm guessing the docs should also be updated with this approach.

2020-10-29 17:11 UTC, saturninoabril commented
Thanks and yes, docs on the way.

2020-11-03 10:09 UTC, enahum approved these changes

2020-11-03 10:11 UTC, merged