update dependencies
mattermost/mattermost-mobile pull request #4958
Opened 2020-11-11 22:43 UTC by enahum

#### Summary
Update dependencies including:
* notifications: We should test push notifications and replies from the notification (in-app, background, closed) -> open from a push notification, session expired and test notification on Android.
* keychain: the previous update for this lib caused some Android devices to degrade the cold start (we need to test that) -> @hahmadia I think you were affected by this, thus we reverted. If I'm correct you have a OnePlus Android device,  would you please give it a try?
* detox

2020-11-11 23:05 UTC, mattermod commented
Building app in separate branch.

2020-11-11 23:13 UTC, mattermod commented
Successfully building:  
https://circleci.com/gh/mattermost/mattermost-mobile/11815  
https://circleci.com/gh/mattermost/mattermost-mobile/11814

2020-11-11 23:26 UTC, mattermod commented
Artifact links:  
https://11815-70265724-gh.circle-artifacts.com/0/tmp/artifacts/Mattermost_Beta.ipa  
https://11814-70265724-gh.circle-artifacts.com/0/tmp/artifacts/Mattermost_Beta.apk

2020-11-12 14:09 UTC, hahmadia commented
Yes I tried and it boots up fast. Thanks

2020-11-12 14:10 UTC, enahum commented
Awesome @hahmadia feel free to review the PR :)

2020-11-12 14:14 UTC, hahmadia commented
I'm sorry @enahum . Right after I say that, I tried a few more times and I came across same problem. Posting a video in mobile channel. Sorry! Did not mean to cause premature excitement

2020-11-12 22:48 UTC, hahmadia requested changes
No review comments but as discussed this should be a no merge as it takes way too long to boot up.

2020-11-13 17:59 UTC, hahmadia approved these changes
Code looks good.
Just a note but I think it's not a bad idea to get @anurag6713 in on these reviews as a way to help him get familiar with our code review process.

2020-11-13 18:52 UTC, mattermod commented
Building app in separate branch.

2020-11-13 18:59 UTC, mattermod commented
Successfully building:  
https://circleci.com/gh/mattermost/mattermost-mobile/11924  
https://circleci.com/gh/mattermost/mattermost-mobile/11923

2020-11-13 19:13 UTC, mattermod commented
Artifact links:  
https://11924-70265724-gh.circle-artifacts.com/0/tmp/artifacts/Mattermost_Beta.ipa  
https://11923-70265724-gh.circle-artifacts.com/0/tmp/artifacts/Mattermost_Beta.apk

2020-11-16 15:49 UTC, josephbaylon commented
@enahum I'm experiencing an issue with opening the channel from push notifications when app is closed (not backgrounded/minimized). This is only for iOS (Android works fine). I also tested v1.37 and it works there fine.

Steps,
1. As User A, go to Channel A then close app (not background) with notifications set to all activities
2. As User B, go to Channel B where User A is also a member and post a message
3. As User A, tap on the push notification

Expected: App opens and redirects channel to Channel B
Observed: App opens and gets stuck on Channel A

Note: When user backgrounds/minimizes the app, the redirection happens correctly.

2020-11-17 07:53 UTC, anurag6713 approved these changes

2020-11-17 23:05 UTC, josephbaylon commented
@enahum The issue with iOS redirecting to correct channel is now fixed. Also verified Android still works.

However, there's another issue which I don't know if it is a side-effect of the changes. This is for Android only when user closes app using device back button. I couldn't repro this on v1.37 build 334.

Steps,
1. Login to server and go to a channel
2. Press device back button to close app
3. Open app again.
4. Repeat steps 2 and 3 multiple times (it happened to me about the 3rd time)

Expected: App should not continue functioning and not display black screen
Observed: App displays black screen and user needs to close and re-open again to see the channel

2020-11-18 00:39 UTC, enahum commented
hey @josephbaylon thanks, that was a great finding. I had to apply a patch to the `react-native-localize` dependency on Android that was causing the behavior you found.

2020-11-18 01:27 UTC, josephbaylon commented
@enahum Although the crash was resolved, the push notification for Android completely stopped working for me. iOS still works fine though.

2020-11-18 01:31 UTC, enahum commented
@josephbaylon it makes zero sense as the last commit is only about patching a totally unrelated dependency. Please check that the notification is actually being sent to the Android device

2020-11-18 01:44 UTC, josephbaylon commented
@enahum I tested v1.37 build 334 and Android still receives push notifications. I tried the same thing on emulator and works for build 334 but not on this PR build.

Does it work for you locally? Maybe you can kick off a new CI build from your local.

2020-11-18 01:46 UTC, enahum commented
@josephbaylon yes it did work, and previous PR build worked for you too, right?

I'll give it a go tomorrow and build it if needed

2020-11-18 01:48 UTC, josephbaylon commented
@enahum Yes, the previous build worked for Android in terms of push notifications. I'll continue tomorrow once you've kicked off the new build. Thanks

2020-11-18 14:47 UTC, josephbaylon approved these changes
LGTM. Per @enahum the latest build is receiving notifications for him on Android so I'm going to go ahead and approve this PR. iOS works fine on my device for notifications.

Also tested detox e2e and fastlane builds.

2020-11-19 02:42 UTC, enahum commented on android/app/src/main/java/com/mattermost/rnbeta/CustomPushNotification.java
> +            testNotification = userInfoBundle.getBoolean("test");
There is a local notification for scheduling and another notification to trigger a local test

2020-11-19 02:44 UTC, enahum commented
@migbot answered

2020-11-19 02:45 UTC, merged

2020-11-19 02:45 UTC, mattermod commented
Cherry pick is scheduled.