MM-30478 [v2] watermelondb schema manager
mattermost/mattermost-mobile pull request #4997
Opened 2020-12-02 14:35 UTC by avinashlng1080

#### Summary
This PR holds the schema manager which is basically a function returning an object of type SQLiteAdapterOptions that will be consumed by the wdb database.

Please note that the parameter dbPath can either hold the file-path of the AppGroup or the database name.

With regards to the migration process' status, we can also pass in a few callbacks within the optional parameter **migrationEvents**.  A patch to the @nozbe/watermelondb module will trigger those callbacks -  onSuccess, onFailure, onStarted -  when it performs a migration.  These will help us animate a progress bar for example.   A PR has also been sent to wdb repo and it is currently under review ( https://github.com/Nozbe/WatermelonDB/pull/880 )

@enahum please let me know if there is anything to add.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-30478

2020-12-03 11:05 UTC, avinashlng1080 commented on types/database/user.d.ts
> +    timeZone: string[];
For the time being, those are temporary types.  NotifyProps, Props and timezone will contain JSON object.  Once we finalized their shapes, we will create their types definition and update them there.

2020-12-03 11:08 UTC, avinashlng1080 commented on app/database/server/models/draft.ts
> +    @json('files', (rawJson) => rawJson) files!: string[]
In WatermelonDB, we can store JSON values; in the background, the json objects are serialized to strings.  The callback is simply a sanitizer function that we can use to prune the object before serving it to the caller.  Currently, we are returning the value as stored in the DB ( equivalent to JSON.parse() ) but when the time comes to work on this part, we will update the sanitizer callback accordingly.

2020-12-06 14:48 UTC, enahum requested changes
For me is clear that this PR needs work, I see the adapter being created, but no way to delete the database nor to switch to and make another database the active one as per the ticket.

2020-12-06 14:48 UTC, enahum commented on app/database/managers/schema_manager.ts
> + * @param {string} dbPath - The dbName or filePath (e.g. AppGroup path) for the database
I rather separate this two as in `path` and `name` and then construct the `dbName` based on those two values where  `path` default value is an empty string and `name` is *default*

2020-12-06 14:48 UTC, enahum commented on app/database/managers/schema_manager.ts
> +        ...(Boolean(migrationEvents) && {migrationEvents}),
what does this do when the first check is false?

2020-12-06 14:48 UTC, enahum commented on app/database/managers/schema_manager.ts
> +        ...(Boolean(migrationSteps) && migrationSteps!.length > 0 && {migrations: schemaMigrations({migrations: migrationSteps!})}),
same question

2020-12-06 14:49 UTC, enahum commented
Also the database creation is not adding or updating any records in the default database.

2021-01-09 17:07 UTC, avinashlng1080 commented on app/screens/server/list_of_servers/index.tsx
> +            {servers.length > 0 && (
This is just a test component - I'm going to close this PR as it is not yet ready for review.

2021-01-09 17:08 UTC, closed without merging