Migrate to typescript App bindings related files
mattermost/mattermost-mobile pull request #5020
Opened 2020-12-10 12:55 UTC by larkox

#### Summary
Migrate to typescript files related to the App effort, in particular those regarding bindings.

#### Ticket Link
None

2021-01-27 09:43 UTC, larkox commented on app/actions/views/channel.test.ts
> +        // Should it accept null? Should this testcase be renamed?
`handleSelectChannelByName` is supposed to receive a string as a second parameter, but here in the test (and I think nowhere else) is receiving null. Therefore either we accept null as a parameter, or we use the empty string in the test as I did.

2021-01-27 09:47 UTC, larkox commented on app/store/initial_state.ts
> +    // device: {
These are not defined in the GlobalState type. Either these are no longer used and the types are right (and should be removed completely) or this is right and the types are outdated, so the types must be updated. Do you know what is it?

2021-05-19 11:15 UTC, larkox commented
@migbot conflicts resolved

2021-06-30 20:30 UTC, enahum requested changes
Also make sure all end to end tests run without issues

2021-06-30 20:30 UTC, enahum commented on app/screens/channel_info/__snapshots__/channel_info_header.test.tsx.snap
> -          testID="channel_info.header.header"
Please bring this back

2021-06-30 20:30 UTC, enahum commented on app/screens/channel_info/bindings/bindings.tsx
> +    intl?: typeof intlShape;
why is this optional?

2021-06-30 20:30 UTC, enahum commented on app/screens/channel_info/channel_info_header.tsx
> -                                    testID={`${testID}.header`}
do not remove any testID!!!! this is breaking end to end tests

2021-06-30 20:30 UTC, enahum commented on app/screens/channel_info/channel_info_row.tsx
>  };
this need to be set in the props deconstructor, it won't work as defaultProps

2021-06-30 20:30 UTC, enahum commented on test/test_helper.ts
> -    generateId = () => {
Why was this removed? is being used in this file

2021-07-07 13:08 UTC, larkox commented on app/actions/websocket/index.ts
> +                    const {data: myData}: any = await dispatch(loadChannelsForTeam(currentTeamId, true));
If I have to guess, probably I was trying to make it work before just migrating the related file.

2021-07-07 13:11 UTC, larkox commented on app/actions/views/channel.ts
> +                const result = await dispatch(joinChannel(currentUserId, '', channel.id, ''));
Should not give issues, but it is probably cleaner with an optional parameter. Will fix.

2021-07-07 13:19 UTC, larkox commented on app/actions/views/channel.ts
> +        dispatch(toggleDMChannel(channel.teammate_id || '', 'false'));
If I have to guess, this function is always called with a DM Channel, so there is always a teammate_id. We could use something like `channel.teammate_id!` in that case, but sounds a bit... dangerous in this place.

Also, this is the nearest to the current behavior. I could add an early return, but I don't know the code surrounding this to make sure doing that will not introduce any unexpected problem.

2021-07-07 16:49 UTC, larkox commented on app/actions/views/channel.ts
> +                                data: {groupsByChannelId: getAllGroupsAssociatedToChannelsInTeam},
It seems that the types for `app/client/rest/groups.ts` are wrong. Will fix on that side.

2021-07-07 17:15 UTC, larkox commented
Closing this due to the age, size and multiple merge that this branch has suffered. If we were to tackle one more time this task, we will do it in smaller pieces.

2021-07-07 17:15 UTC, closed without merging