[MM-31376] Do not subtract offset from accessories container
mattermost/mattermost-mobile pull request #5042
Opened 2020-12-15 18:26 UTC by migbot

#### Summary
Subtracting from `kHeight` also affected the accessories container's Y position since `kHeight` is used there as well. Fixed by using `_observingInputAccessoryView.keyboardHeight` instead.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-31376

#### Device Information
This PR was tested on:
* iPhone SE, 11, and 12 simulators

#### Screenshots
![Simulator Screen Shot - iPhone 11 Pro - 2020-12-15 at 11 21 59](https://user-images.githubusercontent.com/3208014/102256220-5677b880-3ec8-11eb-8f1c-09f708c01d1c.png)

2020-12-15 22:57 UTC, amyblais commented
Removing this from v1.38 for now; not a hard blocker and release tests should wrap up soon.

2020-12-16 17:41 UTC, enahum requested changes
small change and it should be good to go

2020-12-16 17:41 UTC, enahum commented on app/components/post_draft/post_draft.js
> +                onLayout={onLayout}
this is not being used anywhere

2020-12-16 17:57 UTC, mattermod commented
Building app in separate branch.

2020-12-16 18:04 UTC, mattermod commented
Successfully building:  
https://circleci.com/gh/mattermost/mattermost-mobile/12700  
https://circleci.com/gh/mattermost/mattermost-mobile/12698

2020-12-16 18:11 UTC, enahum approved these changes

2020-12-16 18:14 UTC, mattermod commented
Artifact links:  
https://12700-70265724-gh.circle-artifacts.com/0/tmp/artifacts/Mattermost_Beta.apk  
https://12698-70265724-gh.circle-artifacts.com/0/tmp/artifacts/Mattermost_Beta.ipa

2020-12-16 18:38 UTC, josephbaylon approved these changes
LGTM. Autocomplete in single line and multi-line and attachment messages always appears on the top most edge of post draft and doesn't block post draft anymore. User is still able to select option from autocomplete. Tested on channel and thread.

Tested on iPhone X (14.3) and Pixel 3 XL (11) devices.

2020-12-18 02:14 UTC, merged

2020-12-18 02:14 UTC, mattermod commented
Cherry pick is scheduled.

2020-12-18 19:28 UTC, amyblais commented
/cherry-pick release-1.38

2020-12-18 19:28 UTC, mattermod commented
Cherry pick is scheduled.

2020-12-18 19:28 UTC, mattermod commented
Error trying doing the automated Cherry picking. Please do this manually

```
+++ Updating remotes...
Fetching upstream
Failed to add the RSA host key for IP address '140.82.112.3' to the list of known hosts (/app/.ssh/known_hosts).
From github.com:mattermost/mattermost-mobile
   fa8a26d68..f838d8de1  MM-29104-avatar-list-component -> upstream/MM-29104-avatar-list-component
   7aebfd0b1..70e5cace1  release-1.39 -> upstream/release-1.39
 * [new branch]          rudder       -> upstream/rudder
 * [new tag]             v1.38.0      -> v1.38.0
Fetching origin
Failed to add the RSA host key for IP address '140.82.112.3' to the list of known hosts (/app/.ssh/known_hosts).
+++ Updating remotes done...
+++ Creating local branch automated-cherry-pick-of-mattermost-mobile-#5042-upstream-release-1.38-1608319718
Switched to a new branch 'automated-cherry-pick-of-mattermost-mobile-#5042-upstream-release-1.38-1608319718'
Branch 'automated-cherry-pick-of-mattermost-mobile-#5042-upstream-release-1.38-1608319718' set up to track remote branch 'release-1.38' from 'upstream'.

+++ About to attempt cherry pick of PR #5042 with merge commit 8fb6510a3283a6eeb4766410a521852a0795119c.

error: could not apply 8fb6510a3... [MM-31376] Do not subtract offset from accessories container (#5042)
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'

+++ Conflicts detected:

UU app/screens/thread/__snapshots__/thread.ios.test.js.snap
Aborting.

+++ Aborting in-progress git cherry-pick.

+++ Returning you to the master branch and cleaning up.

```

2020-12-18 19:29 UTC, enahum commented
@migbot can you please cherry-pick this PR manually ?