Give a enough warning when archiving a channel
mattermost/mattermost-mobile pull request #5061
Opened 2020-12-21 04:36 UTC by nobuto-m

Archiving a channel in Mattermost is actually stronger than it sounds.
It will remove the channel from the user interface, and the contents
cannot be viewed, shared, or searched out of the box.
https://docs.mattermost.com/help/getting-started/organizing-conversations.html#archiving-a-channel

Let's give a enough warning similar to the web version.

Closes: #4806

#### Summary

#### Ticket Link

#### Checklist

- [ ] Added or updated unit tests (required for all new features)
- [ ] Has UI changes
- [ ] Includes text changes and localization file updates

#### Device Information
This PR was tested on:  

#### Screenshots

2020-12-21 04:36 UTC, mattermod commented
Hello @nobuto-m,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

Per the [Mattermost Contribution Guide](https://developers.mattermost.com/contribute/getting-started/), we need to add you to the list of [approved contributors](https://docs.google.com/spreadsheets/d/1NTCeG-iL_VS9bFqtmHSfwETo5f-8MQ7oMDE5IUYJi_Y/pubhtml?gid=0&single=true) for the Mattermost project.

**Please help complete the Mattermost [contribution license agreement](http://www.mattermost.org/mattermost-contributor-agreement/)?**
Once you have signed the CLA, please comment with `/check-cla` and confirm that the CLA check is green.

This is a standard procedure for many open source projects.

Please let us know if you have any questions.

We are very happy to have you join our growing community! If you're not yet a member, please consider joining our [Contributors community channel](https://pre-release.mattermost.com/core/channels/tickets) to meet other contributors and discuss new opportunities with the core team.

2020-12-21 04:48 UTC, nobuto-m commented
/check-cla

2020-12-21 10:49 UTC, enahum requested changes
Thanks @nobuto-m this PR needs to update the en.json file under assets/base/i18n for the changes in the string to really apply.

As for the string in itself I leave it for PM to approve or reject

2020-12-21 16:04 UTC, mattermod commented
Building app in separate branch.

2020-12-21 16:13 UTC, mattermod commented
Successfully building:  
https://circleci.com/gh/mattermost/mattermost-mobile/12839  
https://circleci.com/gh/mattermost/mattermost-mobile/12837

2020-12-21 16:23 UTC, mattermod commented
Artifact links:  
https://12839-70265724-gh.circle-artifacts.com/0/tmp/artifacts/Mattermost_Beta.apk  
https://12837-70265724-gh.circle-artifacts.com/0/tmp/artifacts/Mattermost_Beta.ipa

2020-12-22 04:52 UTC, nobuto-m reviewed
Pushed as ea895578e8f94fd219a2ca0b93f1d6648ddc029c

2020-12-22 04:54 UTC, nobuto-m commented
Wondered if `\n\n` is better to be added between two sentences?

2020-12-22 08:05 UTC, enahum commented
I guess, give it a try

2020-12-22 12:36 UTC, enahum commented
@nobuto-m Can you share an updated screenshot?

2021-01-02 01:00 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

/cc @jasonblais @jfrerich @emilyacook

2021-01-04 18:15 UTC, jfrerich commented
Thanks for your PR, @nobuto-m!  Do you have any updates?

2021-01-05 00:06 UTC, nobuto-m commented
I've been struggling to build and run the app. Would somebody be able to add `Build Apps for PR` label so I can grab the binary from the CI?

2021-01-05 01:18 UTC, enahum commented
The binary will only work for Android as iOS uses an ad-hoc cert

2021-01-05 01:18 UTC, mattermod commented
Building app in separate branch.

2021-01-05 01:25 UTC, mattermod commented
Successfully building:  
https://circleci.com/gh/mattermost/mattermost-mobile/12957  
https://circleci.com/gh/mattermost/mattermost-mobile/12956

2021-01-05 01:38 UTC, mattermod commented
Artifact links:  
https://12957-70265724-gh.circle-artifacts.com/0/tmp/artifacts/Mattermost_Beta.apk  
https://12956-70265724-gh.circle-artifacts.com/0/tmp/artifacts/Mattermost_Beta.ipa

2021-01-05 12:41 UTC, nobuto-m commented
Okay, another screenshot for review is ready with a real Android phone.
![Screenshot_20210105-191223](https://user-images.githubusercontent.com/4356209/103647365-89304080-4f9e-11eb-9303-779faaba1165.png)

2021-01-05 17:05 UTC, josephbaylon approved these changes
LGTM. New message and format are displayed on archive alert.

Tested on both iPhone X (14.3) and Pixel 3 XL (11) devices.

See snapshots below,
|iOS|Android|
|:---|:---|
|![A8FDBD4A-94AF-4979-88E7-C2D74C22F22E](https://user-images.githubusercontent.com/487991/103674725-efcc4480-4f33-11eb-921b-3c5a3ab3f0e7.jpg)|![image-495ba866-81c4-405d-ac34-f136a163c96e](https://user-images.githubusercontent.com/487991/103675678-13dc5580-4f35-11eb-84f8-53913b12287e.jpg)|

2021-01-11 23:08 UTC, esethna approved these changes

2021-01-11 23:10 UTC, esethna requested changes
@nobuto-m technically the wording used here is inaccurate. If system admins have enabled the setting for searching archived channels, then users can still access the contents, see web message: https://docs.mattermost.com/administration/config-settings.html?highlight=archived%20channels#allow-users-to-view-archived-channels-beta

![image](https://user-images.githubusercontent.com/14333569/104248839-210ab000-541f-11eb-9c42-ba4c2ce9659a.png)

2021-01-12 00:30 UTC, nobuto-m commented
> @nobuto-m technically the wording used here is inaccurate. If system admins have enabled the setting for searching archived channels, then users can still access the contents, see web message: https://docs.mattermost.com/administration/config-settings.html?highlight=archived%20channels#allow-users-to-view-archived-channels-beta

I knew the admin knob, but I wasn't aware that the web version actually changed the message based on the flag. Sounds like the equivalent feature (changing the message catalog based on the flag) is required in the mobile version?

2021-01-12 20:33 UTC, esethna commented
@nobuto-m yes I believe so!

2021-01-16 13:24 UTC, enahum commented
Please re-add me as a reviewer once PM has approved.

2021-01-28 01:00 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

/cc @jasonblais @jfrerich @emilyacook

2021-02-03 22:31 UTC, emilyacook commented
> @nobuto-m yes I believe so!

Hi @nobuto-m! Let me know if there are any updates! :)

2021-02-04 00:43 UTC, nobuto-m commented
I'm closing this PR because
1. The scope of work is bigger than what is initially anticipated
2. And to let others work on it unless I get spare cycles

Thanks,

2021-02-04 00:43 UTC, closed without merging

2021-02-11 18:26 UTC, emilyacook commented
@nobuto-m Thank you! Really appreciate the time you spent on this 🙂