Revert "[MM-29225] Define LSApplicationQueriesSchemes so Linking.canO…
mattermost/mattermost-mobile pull request #5067
Opened 2020-12-23 16:36 UTC by migbot

#### Summary
Reverting back to using `openUrl` over `canOpenUrl` as `canOpenUrl` is meant to be used in conjuction with `LSApplicationQueriesSchemes` when wanting to limit what schemes to use in our app. In our case, we don't want a limitation so we should attempt to open all link and catch the failure case.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-29225

#### Device Information
This PR was tested on:
* iPhone SE, iOS 14.2

2020-12-23 16:45 UTC, enahum requested changes
Two things:
1. Can we create a utility function to avoid this many code duplication?
2. What was the other PR that made use of canOpenURL? The one from @larkox ?

And yes I would say it would be good to run some QA tests unless you want to add some automation tests for this (perhaps automation is a better idea)

2020-12-23 16:57 UTC, enahum commented
Not sure if this alone requires a dot release, we could look into the ipad issue as well and then we may consider a second dot release

2020-12-23 17:37 UTC, enahum commented
Sure ok, please create the ticket

2020-12-23 17:38 UTC, enahum approved these changes

2021-01-05 18:17 UTC, enahum commented on app/components/post_attachment_opengraph/post_attachment_opengraph.js
> +        tryOpenURL(this.props.link);
no error here?

2021-01-05 18:17 UTC, enahum commented on app/components/post_body_additional_content/post_body_additional_content.js
> +                tryOpenURL(videoLink);
no error here?

2021-01-05 18:19 UTC, enahum approved these changes

2021-01-05 18:26 UTC, enahum commented on app/components/post_attachment_opengraph/post_attachment_opengraph.js
> +        tryOpenURL(this.props.link);
Yeah, generic one is fine

2021-01-05 18:44 UTC, enahum requested changes

2021-01-05 18:44 UTC, enahum commented on app/components/markdown/markdown_link/markdown_link.js
> +                );
```suggestion
                Alert.alert(
                    formatMessage({
                        id: 'mobile.link.error.title',
                        defaultMessage: 'Error',
                    }),
                    formatMessage({
                        id: 'mobile.link.error.text',
                        defaultMessage: 'Unable to open the link.',
                    }),
                );
```

2021-01-05 19:05 UTC, enahum approved these changes

2021-01-05 22:03 UTC, mattermod commented
Building app in separate branch.

2021-01-05 22:12 UTC, mattermod commented
Successfully building:  
https://circleci.com/gh/mattermost/mattermost-mobile/12989  
https://circleci.com/gh/mattermost/mattermost-mobile/12987

2021-01-05 22:24 UTC, mattermod commented
Artifact links:  
https://12989-70265724-gh.circle-artifacts.com/0/tmp/artifacts/Mattermost_Beta.apk  
https://12987-70265724-gh.circle-artifacts.com/0/tmp/artifacts/Mattermost_Beta.ipa

2021-01-06 13:28 UTC, enahum commented
@josephbaylon can you please give this one a review ? Thanks

2021-01-06 16:07 UTC, josephbaylon approved these changes
LGTM. In iOS, invalid links display the alert on either default safari/chrome. And valid links open in the correct browser on either default safari/chrome. In Android, smoke tested valid and invalid links.

Tested on iPhone X (14.3) and Pixel 3 XL (11) devices.

2021-01-06 16:11 UTC, merged

2021-01-06 16:11 UTC, mattermod commented
Cherry pick is scheduled.