Add refresh websocket event to refetch bindings
mattermost/mattermost-mobile pull request #5194
Opened 2021-02-26 18:28 UTC by larkox

#### Summary
Add refresh bindings websocket event.

This naïve approach is the first iteration on handling changes in the bindings on server side. When the event is sent, we fetch one more time the bindings. Eventually we will look into better ways to handle this, maybe sending information through the websocket event.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-33129

#### Related PR
Proxy: Coming Soon
Webapp: Coming Soon

2021-02-27 01:02 UTC, enahum requested changes

2021-02-27 01:02 UTC, enahum commented on app/actions/websocket/index.ts
> +        case 'custom_com.mattermost.apps_refresh_bindings': {
Create a constant?

2021-02-27 01:02 UTC, enahum commented on app/actions/websocket/index.ts
> +                dispatch(fetchAppBindings(getCurrentUserId(state), getCurrentChannelId(state)));
Perhaps a handler like the other events so the state is isolated? Easier for the migration later on

2021-03-04 01:24 UTC, catalintomai approved these changes

2021-03-04 10:26 UTC, merged