MM-33495 Sanitize filename in Android ShareExtension
mattermost/mattermost-mobile pull request #5210
Opened 2021-03-05 18:46 UTC by enahum

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-33495

2021-03-05 19:46 UTC, enahum commented on android/app/src/main/java/com/mattermost/share/RealPathUtil.java
> +        if (uri == null || uri.isRelative()) {
It will not, also the sanitize function will only return the filename regardless of the scheme

2021-03-07 10:13 UTC, shazm approved these changes

2021-03-08 07:43 UTC, jupenur commented on android/app/src/main/java/com/mattermost/share/RealPathUtil.java
>                  fileName = uri.getLastPathSegment().toString().trim();
The Javadoc for [getLastPathSegment](https://developer.android.com/reference/android/net/Uri#getLastPathSegment()) says it decodes the thing it returns -- does that mean `%2F` becomes `/`? If so, we need to call `sanitizeFilename` again here.

2021-03-08 07:50 UTC, jupenur requested changes

2021-03-08 07:50 UTC, jupenur commented on android/app/src/main/java/com/mattermost/share/RealPathUtil.java
>                  fileName = uri.getLastPathSegment().toString().trim();
Answering my own question after a quick test: yes, path separators get decoded so this needs to be sanitized.

2021-03-08 11:56 UTC, jupenur approved these changes

2021-03-08 15:44 UTC, mattermod commented
Building app in separate branch.

2021-03-08 15:49 UTC, mattermod commented
Successfully building:  
https://circleci.com/gh/mattermost/mattermost-mobile/14295  
https://circleci.com/gh/mattermost/mattermost-mobile/14294

2021-03-08 16:03 UTC, mattermod commented
Artifact links:  
https://14295-70265724-gh.circle-artifacts.com/0/tmp/artifacts/Mattermost_Beta.apk  
https://14294-70265724-gh.circle-artifacts.com/0/tmp/artifacts/Mattermost_Beta.ipa

2021-03-08 16:17 UTC, josephbaylon commented
Hi @jupenur I'm not sure how to properly test this PR. I only did some smoke tests around share extension and looks good on Android. Would you be able to test this PR properly? I triggered an app build and you should be able to down the APK from the `QA: Builds` channel

2021-03-08 16:21 UTC, enahum commented
@jupenur would you know why the deps-check job is failing ?

2021-03-08 16:22 UTC, jupenur commented
> Would you be able to test this PR properly?

@josephbaylon sure thing, on it now

> @jupenur would you know why the deps-check job is failing ?

@enahum see https://community.mattermost.com/core/pl/kdee1bucofdeidkgamcq5br1ka

2021-03-08 16:22 UTC, enahum commented
> Hi @jupenur I'm not sure how to properly test this PR. I only did some smoke tests around share extension and looks good on Android. Would you be able to test this PR properly? I triggered an app build and you should be able to down the APK from the QA: Builds channel

important note: the APK there uses the packageId `com.mattermost.rnbeta`  which may be different than the one in the POC

2021-03-08 17:06 UTC, jupenur commented
@josephbaylon tested with an appropriate "companion app", looks all good to me.

2021-03-08 17:09 UTC, josephbaylon approved these changes
LGTM. Per https://github.com/mattermost/mattermost-mobile/pull/5210#issuecomment-792906661, PR fixes security issue on Android share extension

2021-03-08 17:27 UTC, enahum commented
/update-branch

2021-03-08 17:38 UTC, merged

2021-03-08 17:38 UTC, mattermod commented
Cherry pick is scheduled.