[MM-33742] Update RequiredServer
mattermost/mattermost-mobile pull request #5242
Opened 2021-03-25 16:51 UTC by migbot

#### Summary
Update RequiredServer to ESR version 5.31.0

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-33742

2021-03-25 17:04 UTC, enahum requested changes
you need to update the README and also 
* https://github.com/mattermost/mattermost-mobile/blob/master/fastlane/metadata/changelog 
* https://github.com/mattermost/mattermost-mobile/blob/master/fastlane/metadata/android/en-US/full_description.txt

2021-03-25 17:16 UTC, enahum approved these changes

2021-03-25 17:49 UTC, josephbaylon approved these changes
LGTM. Changes look straightforward and the same as https://github.com/mattermost/mattermost-mobile/pull/4830

2021-03-26 21:46 UTC, merged

2021-03-26 21:46 UTC, mattermod commented
Cherry pick is scheduled.