Get all existing server credentials on init
mattermost/mattermost-mobile pull request #5468
Opened 2021-06-18 21:49 UTC by migbot

#### Summary
Gets all existing server credentials on init for use with initializing the DatabaseManager and the NetworkClientManager. The keychain library on the iOS side needed patching to support extracting all server URLs from internet credential entries.

```release-note
NONE
```

2021-06-18 21:57 UTC, enahum commented on app/init/credentials.ts
> +    for (const serverUrl of serverUrls) {
```suggestion
    for await (const serverUrl of serverUrls) {
```

2021-06-18 22:03 UTC, enahum approved these changes
just not sure why Podfile.lock updated

2021-06-18 22:03 UTC, enahum commented on ios/Podfile.lock
> +  - libwebp (1.2.0):
why is this changing?

2021-06-18 22:03 UTC, enahum commented on patches/react-native-keychain+7.0.0.patch
> ++++ b/node_modules/react-native-keychain/RNKeychainManager/RNKeychainManager.m
do we want to submit this patch upstream?

2021-06-18 22:51 UTC, enahum approved these changes

2021-06-21 08:08 UTC, avinashlng1080 commented on app/init/credentials.ts
>  import AsyncStorage from '@react-native-community/async-storage';
When sorting imports, the `@react-native-community/async-storage` should be treated as the character `a` and sorted amongst the first modules.

2021-06-21 08:10 UTC, avinashlng1080 approved these changes
LGTM

2021-06-21 13:39 UTC, enahum requested changes

2021-06-21 13:39 UTC, enahum commented on app/init/credentials.ts
> +    const normalizedServerUrl = normalizeServerUrl(serverUrl);
I'm having my doubts about normalizing.. let's chat about this

2021-06-21 15:09 UTC, enahum approved these changes

2021-06-21 18:20 UTC, avinashlng1080 approved these changes

2021-06-21 21:08 UTC, merged