Fixed MM-36591 issue
mattermost/mattermost-mobile pull request #5496
Opened 2021-06-28 09:18 UTC by manojmalik20

#### Summary

- Fixed MM-36591 RN: Custom Statuses: Add custom status to mention autocomplete
- Changed the default behavior of autocomplete item UI in case of long display names. Long display names will be truncated to show the username.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-36591

#### Checklist

- [ ] Added or updated unit tests (required for all new features)
- [x] Has UI changes
- [ ] Includes text changes and localization file updates

#### Device Information
This PR was tested on: 

- iPhone 12 Simulator - iOS 14.4
- Android Emulator - Pixel_3a_API_30_x86 - Android 10

#### Screenshots

![image](https://user-images.githubusercontent.com/77336594/123611536-55ccc100-d81f-11eb-8ce4-ecd8e6d6c656.png)

![image](https://user-images.githubusercontent.com/77336594/123611599-63824680-d81f-11eb-891b-0c19344411e9.png)

![image](https://user-images.githubusercontent.com/77336594/123611638-6da44500-d81f-11eb-8be4-25ab27080253.png)

#### Release Note

```release-note
- Fixed MM-36591 RN: Custom Statuses: Add custom status to mention autocomplete
- Changed the default behavior of autocomplete item UI in case of long display names. Long display names will be truncated to show the username.
```

2021-06-28 09:18 UTC, mattermod commented
Hello @manojmalik20,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2021-06-28 14:54 UTC, mattermod commented
Building app in separate branch.

2021-06-29 14:00 UTC, matthewbirtch commented
Thanks @manojmalik20. It's looking great. The only thing I noticed is that we are using the ellipses differently here than we are in the production app. Is there a reason for that? I would prefer the ellipses be used at the end always rather than in the middle.
<table>
<tr>
<td>
<p><strong>Production App</strong></p>
<img src="https://user-images.githubusercontent.com/2040554/123810718-a2b4a400-d8c0-11eb-9d16-cd1315a83160.PNG" width="400">
</td>
<td>
<p><strong>This PR</strong></p>
<img src="https://user-images.githubusercontent.com/2040554/123810762-a9dbb200-d8c0-11eb-8c64-ddc772a87ad9.PNG" width="400">
</td>
</tr>
</table>

2021-06-29 14:48 UTC, manojmalik20 commented
@matthewbirtch Actually in the production app, if there is a really long name then the username isn't visible at all. So I've changed that behavior. If a user has a really long name, it will be truncated with ellipses to show the username also.

2021-06-29 14:54 UTC, matthewbirtch commented
> @matthewbirtch Actually in the production app, if there is a really long name then the username isn't visible at all. So I've changed that behavior. If a user has a really long name, it will be truncated with ellipses to show the username also.

Right, I understand that. However, this approach favours the username over the display name. I would expect it to favour the display name. It's also strange to have an ellipses in the middle.

I don't think this change was expected as part of this ticket, so would you be able to revert that change?

2021-06-29 15:56 UTC, manojmalik20 commented
@matthewbirtch I've reverted that change.

2021-06-29 15:56 UTC, mattermod commented
Building app in separate branch.

2021-06-30 14:54 UTC, matthewbirtch commented
@manojmalik20 now I'm not seeing the elipses at all. The text now just gets cut off (screenshot below)

<img src="https://user-images.githubusercontent.com/2040554/123983012-86cd0300-d991-11eb-9266-891215ee8938.PNG" width="414">

2021-07-02 10:16 UTC, manojmalik20 commented
@matthewbirtch I'm not able to reproduce this on either Android or IOS. 

![Simulator Screen Shot - iPhone 12 - 2021-07-02 at 05 11 10](https://user-images.githubusercontent.com/77336594/124259782-84fb6f00-db4c-11eb-9156-8b96cbcc27c2.png)

Can you tell me the version you are using for both ios and android?

2021-07-06 13:20 UTC, matthewbirtch commented
> Can you tell me the version you are using for both ios and android?

@manojmalik20 I have iOS 14.6 on my iPhone. 

The screenshot you showed above truncates the display name and then cuts off the username (you can actually see it getting cut off on your screenshot). The truncation should be at the end of both elements no matter what. If the display name is longer than what is visible, then we should see the ellipses at the end of the display name and we wouldn't see the username at all. If the display name is short, but the username is longer than what's visible, the ellipses would show at the end of the username

2021-07-07 11:01 UTC, manojmalik20 commented
@matthewbirtch I've fixed the username cutting off issue.


![Simulator Screen Shot - iPhone 12 - 2021-07-07 at 05 59 25](https://user-images.githubusercontent.com/77336594/124748449-c58a2c80-df40-11eb-927a-80a572090c39.png)

2021-07-07 14:29 UTC, mattermod commented
Building app in separate branch.

2021-07-07 14:58 UTC, mattermod commented
Failed retrieving build links. @mattermost/core-build-engineers have been notified. Error:  
```504: unable to parse API response: invalid character '<' looking for beginning of value```

2021-07-07 16:57 UTC, matthewbirtch commented
@manojmalik20 the build failed. The screenshots look good though

2021-07-08 10:20 UTC, manojmalik20 commented
@matthewbirtch Can you please re-trigger the build and add more reviewers?

2021-07-08 13:12 UTC, mattermod commented
Building app in separate branch.

2021-07-08 13:42 UTC, manojmalik20 commented
@matthewbirtch The build is failing at the Checkout code step. Do you know what might be the reason for that?

2021-07-08 13:49 UTC, matthewbirtch commented
> @matthewbirtch The build is failing at the Checkout code step. Do you know what might be the reason for that?

I'm afraid I'm not well versed in the build processes. @enahum can you help out?

2021-07-08 13:52 UTC, enahum commented
The CI was having an outage yesterday, let's try again

2021-07-08 13:52 UTC, mattermod commented
Building app in separate branch.

2021-07-08 14:41 UTC, manojmalik20 commented
@enahum The build failed again in the `Getting Javascript Dependencies` step due to socket timeout. Maybe try again?

2021-07-08 18:16 UTC, enahum commented
Build is ready

2021-07-08 19:07 UTC, matthewbirtch approved these changes
I think we're good @manojmalik20

2021-07-08 19:08 UTC, matthewbirtch commented
@esethna can you help assign appropriate engineering reviewers?

2021-07-08 20:47 UTC, enahum approved these changes

2021-07-09 05:39 UTC, anurag6713 requested changes

2021-07-09 05:39 UTC, anurag6713 commented on app/components/autocomplete/at_mention_item/at_mention_item.tsx
> +                        style={{marginLeft: 4}}
1. Can we move this out from inline?
2. Add the same style to Shared channel's `ChannelIcon` component?

2021-07-09 05:39 UTC, anurag6713 commented on app/components/autocomplete/at_mention_item/at_mention_item.tsx
> -            flex: 1,
Can you make the shared channel Icon visible in code and fix this?  
<img width="378" alt="Screenshot 2021-07-09 at 11 07 55" src="https://user-images.githubusercontent.com/3680799/125028599-f3d54c80-e0a5-11eb-89fd-d507aebcc16d.png">

2021-07-09 15:19 UTC, manojmalik20 commented
@anurag6713 This is ready for re-review.

2021-07-09 15:36 UTC, anurag6713 approved these changes

2021-07-09 15:36 UTC, anurag6713 commented
@manojmalik20 LGTM! Thank you 🙂

2021-07-09 15:41 UTC, mattermod commented
Building app in separate branch.

2021-07-09 20:09 UTC, jgilliam17 approved these changes
Thank you @manojmalik20 
Tested, looks good to merge.
- Verified custom status displays on mention autocomplete, and also long display names are truncated properly on the right.

2021-07-09 20:27 UTC, merged