Fix mm emoji
mattermost/mattermost-mobile pull request #5526
Opened 2021-07-08 21:35 UTC by Willyfrog

#### Summary

Add mattermost emoji as an asset.

#### Ticket Link

[MM-36900](https://mattermost.atlassian.net/browse/MM-36900)

#### Device Information
This PR was tested on: ios simulator

#### Screenshots

<img width="373" alt="Screenshot 2021-07-08 at 23 34 51" src="https://user-images.githubusercontent.com/1515906/124993766-18e5a300-e045-11eb-9a98-3665591e1993.png">

#### Release Note

```release-note
NONE
```

2021-07-08 22:17 UTC, enahum requested changes

2021-07-08 22:17 UTC, enahum commented on app/components/emoji/emoji.tsx
> +const assetImages = new Map([['mattermost.png', require('@assets/images/mattermost.png')]]);
can we add the asset under an emojis folder?

2021-07-08 23:26 UTC, enahum approved these changes

2021-07-09 14:43 UTC, mattermod commented
Building app in separate branch.

2021-07-09 14:52 UTC, hmhealey approved these changes

2021-07-09 15:55 UTC, josephbaylon approved these changes
LGTM. Mattermost emoji now displays properly.

2021-07-09 16:32 UTC, merged

2021-07-09 16:32 UTC, mattermod commented
Cherry pick is scheduled.