Fix keep mention for channel A when opening a push notification on channel B
mattermost/mattermost-mobile pull request #5597
Opened 2021-08-05 03:18 UTC by enahum

#### Summary
When the app was sitting in the background and a user tapped on a push notification (which brings the app to the foreground) there were three issues:
1. A race condition that did not cancel the previous setTimeout
2. Two sources from where we called the function to clear the channel notifications
3. The channel id from which we needed to cancel the notifications was not being updated properly thus it used the last one set (first current channel Id)

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-37660

#### Release Note
```release-note
Fixed a race condition when bringing the app to the foreground by tapping in a notification that belongs to a channel other than the current channel that cause the current channel to missed any mentions if it had any.
```

Additional note: We need to bring this fix to the Gekidou branch.

2021-08-05 07:48 UTC, mattermod commented
Building app in separate branch.

2021-08-05 14:11 UTC, josephbaylon commented
@enahum The build for Android is stuck running. Do we just kill that process and issue another build app trigger?

2021-08-05 14:12 UTC, enahum commented
@josephbaylon looking into it

2021-08-05 14:14 UTC, enahum commented
@josephbaylon ready

2021-08-05 14:39 UTC, josephbaylon commented
@enahum I'm still getting the same issue as before. Is it working on your end?

2021-08-05 15:06 UTC, enahum commented
@josephbaylon yes it did,.. re-tested 5 times in a row

2021-08-05 15:10 UTC, josephbaylon commented
@enahum Can you also rebuild the apk locally and attach the apk here? Maybe it's the QA build issue.

2021-08-05 22:58 UTC, enahum commented
@josephbaylon I've covered all cases
1. app in kill state
2. app in the foreground
3. app in the background
4. app in suspended state (back button pressed twice)

I've also tested opening the app from the app Icon and not the notification, it should clear them accordingly if there are any notifications for the current channel

Give it a try and let me know

2021-08-05 23:03 UTC, mattermod commented
Building app in separate branch.

2021-08-06 00:17 UTC, josephbaylon requested changes
Just so info is not lost, I'm reiterating the DM discussion here. Foreground, background, and suspended produce the appropriate badges in different scenarios. However for killed case, the following A and B scenarios fail, while scenario C passes.

_A. User 1 tapping on Channel B mention_
Steps,
1. User 1 is on Channel A, then kills the app
2. User 2 mentions User 1 on Channel A, then mentions User 1 on Channel B
3. User 1 taps on Channel B mention

Expected: App opens Channel B, should have a badge on menu, and badge for unread Channel A when main sidebar is expanded
Actual: App opens Channel B, no badge on menu, and no badge on Channel A (not unread) when sidebar is expanded

_B. User 1 tapping on Channel A mention_
Steps,
1. User 1 is on Channel A, then kills the app
2. User 2 mentions User 1 on Channel A, then mentions User 1 on Channel B
3. User 1 taps on Channel A mention

Expected: App opens Channel A, should have a badge on menu, and badge for unread Channel B when main sidebar is expanded
Actual: App opens Channel A, no badge on menu, and no badge on Channel B (not unread) when sidebar is expanded

_C. User 1 opening app from icon_ (**THIS WORKS**)
1. User 1 is on Channel A, then kills the app
2. User 2 mentions User 1 on Channel A, then mentions User 1 on Channel B
3. User 1 opens app from icon

Expected and Actual: App opens Channel A, should have a badge on menu, and badge for unread Channel B when main sidebar is expanded

2021-08-06 01:11 UTC, mattermod commented
Building app in separate branch.

2021-08-06 01:47 UTC, josephbaylon approved these changes
LGTM. Verified various scenarios for all the cases mentioned are producing appropriate badges.

2021-08-06 02:56 UTC, merged

2021-08-06 02:56 UTC, mattermod commented
Cherry pick is scheduled.