MM-37666 Properly dismiss edit profile screen
mattermost/mattermost-mobile pull request #5599
Opened 2021-08-05 14:00 UTC by enahum

#### Summary
Properly dismiss Edit profile screen by passing the componentId of the screen being dismissed

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-37666

#### Release Note
```release-note
NONE
```

Dev review not needed

2021-08-05 14:12 UTC, mattermod commented
Building app in separate branch.

2021-08-05 15:02 UTC, josephbaylon requested changes
@enahum On fresh install, when I edit profile and remove existing photo, I get an error saying `Invalid or missing password in request body` (see image)
![rn_image_picker_lib_temp_97f4505b-fb45-4a85-bd3f-55bf979a5472](https://user-images.githubusercontent.com/487991/128372657-243bdb96-8ba8-49b2-bccb-90a953d49006.png)

When I dismiss the modal by clicking X and re-opening the Edit Profile, the removal of the picture seem to have occurred.

Then I go on to upload a new photo, then the endless spinner still occurs. See image
![rn_image_picker_lib_temp_776c7e1a-f917-4e4d-bb94-e25c9d2eeca2](https://user-images.githubusercontent.com/487991/128372941-a030f0f7-3f24-46c9-984b-ce8a693ceaf2.png)

2021-08-05 15:07 UTC, enahum commented
WHAT!!

the error message is being returned by the server, so no idea why would that be.. and the endless spinner should have been fixed. Let me build it locally and I'll share the apk directly..

2021-08-05 21:41 UTC, mattermod commented
Building app in separate branch.

2021-08-05 22:58 UTC, josephbaylon approved these changes
LGTM. Updating profile pic from account settings does not end in endless spinner anymore and dismisses Edit Profile modal.

2021-08-06 12:57 UTC, merged

2021-08-06 12:57 UTC, mattermod commented
Cherry pick is scheduled.