MM-37485 MM-37602 37610 37684 37719 37522  App crash, Sync issue fixes
mattermost/mattermost-mobile pull request #5612
Opened 2021-08-09 11:02 UTC by anurag6713

#### Summary
* Fixes app crash on opening channel header
* Fixes app crash on opening permalink from permalink screen
* Fixes showing duplicates channels while searching in "Jump to..."
* Fixes auto following the thread on opening the thread view when there are unreads
* Fixes updation of threads state (Read/Unread/Deleted) of already loaded threads
* Fixes counter showing as blank due to threads sync issue

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-37485
https://mattermost.atlassian.net/browse/MM-37602
https://mattermost.atlassian.net/browse/MM-37610
https://mattermost.atlassian.net/browse/MM-37684
https://mattermost.atlassian.net/browse/MM-37719
https://mattermost.atlassian.net/browse/MM-37522

#### Device Information
This PR was tested on: iOS 14.5

#### Release Note
```release-note
NONE
```

2021-08-09 11:08 UTC, mattermod commented
Building app in separate branch.

2021-08-09 16:05 UTC, mattermod commented
Building app in separate branch.

2021-08-09 22:55 UTC, jgilliam17 commented
Thanks @anurag6713 
Seeing few issues
1. MM-37610 Verified tapping on the highlighted permalink reply post no longer crashes the app.
There is still an issue where the post is highlighted on the main channel view, not on the thread. Let me know if you want this filed separately, since the crash is fixed and this feels out of scope of that particular ticket.
**permalink view** 

![IMG_9662](https://user-images.githubusercontent.com/52937121/128783262-7501688f-473f-4f31-9214-e4c5ce263c76.PNG)
**main channel, after jump to recent** 

 ![IMG_9663](https://user-images.githubusercontent.com/52937121/128783280-04823f6e-6cab-465a-a428-8a07f78cc56d.jpg) 

2. MM-37719 Verified deleting doc and data no longer reduces number of items displayed on global thread. Seeing an issue where global threads item is not bolding on the channel sidebar after delete doc and data if unread threads are still present.

3. MM-37720 Verified long press menu the option to follow a thread is not available when CRT if off  on the threads view. Option to follow message is still available on the main channel view for root and reply posts.
![IMG_A5D4C8AC2D8B-1](https://user-images.githubusercontent.com/52937121/128784072-3c9564bc-c6d4-4699-b00c-75bbc23c7a9c.jpeg)

2021-08-10 01:56 UTC, anurag6713 commented
Thank you @jgilliam17.

Regarding the truth post getting highlighted, we have a ticket for it here https://mattermost.atlassian.net/browse/MM-37517

2021-08-10 03:10 UTC, jgilliam17 commented
Thanks @anurag6713 
I can reproduce 2. consistently - Threads item is not bolded on the channel sidebar after deleting documents and data until user taps on the Global Threads item again.

2021-08-10 16:35 UTC, enahum reviewed
so far looks good, nothing that stands out other than the issues found by QA that should be addressed

2021-08-10 19:25 UTC, esethna commented
@jgilliam17 can you confirm what issues are actual blockers and what can be addressed separately (in the next release)?

2021-08-10 19:25 UTC, esethna commented
cc// @anurag6713 @ashishbhate @enahum ^

2021-08-10 19:28 UTC, enahum commented
@esethna I have already reviewed https://github.com/mattermost/mattermost-mobile/pull/5612#pullrequestreview-726599476

2021-08-10 19:30 UTC, jgilliam17 commented
@esethna 3. is a blocker as it causes the app to crash
1. There is a follow up ticket https://mattermost.atlassian.net/browse/MM-37517
2. I discussed with Anurag, not a blocker. I'll create a ticket for it.

2021-08-10 19:38 UTC, esethna commented
@jgilliam17 can you clarify the behaviour that causes the crash for (3), sorry I might be missing something based on your review above

2021-08-10 19:42 UTC, jgilliam17 commented
Sure. Option to follow root post and replies is available on the main channel long press menu when CRT is off
steps:
1. toggle CRT off on daily
2. login on daily on the mobile app
3. view any channel
4. long press on any post (root or reply)
Observed: Follow Message option is available while CRT is off

2021-08-10 19:45 UTC, anurag6713 commented
https://mattermost.atlassian.net/browse/MM-37720

@jgilliam17 Can you test on the latest build? I have added that fix after the 1st build.

2021-08-10 19:48 UTC, anurag6713 commented
With CRT:
![Simulator Screen Shot - iPhone 12 - 2021-08-11 at 01 16 50](https://user-images.githubusercontent.com/3680799/128925244-4850bb80-473b-45f8-9fb1-e3e46c3838d0.png)

Without CRT:
![Simulator Screen Shot - iPhone 12 - 2021-08-11 at 01 16 27](https://user-images.githubusercontent.com/3680799/128925266-164000ca-9bc2-4bba-9479-abdf587b9c21.png)

2021-08-10 19:52 UTC, jgilliam17 commented
> Can you test on the latest build? I have added that fix after the 1st build.

Yes, give me a sec to find and install the latest app

2021-08-10 19:59 UTC, jgilliam17 commented
@esethna @anurag6713 Please disregard 3. It's no longer reproducing. Fixed.

2021-08-10 21:11 UTC, esethna commented
@enahum if all looks good can you please approve? 

@jgilliam17 thanks, does that mean this PR is QA approved given the followup items? 

@ashishbhate please help with a priority dev review :)

2021-08-10 21:22 UTC, enahum commented
@esethna I won't until QA approves and there are no new changes

2021-08-10 21:42 UTC, jgilliam17 approved these changes
Thanks @anurag6713 
Tested, looks good to merge. 
- MM-37485 - Verified app no longer crashes when opening channel header.
- MM-37602 Verified that channel sidebar unreads list remains the same before and after tapping on “jump to” link.
- MM-37610 Verified tapping on the highlighted permalink reply post no longer crashes the app. (MM-37517 follow-up, filed separately)
- MM-37684 - Verified thread that has been viewed, but not followed is no longer auto-followed after new replies come in.
- MM-37719 Verified deleting doc and data no longer reduces number of thread items on global threads (MM-37794 follow up ticket for unbolded Threads)
- MM-37522 Empty thread bubble no longer reproduces.
- MM-37720 Verified long press menu the option to follow a thread is not available when CRT if off 

Anurag - please ping me for re-review if any changes are requested.

2021-08-10 21:50 UTC, enahum approved these changes

2021-08-11 02:00 UTC, enahum requested changes

2021-08-11 02:00 UTC, enahum commented on app/screens/post_options/post_options.js
> +        if (location !== CHANNEL || !thread) {
This should also render null if CRT is disabled by the user.

2021-08-11 02:01 UTC, enahum commented
@esethna found a bug where CRT is disabled but the post options show `Follow Message` which is should not be present in the options menu.

2021-08-11 02:06 UTC, anurag6713 commented
@enahum we are checking in the index.ts and setting thread as null in case crt is not enabled. Agreed it's not clear and I will move the condition here for clarity.

2021-08-11 02:07 UTC, enahum commented
> @enahum we are checking in the index.ts and setting thread as null in case crt is not enabled. Agreed it's not clear and I will move the condition here for clarity.

@anurag6713 yes, so it later on.. so that is why I removed my comment and approved again

2021-08-11 10:25 UTC, ashishbhate approved these changes

2021-08-11 10:26 UTC, merged

2021-08-11 10:26 UTC, mattermod commented
Cherry pick is scheduled.