MM-37781: WIP
mattermost/mattermost-mobile pull request #5627
Opened 2021-08-13 20:32 UTC by mkraft

#### Summary

#### Ticket Link

#### Checklist

- [ ] Added or updated unit tests (required for all new features)
- [ ] Has UI changes
- [ ] Includes text changes and localization file updates

#### Device Information
This PR was tested on: 

#### Screenshots

#### Release Note

```release-note

```

2021-08-17 16:56 UTC, BenCookie95 requested changes
I commented on 2 places but I think this applies to a lot of the configs. Anywhere `hasNewPermissions` is called we don't need to call our new minimum server version because it already checks for 4.9.0 and has a return in that block

2021-08-17 16:56 UTC, BenCookie95 commented on app/mm-redux/utils/post_utils.ts
> +        if (!isMinimumServerVersion(serverVersion, 6, 0, 0)) {
I don't think we need this because `hasNewPermissions` already checks for a minimum server version of 4.9.0

2021-08-17 16:56 UTC, BenCookie95 commented on app/mm-redux/utils/post_utils.ts
> +        canEdit = isOwner && (config.AllowEditPost !== 'never' && !isMinimumServerVersion(serverVersion, 6));
I don't think we need this because hasNewPermissions already checks for a minimum server version of 4.9.0

2021-08-22 23:56 UTC, enahum requested changes
I'll push a commit with the iOS fixes plus addressing my feedback

2021-08-23 00:06 UTC, enahum approved these changes

2021-08-23 18:30 UTC, amyblais commented
@mkraft Since Ben is off, can another dev review this?

2021-08-23 19:01 UTC, mkraft commented on app/screens/post_options/index.js
> +                ((config.AllowEditPost === General.ALLOW_EDIT_POST_TIME_LIMIT && !isMinimumServerVersion(serverVersion, 6)) || (config.PostEditTimeLimit !== -1 && config.PostEditTimeLimit !== '-1'))
Yes, as part of the server PR [that config settings is being removed](https://github.com/mattermost/mattermost-server/pull/18035/files#diff-07146319e6e0a169b23444e4db03e086b60c72f16996920a8eabfb057841c8eeL338).

2021-09-01 13:38 UTC, mkraft commented on app/actions/helpers/channels.ts
> +    const gmAutoClosed = isAutoClosed(config, myPreferences, channel, channel.last_post_at, 0, serverVersion);
Added.

2021-09-01 14:07 UTC, BenCookie95 approved these changes

2021-09-01 22:36 UTC, furqanmlk commented
@mkraft 
Can you please help me define the QA steps ?

2021-09-02 16:12 UTC, mkraft commented
> @mkraft
> Can you please help me define the QA steps ?

I think if you create a build from this branch and point it to a server using the previous release it should 

> @mkraft
> Can you please help me define the QA steps ?

1. Create a build using this branch.
2. Connect to a previous server version.
3. Attempt to upload an attachment with `CloseUnusedDirectMessages` set to `true` and `false`.
4. Attempt to edit a post with `AllowEditPost` set to `true` and `false`.
5. Attempt to list archived channels with `ExperimentalViewArchivedChannels` set to `true` and `false`.
6. See the option to delete a public channel with `RestrictPrivateChannelDeletion` set to `true`/`false`.
7. Post to Town Square with `ExperimentalTownSquareIsReadOnly` set to `true`/`false`.
8. Test the auto-closing of DMs with `CloseUnusedDirectMessages` set to `true`/`false`.
9. Test `RestrictPublicChannelCreation` and `RestrictPrivateChannelCreation` configs.
10. Test `RestrictPublicChannelManagement` config.
11. 10. Test `RestrictPrivateChannelManagement` config.

@BenCookie95 Anything else to add?

2021-09-02 16:23 UTC, BenCookie95 commented
> > @mkraft
> > Can you please help me define the QA steps ?
> 
> I think if you create a build from this branch and point it to a server using the previous release it should
> 
> > @mkraft
> > Can you please help me define the QA steps ?
> 
> 1. Create a build using this branch.
> 2. Connect to a previous server version.
> 3. Attempt to upload an attachment with `CloseUnusedDirectMessages` set to `true` and `false`.
> 4. Attempt to edit a post with `AllowEditPost` set to `true` and `false`.
> 5. Attempt to list archived channels with `ExperimentalViewArchivedChannels` set to `true` and `false`.
> 6. See the option to delete a public channel with `RestrictPrivateChannelDeletion` set to `true`/`false`.
> 7. Post to Town Square with `ExperimentalTownSquareIsReadOnly` set to `true`/`false`.
> 8. Test the auto-closing of DMs with `CloseUnusedDirectMessages` set to `true`/`false`.
> 9. Test `RestrictPublicChannelCreation` and `RestrictPrivateChannelCreation` configs.
> 10. Test `RestrictPublicChannelManagement` config.
> 11. 1. Test `RestrictPrivateChannelManagement` config.
> 
> @BenCookie95 Anything else to add?

We should also test against my server PR branch and check there are no issues doing the above steps. The configs won't exist but we should test the ability to do the above activities.

2021-09-09 12:26 UTC, amyblais commented
@mkraft This PR has conflicts that need to be resolved.
@furqanmlk Kind reminder for PR review.

2021-09-15 12:11 UTC, amyblais commented
@furqanmlk Kind reminder for PR review - let's aim to merge this before the end of this week (code complete is this Friday).

2021-09-15 18:53 UTC, furqanmlk approved these changes
Related setting has been tested. working as expected.

2021-09-15 19:16 UTC, amyblais commented
@mkraft Please help merge.

2021-09-15 20:52 UTC, merged