Add color to loading spinners
mattermost/mattermost-mobile pull request #5872
Opened 2021-12-10 12:56 UTC by larkox

#### Summary
Add color to loading spinners. This is based on our discussions on the channel and my PR on browse channels.

This small PR will allow @avinashlng1080 to work with this changes, and reduce the size of the browse channels PR.

#### Ticket Link
None

#### Release Note
```release-note
None
```

2021-12-10 12:59 UTC, enahum approved these changes

2021-12-14 08:02 UTC, enahum commented
@avinashlng1080 please review asap

2021-12-14 08:04 UTC, avinashlng1080 commented on app/screens/channel/failed_teams/index.tsx
> +                    flex: 1,
Should this be in Stylesheet ?

2021-12-14 08:05 UTC, avinashlng1080 requested changes
LGTM, just one comment regarding the containerStyle.

2021-12-14 13:06 UTC, avinashlng1080 approved these changes
LGTM

2021-12-14 13:09 UTC, merged