[Gekidou MM-3972] Websocket Events - Reaction and emojis
mattermost/mattermost-mobile pull request #5920
Opened 2022-02-01 16:30 UTC by jfrerich

#### Summary
This PR handles the following teams websocket events:
* Reaction added event 
* Reaction removed event
* Emoji added event

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-41523

#### Checklist

- [ ] Added or updated unit tests (required for all new features)
- [ ] Has UI changes
- [ ] Includes text changes and localization file updates
- [ ] Have tested against the 5 core themes to ensure consistency between them.

#### Device Information
This PR was tested on: 

#### Screenshots

#### Release Note

```release-note

```

2022-02-02 21:51 UTC, enahum commented on app/database/operator/server_data_operator/handlers/user.ts
> +                deleteReactions.map((outCast) => outCast.prepareDestroyPermanently());
this should not be a map, this should be a `forEach`

2022-02-02 21:51 UTC, enahum commented on app/database/operator/server_data_operator/handlers/user.ts
> +                deleteReactions.map((outCast) => outCast.prepareDestroyPermanently());
```suggestion
                deleteReactions.forEach((outCast) => outCast.prepareDestroyPermanently());
```

2022-02-02 22:11 UTC, enahum commented on app/actions/websocket/index.ts
> +            handleAddCustomEmoji(serverUrl, msg);
do we have an `EMOJI_REMOVED` event?

2022-02-02 22:15 UTC, enahum requested changes
interesting to see, I'm almost sure we have a WS event for when a custom emoji is removed, perhaps it was never added to the mobile app, but we could do now!

2022-02-02 22:15 UTC, enahum commented on app/actions/websocket/reactions.ts
> +        if (operator) {
no need to check for this as it would return on line 12

2022-02-02 22:15 UTC, enahum commented on app/actions/websocket/reactions.ts
> +    }
const operator = DatabaseManager.serverDatabases[serverUrl]?.operator;
    if (!operator) {
        return;
    }

2022-02-02 22:15 UTC, enahum commented on app/actions/websocket/reactions.ts
> +        if (operator) {
no need for this after the suggestion I made

2022-02-02 22:15 UTC, enahum commented on app/actions/websocket/reactions.ts
> +            operator.handleCustomEmojis({
if you don't await the error won't be caught

2022-02-02 23:25 UTC, jfrerich commented
We do not have Websocket event from the server when a emoji is deleted. See [emoji.go](https://github.com/mattermost/mattermost-server/blob/master/app/emoji.go#L169)

I could add code the WS handler in this PR and and create the server PR also or add as a new ticket to get this merged sooner.

2022-02-02 23:26 UTC, enahum commented
Let's create a ticket for the missing custom emoji removal

2022-02-02 23:27 UTC, enahum commented
@jfrerich did you forget to push a commit ?

2022-02-02 23:30 UTC, jfrerich commented
@enahum, yes, I forgot to push. Sorry. It's there now.

2022-02-02 23:31 UTC, enahum requested changes

2022-02-02 23:31 UTC, enahum commented on app/actions/websocket/reactions.ts
> +    console.log('\n<><> 2. handleReactionAddedToPostEvent');
remove!
```suggestion
```

2022-02-02 23:31 UTC, enahum commented on app/actions/websocket/reactions.ts
> +    const database = DatabaseManager.serverDatabases[serverUrl].database;
```suggestion
    const database = DatabaseManager.serverDatabases[serverUrl]?.database;
```

2022-02-02 23:35 UTC, enahum approved these changes

2022-02-03 10:13 UTC, larkox approved these changes
LGTM!

2022-02-03 10:14 UTC, merged