Handle test notifications on iOS
mattermost/mattermost-mobile pull request #6002
Opened 2022-02-23 10:48 UTC by larkox

#### Summary
Handle test notifications in iOS.

#### Related PRs
Server: https://github.com/mattermost/mattermost-server/pull/19610
Push Proxy: Soon

#### Ticket Link
None

#### Release Note
```release-note
NONE
```

2022-02-23 10:53 UTC, enahum requested changes
let's return early

2022-02-23 10:53 UTC, enahum commented on ios/Mattermost/AppDelegate.m
> +  BOOL isTestAction = (action && [action isEqualToString: NOTIFICATION_TEST_ACTION]);
```suggestion
  BOOL isTestAction = (action && [action isEqualToString: NOTIFICATION_TEST_ACTION]);
  
if (isTestAction) {
    completionHandler(UIBackgroundFetchResultNoData);
    return;
}
```

2022-02-23 10:53 UTC, enahum commented on ios/Mattermost/AppDelegate.m
> +    completionHandler(UIBackgroundFetchResultNoData);
```suggestion
```

2022-02-23 10:56 UTC, enahum commented on ios/Mattermost/AppDelegate.m
> +if (isTestAction) {
hahahaha weird indentation

2022-02-23 10:56 UTC, enahum approved these changes

2022-03-01 14:12 UTC, larkox commented
@enahum Just to confirm, do we want to merge this already? (I don't see any reason to delay merging)

2022-03-01 14:14 UTC, enahum commented
I did already approved, 0/5 if you want to merge without another approval

2022-03-04 05:04 UTC, avinashlng1080 approved these changes

2022-03-04 09:10 UTC, merged