Add User Mention to autocomplete
mattermost/mattermost-mobile pull request #6005
Opened 2022-02-24 14:27 UTC by larkox

#### Summary
Add User (and group) mention to Autocomplete.

#### Ticket Link
Part of https://mattermost.atlassian.net/browse/MM-39682

#### Screenshots
![Screenshot from 2022-02-24 15-24-17](https://user-images.githubusercontent.com/1933730/155542779-d00ec36c-ddfb-4670-85ea-570e6ca47394.png)

#### Release Note
```release-note
NONE
```

2022-03-06 09:25 UTC, enahum commented
Needs conflict resolution

2022-03-08 17:04 UTC, larkox commented
@enahum conflicts resolved.

2022-03-11 19:14 UTC, enahum requested changes
it works for the most part.. on iOS it has a weird behavior, it never stops showing the autocomplete if you use the full name of the user and then continue typing without selecting from the autocomplete.

Also when you select the autocomplete after adding a space it concatenates some part of the username to the end of the input.

if in a message we go back a few lines and add the username with the autocomplete in the middle of message or anywhere really the autocomplete opens again after the user was selected.

Also for some reason every user is displayed with the bot tag

2022-03-14 19:58 UTC, enahum approved these changes

2022-03-14 20:05 UTC, merged