Adds DM/GM limit based on pref
mattermost/mattermost-mobile pull request #6074
Opened 2022-03-20 23:20 UTC by shazm

#### Summary

#### Ticket Link

#### Checklist

- [ ] Added or updated unit tests (required for all new features)
- [ ] Has UI changes
- [ ] Includes text changes and localization file updates
- [ ] Have tested against the 5 core themes to ensure consistency between them.

#### Device Information
This PR was tested on: 

#### Screenshots

#### Release Note

```release-note

```

2022-03-20 23:25 UTC, enahum commented
@shazm do we need to filter DM & GMs in other categories too? What about the last time there were msgs in the channel? I ask cause I still have a GM in my favs that is not visible on the webapp

2022-03-20 23:31 UTC, shazm commented
<img width="812" alt="Screen Shot 2022-03-21 at 10 27 12 am" src="https://user-images.githubusercontent.com/456511/159190603-fc564eee-1a33-430e-91ac-d87f57fdbf88.png">

Good question - that's the setting itself. I'm not sure if it implies that's the total number of direct messages to show across all categories, or just the number of channels to show in the Direct Messages category. 

As the description states; you can set it here as well:

<img width="533" alt="Screen Shot 2022-03-21 at 10 30 49 am" src="https://user-images.githubusercontent.com/456511/159190725-0465692b-8f3b-4ec0-b03d-899b2e39af0a.png">

Which to me implies that you only set that number for that category.

From what you describe, the behaviour is the former on the webapp - I might refer to @esethna / @matthewbirtch to make that call on what it should be.

2022-03-20 23:35 UTC, enahum commented
> 
> From what you describe, the behaviour is the former on the webapp - I might refer to @matthewbirtch to make that call on what it should be.

I don't think is the former as it currently is not displayed on the webapp on daily but it is with this PR.

I would encourage you to look at the current webapp and try and match every functionality

2022-03-20 23:43 UTC, shazm commented
> @shazm do we need to filter DM & GMs in other categories too? What about the last time there were msgs in the channel? I ask cause I still have a GM in my favs that is not visible on the webapp

> I don't think is the former as it currently is not displayed on the webapp on daily but it is with this PR.

Ah! I assumed you were trying to say that GMs/DMs should be limited across all categories (based on the user pref) - the behaviour you describe is probably a separate issue to this PR then; as the webapp is following the latter behaviour which I've implemented here (just limit the number of channels in the direct messages category).

2022-03-20 23:47 UTC, enahum requested changes
Based on the convo this is the only change, do we have tickets to look at the entire behavior regardless of the category to match the webapp?

2022-03-20 23:47 UTC, enahum commented on app/components/channel_list/categories/body/index.ts
> +                    (val) => of$(val[0].value),
This should be checking if val[0] exist if not return of$('')

Also I rather do the parseInt here and have the component receive an integer.

2022-03-20 23:51 UTC, shazm commented
> Based on the convo this is the only change, do we have tickets to look at the entire behavior regardless of the category to match the webapp?

Added: https://mattermost.atlassian.net/browse/MM-42641

2022-03-21 00:01 UTC, enahum approved these changes

2022-03-21 00:09 UTC, enahum requested changes

2022-03-21 00:09 UTC, enahum commented on app/components/channel_list/categories/body/category_body.tsx
> +        ids = sortedIds.slice(0, limit - 1);
Actually you should useMemo for `ids` as is always a new array

2022-03-21 09:03 UTC, larkox approved these changes
Apart of enahum concern, LGTM.

2022-03-21 14:41 UTC, matthewbirtch commented
> I'm not sure if it implies that's the total number of direct messages to show across all categories, or just the number of channels to show in the Direct Messages category.

Just chiming in here to confirm that it's the number to show in the Direct Messages category. Doesn't apply to the other categories

2022-03-21 20:33 UTC, enahum approved these changes

2022-03-21 20:51 UTC, merged