MM-41532 Gekidou Snack Bars
mattermost/mattermost-mobile pull request #6181
Opened 2022-04-20 10:35 UTC by avinashlng1080

#### Summary
With this PR, we have implemented the SnackBar component that appears whenever we have copied a link or a text from the post options.

In this ticket, we have two more snackbar for undoing the action for 'Mute Channel' and 'Unfollow Channel'.  Un/Follow post already has visual indicators so no snackbar was implemented for it.   I will implement the unmute channel in a separate ticket.  https://mattermost.atlassian.net/browse/MM-43584

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-41532

#### Release Note
```release-note
NONE
```

2022-04-20 13:47 UTC, avinashlng1080 commented on app/components/common_post_options/copy_permalink_option/copy_permalink_option.tsx
> +    location: typeof Screens[keyof typeof Screens];
rename `location` to `sourceScreen` = > wherever applicable

2022-04-20 14:06 UTC, enahum approved these changes

2022-04-20 14:43 UTC, mattermod commented
Building app in separate branch.

2022-04-20 14:48 UTC, mattermod commented
Successfully building:  
https://circleci.com/gh/mattermost/mattermost-mobile/21892  
https://circleci.com/gh/mattermost/mattermost-mobile/21891

2022-04-20 15:19 UTC, mattermod commented
Artifact links:  
https://output.circle-artifacts.com/output/job/b10e564d-d131-421f-82fe-c0b3331ad981/artifacts/0/tmp/artifacts/Mattermost_Beta.apk  
https://output.circle-artifacts.com/output/job/0b6126b1-9d87-4a18-ab91-80a453111385/artifacts/0/tmp/artifacts/Mattermost_Beta.ipa

2022-04-20 16:29 UTC, matthewbirtch requested changes
@avinashlng1080 thanks for this. A couple things:

1. Can we reduce the left & right margin on the component? In the design we had a margin of 8 on the left and right.
2. For the link copied toast, I don't think we need to make it green — it only needs to be green in the gallery view (for contrast purposes). Can we use the same background color as the copy text toast? Also, can we change the icon to the link icon? Below is an example of what I mean (this screenshot also shows the correct margin for the point above).

<img src="https://user-images.githubusercontent.com/2040554/164272994-fbf4faed-eb62-461a-ac1e-a961b59cc9a0.png" width="414">

4. Can we add a gesture to dismiss the toasts? Swiping down should dismiss them

5. For the copy text toast, can we adjust the message to "Text copied to clipboard"
6. Can we add an elevation to the toast so it adds a shadow? (in design we have it set to Elevation 2)
7. When navigating back from the thread view to channel view or from the channel view to the home screen, the toast 
stays on screen still. Can we remove it immediately when that interaction happens instead of waiting for it to automatically dismiss?

2022-04-20 20:11 UTC, enahum commented
@matthewbirtch

About 6: elevation is an Android thing, for iOS we'll need the shadow style values, are they also in figma?
About 7: the toast is an overlay that will be on top of all navigation screens, doing what you are asking is possible but my question is, should that apply at all times regardless of the screen that is being removed from the stack?

2022-04-20 20:15 UTC, matthewbirtch commented
> @matthewbirtch
> 
> About 6: elevation is an Android thing, for iOS we'll need the shadow style values, are they also in figma? About 7: the toast is an overlay that will be on top of all navigation screens, doing what you are asking is possible but my question is, should that apply at all times regardless of the screen that is being removed from the stack?

Sorry, I was referring to our own elevation styles in our design system. Elevation 2 in our system is:
<img width="220" alt="image" src="https://user-images.githubusercontent.com/2040554/164314935-69774e9d-ed4b-45a0-9112-5d93539d26fc.png">

I'm not exactly sure what this works out to, but Figma spits this out:

For iOS
```
Effect: Drop shadow
Radius: 6 pt
Offset: 0 pt, 4 pt
rgba 0.0, 0.0, 0.0, 0.12
```
and this for Android:
```
Effect: Drop shadow
Radius: 6dp
Offset: 0dp, 4dp
#1F000000
```

2022-04-21 09:41 UTC, avinashlng1080 commented
@matthewbirtch  Thanks for your input.  I'll be working of them.

2022-04-24 17:30 UTC, anurag6713 commented on assets/base/i18n/en.json
> -  "threads.newReplies": "{count} new {count, plural, one {reply} other {replies}}",
`threads.newReplies` & `threads.replies` - We are using both. Added both in the Global Threads Screen PR.

2022-05-02 13:18 UTC, mattermod commented
Building app in separate branch.

2022-05-02 13:22 UTC, mattermod commented
Successfully building:  
https://circleci.com/gh/mattermost/mattermost-mobile/22097  
https://circleci.com/gh/mattermost/mattermost-mobile/22096

2022-05-02 14:21 UTC, matthewbirtch requested changes
Thanks @avinashlng1080.

The toast now dismisses properly when I swipe down or navigate back, so nice work on that. 

1. I'm being picky here, but can we bump up the toast vertically by 4px? The margin between the input box and the bottom of the toast should match the margin on the left and right (which is now correct - thank you!).
2. I still don't see a shadow applied (testing on iOS). Are we skipping that?

Other than that, I think we're good.

2022-05-04 13:19 UTC, enahum commented
> Thanks @avinashlng1080.
> 
> The toast now dismisses properly when I swipe down or navigate back, so nice work on that.
> 
> 1. I'm being picky here, but can we bump up the toast vertically by 4px? The margin between the input box and the bottom of the toast should match the margin on the left and right (which is now correct - thank you!).
> 2. I still don't see a shadow applied (testing on iOS). Are we skipping that?
> 
> Other than that, I think we're good.

@matthewbirtch this PR has nothing to do with the Toasts shown in the gallery, but I wanted to ask if the Toast shown there (gallery) should also have a shadow, do let me know please

2022-05-04 13:21 UTC, matthewbirtch commented
> @matthewbirtch this PR has nothing to do with the Toasts shown in the gallery, but I wanted to ask if the Toast shown there (gallery) should also have a shadow, do let me know please

Yep, just make it consistent for component

2022-05-04 13:31 UTC, enahum commented
Alright, can we leave that off this PR and I'll make sure to include the shadow as I work on https://mattermost.atlassian.net/browse/MM-39764 ?

2022-05-05 11:11 UTC, avinashlng1080 commented
Thanks @matthewbirtch  and @enahum .

@matthewbirtch  I have bumped it vertically as requested.  Please let me know if this works for you.

2022-05-05 13:53 UTC, mattermod commented
Building app in separate branch.

2022-05-05 13:55 UTC, enahum approved these changes

2022-05-05 13:57 UTC, mattermod commented
Successfully building:  
https://circleci.com/gh/mattermost/mattermost-mobile/22270  
https://circleci.com/gh/mattermost/mattermost-mobile/22269

2022-05-05 14:00 UTC, merged