[Gekidou] Show login screen when selecting a previous server
mattermost/mattermost-mobile pull request #6190
Opened 2022-04-22 19:11 UTC by enahum

#### Summary
When selecting a server without an active session from the server list, take the user directly to the login screen and bypass the Add Server screen.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-43640

```release-note
NONE
```

2022-04-22 19:11 UTC, mattermod commented
Building app in separate branch.

2022-04-22 19:15 UTC, mattermod commented
Successfully building:  
https://circleci.com/gh/mattermost/mattermost-mobile/21946  
https://circleci.com/gh/mattermost/mattermost-mobile/21945

2022-04-22 19:44 UTC, mattermod commented
Artifact links:  
https://output.circle-artifacts.com/output/job/3c23895d-1a30-4276-b7e0-38f62f654ce9/artifacts/0/tmp/artifacts/Mattermost_Beta.apk  
https://output.circle-artifacts.com/output/job/0c12884a-d1a1-47ed-94a5-a468b8416411/artifacts/0/tmp/artifacts/Mattermost_Beta.ipa

2022-04-22 20:28 UTC, matthewbirtch approved these changes
Nice! This is a great improvement I think.

2022-04-25 09:26 UTC, larkox approved these changes

2022-04-25 17:10 UTC, jfrerich requested changes
I have one change request and then I'll approve!

2022-04-25 17:10 UTC, jfrerich commented on app/screens/home/channel_list/servers/servers_list/server_item/server_item.tsx
> +            alertServerError(intl, result.error as ClientErrorProps);
```suggestion
            alertServerError(intl, data.error as ClientErrorProps);
```

2022-04-25 17:11 UTC, jfrerich approved these changes
Fastest turnaround time ever!  Nice Job!

2022-04-25 17:26 UTC, merged