Moves collapse animation to FlatList, updates timings
mattermost/mattermost-mobile pull request #6220
Opened 2022-05-04 00:45 UTC by shazm

#### Summary
Removes the animations from the `ChannelItem` and pushes them on to the `FlatList` inside `CategoryBody` further up the tree.

It also updates the timings to `200` / `300` for the opacity easing in and out for a better experience.

#### Ticket Link

#### Checklist

- [ ] Added or updated unit tests (required for all new features)
- [X] Has UI changes
- [ ] Includes text changes and localization file updates
- [ ] Have tested against the 5 core themes to ensure consistency between them.

#### Device Information
This PR was tested on: 

#### Screenshots

#### Release Note

```release-note

```

2022-05-04 00:49 UTC, enahum approved these changes
Nice one!

2022-05-04 07:50 UTC, larkox approved these changes
LGTM, just one small change.

2022-05-04 07:50 UTC, larkox commented on app/screens/home/channel_list/categories_list/categories/body/category_body.tsx
>      }, [category.collapsed, onChannelSwitch]);
No need to depend on category.collapsed anymore apparently.

2022-05-04 13:28 UTC, mattermod commented
Building app in separate branch.

2022-05-04 13:32 UTC, mattermod commented
Successfully building:  
https://circleci.com/gh/mattermost/mattermost-mobile/22209  
https://circleci.com/gh/mattermost/mattermost-mobile/22208

2022-05-04 14:03 UTC, mattermod commented
Artifact links:  
https://output.circle-artifacts.com/output/job/83ff3c40-887b-455b-a11b-8fb2df05d8f2/artifacts/0/tmp/artifacts/Mattermost_Beta.ipa  
https://output.circle-artifacts.com/output/job/5c59f39c-3694-4ec5-9fa0-4b43e5a37730/artifacts/0/tmp/artifacts/Mattermost_Beta.apk

2022-05-04 16:29 UTC, mattermod commented
Building app in separate branch.

2022-05-04 16:34 UTC, mattermod commented
Successfully building:  
https://circleci.com/gh/mattermost/mattermost-mobile/22224  
https://circleci.com/gh/mattermost/mattermost-mobile/22223

2022-05-04 21:27 UTC, enahum commented
/update-branch

2022-05-04 21:53 UTC, enahum requested changes

2022-05-04 21:53 UTC, enahum commented on app/screens/home/channel_list/categories_list/categories/body/category_body.tsx
> +    const height = ids.length ? ids.length * 40 : 0;
@shazm there is an issue here where we are not taking into account channels that have been archived and are not the active channel as well as the ones that should not render as they are in the unread section, basically by not taken them into account there is additional space that should not be there.

2022-05-04 22:27 UTC, matthewbirtch approved these changes
Seems good to me now with your latest changes @enahum

2022-05-05 01:17 UTC, enahum approved these changes

2022-05-05 01:17 UTC, merged