Dismiss post options before executing action
mattermost/mattermost-mobile pull request #6227
Opened 2022-05-04 21:45 UTC by enahum

#### Summary
For some options, dismissing the post/thread options after executing certain actions that update the DB, the post options would not dismiss, this PR ensures that the post options dismisses before executing the action.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-43971

```release-note
NONE
```

2022-05-04 21:49 UTC, mattermod commented
Building app in separate branch.

2022-05-04 21:53 UTC, mattermod commented
Successfully building:  
https://circleci.com/gh/mattermost/mattermost-mobile/22243  
https://circleci.com/gh/mattermost/mattermost-mobile/22242

2022-05-04 22:25 UTC, mattermod commented
Artifact links:  
https://output.circle-artifacts.com/output/job/c5f18704-7d3e-4113-96e0-f0b6e6384374/artifacts/0/tmp/artifacts/Mattermost_Beta.apk  
https://output.circle-artifacts.com/output/job/2beea7dd-6b93-4f75-9147-b84abf06dbf4/artifacts/0/tmp/artifacts/Mattermost_Beta.ipa

2022-05-04 22:31 UTC, matthewbirtch requested changes
This seems to have caused new issues for me now. I'm not longer blocked when I 'Mark as unread', but it's moving messages around on me when I mark as unread. 

In the screen recording attached here, you'll notice that it moved the new message line at the very top and then reversed the order of the messages as well somehow.

https://user-images.githubusercontent.com/2040554/166835961-5a093bc6-e8fa-4f91-b02b-f6a36ba81b00.mov

2022-05-04 22:34 UTC, enahum commented
@matthewbirtch that seems to be an entirely different bug where the post list if flipping around?

I'll look into it though, that is really interesting as of why is happening

2022-05-05 07:17 UTC, avinashlng1080 approved these changes

2022-05-05 12:47 UTC, enahum commented
The issue found by @matthewbirtch where the post list flips is not really caused by this PR, so I'm going to merge this and submit a different PR to take care of the post list flipping.

2022-05-05 12:47 UTC, merged