[Gekidou] Team icon style
mattermost/mattermost-mobile pull request #6258
Opened 2022-05-10 18:14 UTC by enahum

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-44064

#### Checklist
- [x] Has UI changes

```release-note
NONE
```

2022-05-10 18:17 UTC, mattermod commented
Building app in separate branch.

2022-05-10 18:21 UTC, mattermod commented
Successfully building:  
https://circleci.com/gh/mattermost/mattermost-mobile/22469  
https://circleci.com/gh/mattermost/mattermost-mobile/22468

2022-05-10 19:08 UTC, mattermod commented
Artifact links:  
https://output.circle-artifacts.com/output/job/bf1e922b-b98c-4453-b783-47be1136a1d5/artifacts/0/tmp/artifacts/Mattermost_Beta.apk  
https://output.circle-artifacts.com/output/job/9e57df46-4f0c-4979-88b8-d57166f68ce3/artifacts/0/tmp/artifacts/Mattermost_Beta.ipa

2022-05-10 19:16 UTC, matthewbirtch requested changes
I forgot to mention in the ticket that the font used for the letters in the fallback icons should be Metropolis semibold instead of open sans. Can we update that? Other than that, we're good to go with this change

2022-05-10 19:39 UTC, mattermod commented
Building app in separate branch.

2022-05-10 19:43 UTC, mattermod commented
Successfully building:  
https://circleci.com/gh/mattermost/mattermost-mobile/22485  
https://circleci.com/gh/mattermost/mattermost-mobile/22484

2022-05-10 20:13 UTC, mattermod commented
Artifact links:  
https://output.circle-artifacts.com/output/job/8467ead8-586e-4585-b910-d6c772d61f71/artifacts/0/tmp/artifacts/Mattermost_Beta.ipa  
https://output.circle-artifacts.com/output/job/328b1bc5-db02-484f-b10c-a674a2f59401/artifacts/0/tmp/artifacts/Mattermost_Beta.apk

2022-05-10 20:17 UTC, matthewbirtch approved these changes
Looks great! Thanks @enahum

2022-05-11 12:41 UTC, larkox approved these changes

2022-05-11 12:42 UTC, merged