[Gekidou] [WIP] Groups API Calls
mattermost/mattermost-mobile pull request #6277
Opened 2022-05-16 07:48 UTC by shazm

#### Summary

#### Ticket Link

#### Checklist

- [ ] Added or updated unit tests (required for all new features)
- [ ] Has UI changes
- [ ] Includes text changes and localization file updates
- [ ] Have tested against the 5 core themes to ensure consistency between them.

#### Device Information
This PR was tested on: 

#### Screenshots

#### Release Note

```release-note

```

2022-05-23 13:43 UTC, enahum commented
rename the actions to `fetch...`

2022-05-23 14:19 UTC, larkox approved these changes
Apart of Elias' comment, LGTM.

2022-05-23 23:26 UTC, shazm commented
> rename the actions to `fetch...`

Fixed 👍

2022-05-25 22:57 UTC, enahum requested changes

2022-05-25 22:57 UTC, enahum commented on app/components/autocomplete/at_mention/at_mention.tsx
> +};
move to remote and rename to fetch

2022-05-26 18:09 UTC, enahum approved these changes

2022-05-26 18:10 UTC, merged