[Gekidou] Channel Info screen
mattermost/mattermost-mobile pull request #6330
Opened 2022-06-01 20:57 UTC by enahum

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-41575

```release-note
NONE
```

2022-06-01 21:14 UTC, mattermod commented
Building app in separate branch.

2022-06-01 21:19 UTC, mattermod commented
Successfully building:  
https://circleci.com/gh/mattermost/mattermost-mobile/22931  
https://circleci.com/gh/mattermost/mattermost-mobile/22930

2022-06-02 11:00 UTC, larkox requested changes
Great work! Nothing seemingly blocking, but marking it as request changes because of the amount of comments.

2022-06-02 14:01 UTC, enahum commented on app/components/markdown/markdown.tsx
> +                <Text style={style.bold}>
is in the figma design
![image](https://user-images.githubusercontent.com/6757047/171646879-1ab8e583-5025-449f-b1f4-4905ec439d60.png)

2022-06-02 14:03 UTC, enahum commented on app/components/markdown/markdown.tsx
> +    const renderer = useMemo(createRenderer, [theme, textStyles]);
block styles are based on the theme, imageMetadata will not change, nor any of the others.. in fact textStyles if changed is also cause of a theme change

2022-06-02 14:15 UTC, matthewbirtch requested changes
Awesome work @enahum. It's looking great. Here are a few things I found:

1. I got in to a scenario where I double tapped the channel name to open the channel modal. Two copies of the modal opened up. I closed one, but then the last one couldn't be closed.
2. If I trigger the Channel info modal from the channel quick actions bottom sheet, there is no `X` to close the modal (although I can dismiss by swiping down). If I open the channel info model by tapping the channel name, the `X` _does_ show. We should make sure the `X` is there in all cases.
3. The scroll bar seems to interfere with the content. Can we make sure it stays anchored closer to the right edge? (see screenshot of what I mean)

<img src="https://user-images.githubusercontent.com/2040554/171643377-c91e0ddc-a0fd-4d73-8fd0-1e149b591dee.PNG" width="414">

4. The label for the `Leave channel` menu item seems to be misaligned with the other menu item label
<img src="https://user-images.githubusercontent.com/2040554/171644648-17041240-3905-4e94-8499-6b444ef5744b.PNG" width="414">

5. When I go to the 'Edit channel' view, all the inputs are in the focused state for all inputs that have values filled in. Should we file this separately?
<img src="https://user-images.githubusercontent.com/2040554/171644947-5034c048-c0a8-41b7-85c0-ba2a03443360.jpeg" width="414">

6. For DM info modal, the font size for the user's title is too large. Can we make sure it is 16?
<img src="https://user-images.githubusercontent.com/2040554/171645985-afe1466a-ced3-42df-b181-300eb573bd8a.PNG" width="414">

7. For DM and GM info modal, the `Close direct message` menu option is misaligned
8. It looks like there is more space above and below the divider lines than in the design. Can we reduce the space by 12px above and below? But keep the spacing as-is in the top section between the 'Created by' line and the first divider line.
9. On tablet, I think we need a bit more margin at the bottom of the modal to ensure the last few items aren't so tight to the bottom. Can we add 16px margin at the bottom?
10. On tablet, the 'Copy link' button isn't spanning the same width as the other buttons.
![IMG_D369A71ADB1B-1](https://user-images.githubusercontent.com/2040554/171649365-25ac2e09-9ff0-48e2-8fc2-5b7242e6970c.jpeg)

2022-06-02 15:53 UTC, enahum commented
@matthewbirtch all items should be correct now

2022-06-02 15:59 UTC, mattermod commented
Successfully building:  
https://circleci.com/gh/mattermost/mattermost-mobile/22952  
https://circleci.com/gh/mattermost/mattermost-mobile/22951

2022-06-02 17:30 UTC, matthewbirtch commented
Still seeing these ones:

>  The label for the `Leave channel` menu item seems to be misaligned with the other menu item label

>  For DM and GM info modal, the `Close direct message` menu option is misaligned

Everything else looks great to me

2022-06-02 17:39 UTC, enahum commented
> Still seeing these ones:
> 
> > The label for the `Leave channel` menu item seems to be misaligned with the other menu item label
> 
> > For DM and GM info modal, the `Close direct message` menu option is misaligned
> 
> Everything else looks great to me

done

2022-06-02 20:08 UTC, matthewbirtch approved these changes

2022-06-02 20:09 UTC, merged