Fix some of the bugs created by changing the text size at a OS level
mattermost/mattermost-mobile pull request #6344
Opened 2022-06-03 14:14 UTC by larkox

#### Summary
Address some of the issues when the text is set to a different size at OS level. Not addressed anything regarding size of display (different setting at least in Android).

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-44709

#### Screenshots
Before:
![Screenshot from 2022-06-03 14-05-11](https://user-images.githubusercontent.com/1933730/171851215-6569f2b3-3621-4c5f-9bcc-cb30537b7ed6.png)
![Screenshot from 2022-06-03 14-05-24](https://user-images.githubusercontent.com/1933730/171851221-f5f5e5a9-38c7-4b4a-beb7-74277b755c66.png)
![Screenshot from 2022-06-03 14-12-11](https://user-images.githubusercontent.com/1933730/171851224-4be92776-373b-4e4e-aabb-3c1d8b49116b.png)
![Screenshot from 2022-06-03 14-12-28](https://user-images.githubusercontent.com/1933730/171851226-c7a70232-a37e-40de-b36f-0817db4c3607.png)

After:
![Screenshot from 2022-06-03 13-54-27](https://user-images.githubusercontent.com/1933730/171849820-41db1204-66fc-4865-bccd-ee61bf95e33b.png)
![Screenshot from 2022-06-03 14-02-27](https://user-images.githubusercontent.com/1933730/171849825-420caad5-978b-470d-8dda-32edd0297f10.png)
![Screenshot from 2022-06-03 14-01-29](https://user-images.githubusercontent.com/1933730/171849839-1ebd75b7-62c5-4361-9cac-39d46ee09fd7.png)
![Screenshot from 2022-06-03 14-01-37](https://user-images.githubusercontent.com/1933730/171849842-54e38e1e-fa38-4918-88d6-1f412e9d8dee.png)

#### Release Note
```release-note
NONE
```

2022-06-03 14:39 UTC, mattermod commented
Successfully building:  
https://circleci.com/gh/mattermost/mattermost-mobile/23006  
https://circleci.com/gh/mattermost/mattermost-mobile/23005

2022-06-03 15:08 UTC, mattermod commented
Artifact links:  
https://output.circle-artifacts.com/output/job/eebcf100-a7a5-4a05-9d57-9a37102a0da5/artifacts/0/tmp/artifacts/Mattermost_Beta.apk  
https://output.circle-artifacts.com/output/job/2e77a051-6316-41e2-a28a-e0f4d592e0d0/artifacts/0/tmp/artifacts/Mattermost_Beta.ipa

2022-06-03 16:11 UTC, matthewbirtch requested changes
There are definitely a number of issues introduced with this:

I'll start with the home screen for now, but I think this is going to require a lot of review time to identify all the issues that might be affected by this.
- The team sidebar icons scale up - I think we can keep those a fixed size
- The unread dot becomes an oval shape and is positioned incorrectly (probably because the team icons are scaling up)
- 'unreads' filter button next to the 'Find Channels' input is smaller than the height of the find channels input
- The 'Threads' icon doesn't scale the same way as the channel icons and avatars do
- Not all changes seems to happen immediately when playing around with the OS text size options. Sometimes I have to close the app and restart it for changes to apply. The channel icons and avatars, for example, seem to stay the same size un
- Are we able to increase the spacing between items when scaling up the items? It gets quite tight
![IMG_9411](https://user-images.githubusercontent.com/2040554/171904145-3e12790f-186e-4d21-a7b8-db6c2f7141e6.PNG)

Also noticed this in the servers bottom sheet:
- the button label 'Add a server' gets cut off
<img src="https://user-images.githubusercontent.com/2040554/171903903-c7de6b72-8c7e-491e-8940-7bce84b3a61b.PNG" width="414">

2022-06-06 08:17 UTC, larkox commented
> There are definitely a number of issues introduced with this:
> 
> I'll start with the home screen for now, but I think this is going to require a lot of review time to identify all the issues that might be affected by this.
> 
>     * The team sidebar icons scale up - I think we can keep those a fixed size

I thought keeping them at fixed size make things cluttered, since the letters and the badge numbers grow / shrink. But I can revert the scalling of the icons themselves.

> 
>     * The unread dot becomes an oval shape and is positioned incorrectly (probably because the team icons are scaling up)
>

Yes, I may have missed something with the scalling of that.
 
>     * 'unreads' filter button next to the 'Find Channels' input is smaller than the height of the find channels input
>

Missed it in my local :sweat_smile:
 
>     * The 'Threads' icon doesn't scale the same way as the channel icons and avatars do
>

Missed it in my local : sweat_smile: 
>     * Not all changes seems to happen immediately when playing around with the OS text size options. Sometimes I have to close the app and restart it for changes to apply. The channel icons and avatars, for example, seem to stay the same size un
> 

This is not hard to solve, but requires a bit more of work. The problem is that right now there is nothing listening to changes in the ratio changes, but even if nothing is listening, the text changes sizes...

So we would have to create a hook that, for example, when the app comes into view, checks again the ratio, and propagates the change. That would create some artifact of everything that have to change size moving into place just after you open the app. Not a big deal I think, but just to let you know.

Whether it makes sense to do this in this PR or not, 0/5. I will give it a quick try when I start fixing all these issues.

>     * Are we able to increase the spacing between items when scaling up the items? It gets quite tight
>       ![IMG_9411](https://user-images.githubusercontent.com/2040554/171904145-3e12790f-186e-4d21-a7b8-db6c2f7141e6.PNG)
>

If I am not mistaken, should not be much of a problem. We just need to adjust a few values. But this will be the kind of changes you will need to restart the app to properly see the changes until we have the hook I was talking about.
 
> 
> Also noticed this in the servers bottom sheet:
> 
>     * the button label 'Add a server' gets cut off
> 
> 
> <img alt="" width="414" src="https://user-images.githubusercontent.com/2040554/171903903-c7de6b72-8c7e-491e-8940-7bce84b3a61b.PNG">

Didn't check the bottom sheet yet, but I can give it a look.

2022-06-14 07:57 UTC, larkox commented
This PR can be considered a POC. Further work will need to be done to properly define what are exactly the changes we want to make, and the different parts of the ui that will need to be updated.

2022-06-14 07:57 UTC, closed without merging