[Gekidou] Solidarity poc
mattermost/mattermost-mobile pull request #6394
Opened 2022-06-16 20:31 UTC by ElonVolo

#### Summary

Uses the [Solidarity](https://infinitered.github.io/solidarity/#/) dependency checker to check during the npm install to see if all the global dependencies (Xcode, npm, react-native-cli, environment variables, etc) required to build mattermost-mobile are installed on a developer's machine. If all the required dependencies are present on a developer's machine, the npm install proceeds; if some are missing or are an incorrect version then the npm install for mattermost-mobile is halted until the necessary dependencies are installed and correctly configured.

#### Ticket Link

This is a possible fix for issues such as mattermost/mattermost-mobile#6329. If the user is informed that they don't have the necessary dependencies required to build the app, considerable amounts of developer time on both ends can be saved as it avoids back-and-forths on newly reported github issues that are solved by telling someone they need to up/downgrade a different version of a dependency.

#### Checklist

#### Device Information
This PR was tested on: 

#### Screenshots

See mattermost/mattermost-mobile#6329 for a screenshot of proposed addition.

#### Release Note

```release-note

```

2022-06-16 20:32 UTC, mattermod commented
Hello @ElonVolo,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

Per the [Mattermost Contribution Guide](https://developers.mattermost.com/contribute/getting-started/), we need to add you to the list of [approved contributors](https://docs.google.com/spreadsheets/d/1NTCeG-iL_VS9bFqtmHSfwETo5f-8MQ7oMDE5IUYJi_Y/pubhtml?gid=0&single=true) for the Mattermost project.

**Please help complete the Mattermost [contribution license agreement](http://www.mattermost.org/mattermost-contributor-agreement/)?**
Once you have signed the CLA, please comment with `/check-cla` and confirm that the CLA check is green.

This is a standard procedure for many open source projects.

Please let us know if you have any questions.

We are very happy to have you join our growing community! If you're not yet a member, please consider joining our [Contributors community channel](https://pre-release.mattermost.com/core/channels/tickets) to meet other contributors and discuss new opportunities with the core team.

2022-06-16 20:38 UTC, enahum requested changes
Thanks for this @ElonVolo a quick review with a comment

2022-06-16 22:03 UTC, enahum commented
/check-cla

2022-06-17 04:52 UTC, ElonVolo commented on .solidarity
> +      "Cocoapods": [
I have the two following questions.

1. Should take out the CocoaPods check in or leave it in there?

One the of advantages of putting all the checks in a dependence checking is that the dependency checker file (in this case the .solidarity file) effectively turns into a single source of truth document that lists everything required to do the build and that can't become outdated like a README.md or a wiki page; if the config file's outdated nothing works and people know immediately it must be updated (to get stuff to work again). But if that would hamper some workflow everyone is using I can remove the .solidarity config file entry for Cocoapods.

2. Is exactly version 2.0.2 of Bundler (mentioned in the Mattermost dev environment set up docs) required ? I'm currently on Ruby v3.1.2 (via rvm) and when I do ```gem install bundler --version 2.0.2```, I end up with Bundler version 2.3.7 in spite of my specifying the earlier version (who knows?). Is there actually a range of Bundler versions I should be targeting instead?

2022-06-28 01:01 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2022-08-10 13:52 UTC, maxgorovenko commented
This check could save me couple hours :(

2022-08-20 13:55 UTC, enahum approved these changes

2022-08-20 13:56 UTC, enahum commented
@ElonVolo thanks for bringing this to our attention and for laying the ground work for this.

2022-08-22 10:13 UTC, merged

2022-08-29 07:29 UTC, ElonVolo commented
No prob. 😀 I'm always happy to promote my philosophy of pro-active
synchronization and standardization of global dependencies across developer
machines, as I feel that people should spend their time actually developing
valuable and useful features for software instead of spending frustrating
days of trying to figure out why their development environment isn't
building stuff (when their coworker's strangely seems to have no issue).
I've found this approach is one of the cheapest and easiest things you can
do on a project to effectively and immediately boost developer velocity.

On Sat, Aug 20, 2022 at 9:56 AM Elias Nahum ***@***.***>
wrote:

> @ElonVolo <https://github.com/ElonVolo> thanks for bringing this to our
> attention and for laying the ground work for this.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/mattermost/mattermost-mobile/pull/6394#issuecomment-1221319374>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/APE6QJX3VHWPIDDINPW4Y4TV2DPYDANCNFSM5Y77KIHA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>