MM-45456 - Gekidou LoadingUnreads component keeps spinning
mattermost/mattermost-mobile pull request #6453
Opened 2022-07-02 10:53 UTC by avinashlng1080

#### Summary
As stated in the ticket, the loader next to the server displayname kept spinning when we add a new server.

This PR fixes this issue by: 
1. Ensuring that this component loading state is dictated only when it receives an event, so that it just doesn't spin on mount.
2. Add a workaround on top of the `cancelAnimation` function call due to a bug on reanimated 2.  [The bug](https://github.com/software-mansion/react-native-reanimated/issues/2733) in itself prevents a shared value that switches between two values from being interrupted/cancelled.

@coltoneshaw  - I'm adding you to this PR so that you can verify if the builds work for you.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-45456

#### Device Information
This PR was tested on: 

#### Release Note
```release-note
NONE
```

2022-07-02 10:54 UTC, mattermod commented
Building app in separate branch.

2022-07-02 11:00 UTC, enahum requested changes

2022-07-02 11:00 UTC, enahum commented on app/screens/home/channel_list/categories_list/header/loading_unreads.tsx
> +    const [loading, setLoading] = useState(false);
The even is emitted a bit late and the perception changes.

2022-07-05 08:24 UTC, larkox approved these changes
LGTM, no extra comments appart from enahum's.

2022-07-05 13:47 UTC, avinashlng1080 commented on app/screens/navigation.ts
> +        DeviceEventEmitter.emit(Events.FETCHING_POSTS, false);
use case : 
You have server A and B... you are on B...then you remove B....the loader was not stopping.... this 'emit' fixes the issue.

2022-07-05 13:48 UTC, avinashlng1080 commented on app/actions/remote/entry/common.ts
> +    setTimeout(async () => {
By delaying this `fetchPostsForUnreadChannels`, the home screen gets time to load and it properly catches the `FETCHING_POSTS` event.

2022-07-08 10:13 UTC, avinashlng1080 commented on app/actions/remote/entry/common.ts
> +    setTimeout(async () => {
Agreed.  I'm going to merge this PR for the time being.

2022-07-08 10:14 UTC, merged