Autocomplete Group Member Count
mattermost/mattermost-mobile pull request #6460
Opened 2022-07-07 02:55 UTC by shazm

#### Summary

Shows member counts for groups in the `@mention` auto-complete suggestions.

#### Ticket Link

Figma: https://www.figma.com/file/bPfMqK5N1QWs3TNIYmUdqP/MM-44349-Group-Mentions-Autocomplete-Update?node-id=0%3A1
Jira: https://mattermost.atlassian.net/browse/MM-44759

#### Checklist

- [x] Added or updated unit tests (required for all new features)
- [x] Has UI changes
- [ ] Includes text changes and localization file updates
- [x] Have tested against the 5 core themes to ensure consistency between them.

#### Device Information
This PR was tested on: 

- iPhone 13 / iOS 15.5 (Simulator)
- Pixel 5 / API30 (Simulator)

#### Screenshots
<img width="400" alt="Screen Shot 2022-07-07 at 12 36 58 pm" src="https://user-images.githubusercontent.com/456511/177680714-49a32c07-0c3f-4968-a2cb-69de93cd1b68.png">
<img width="400" alt="Screen Shot 2022-07-07 at 12 32 47 pm" src="https://user-images.githubusercontent.com/456511/177680729-d2e30faa-1be9-4ece-a8ce-3c3c1185d244.png">

#### Release Note

```release-note

```

2022-07-07 02:56 UTC, shazm commented
NOTE: This includes a migration for the `memberCount` field in the groups table.

2022-07-07 08:17 UTC, larkox approved these changes

2022-07-07 08:17 UTC, larkox commented on app/database/migration/server/index.ts
> +            addColumns({
This is more a note to myself (or to the platform team) but we should consider adding unit tests for migrations.

2022-07-07 08:18 UTC, larkox commented
Also, 0/5, but maybe we should have the migration in a different PR. Thoughts @avinashlng1080 ?

2022-07-07 13:17 UTC, matthewbirtch requested changes
Looks good for the most part @shazm. The only thing that needs fixing is how we're truncating the names. It looks like things are just getting cut off, but we should be using the `…` instead. Maybe have a look at how that's done for members autocomplete.

<img width="482" alt="Screen Shot 2022-07-07 at 9 14 50 AM" src="https://user-images.githubusercontent.com/2040554/177782705-0bbe3368-d00a-471e-9e7f-30ad9e96b292.png">

2022-07-07 22:13 UTC, shazm commented
> Also, 0/5, but maybe we should have the migration in a different PR. Thoughts @avinashlng1080 ?

I think leaving it as part of the PR is fine as I imagine they would usually be rare and small - anything substantial I'd expect would be in it's own PR though.

2022-07-07 22:39 UTC, enahum commented
> Also, 0/5, but maybe we should have the migration in a different PR. Thoughts @avinashlng1080 ?

1. Yes, this sort of changes should be in their own PR
2. I'll question the need of storing the group member count in the database in the first place. I believe the autocomplete always displaya info recently fetched from the server and not data that has been stored, so the member count is available in that context, will it be used elsewhere?

2022-07-08 00:13 UTC, shazm commented
> > Also, 0/5, but maybe we should have the migration in a different PR. Thoughts @avinashlng1080 ?
> 
> 1. Yes, this sort of changes should be in their own PR
> 2. I'll question the need of storing the group member count in the database in the first place. I believe the autocomplete always displaya info recently fetched from the server and not data that has been stored, so the member count is available in that context, will it be used elsewhere?

I believe there is work happening on giving an alert to the user that they are about to notify X amount of users, so that's likely another place this will be needed if they are about to ping a group?

Stepping back a bit - the `GroupModel` is passed to the autocomplete (after the records have been prepared to be saved from the API) - not the API `Group` record itself. This is because it should be able to handle the API errors and fall back to the local db store if needed, which returns the `GroupModel`. 

0/5 - Happy to update the component to handle the two different types, but it will add a bit more complexity, and will likely need to do the same in other places the member count will be needed.

2022-07-08 13:57 UTC, avinashlng1080 requested changes
Just one nit and then ready to approve

2022-07-12 02:38 UTC, shazm commented
@matthewbirtch - I've added the textWrap elipsis; do we want to give equal space to both the `displayName` and `name`? Or favour one over the other? It's 2:1 at the moment:

<img width="400" alt="Screen Shot 2022-07-12 at 12 36 26 pm" src="https://user-images.githubusercontent.com/456511/178396491-741a3f1f-4644-4f46-8aa7-6904e98ea853.png">

2022-07-12 23:22 UTC, shazm commented
Updated -

<img width="300" alt="Screen Shot 2022-07-13 at 9 21 45 am" src="https://user-images.githubusercontent.com/456511/178614744-85711868-85b7-4701-b389-2bebb362682f.png">

2022-07-18 06:22 UTC, avinashlng1080 approved these changes

2022-07-18 06:22 UTC, avinashlng1080 commented on app/database/schema/server/index.ts
> +    version: 3,
These files have been reviewed last week.

2022-07-29 00:17 UTC, shazm commented
@avinashlng1080 / @larkox - merged gekidou / resolved conflicts 👍

2022-07-29 08:09 UTC, avinashlng1080 approved these changes

2022-07-29 17:24 UTC, larkox approved these changes
LGTM

2022-07-29 17:24 UTC, larkox commented on app/database/migration/server/index.ts
> +
Unneded change?

2022-07-31 21:57 UTC, shazm commented on app/database/migration/server/index.ts
> +
I think added by ESLint 👀

2022-07-31 22:06 UTC, merged