Gekidou upgrade RN to 0.69.3 and dependencies
mattermost/mattermost-mobile pull request #6537
Opened 2022-08-03 17:16 UTC by enahum

#### Summary
This PR upgrades all dependencies specially React Native to version 0.69.3, another important update is the targetSdk for Android to 31, this change on Android has a small effect on how push notifications are handled, so it would be a very good idea to test notifications while the app is closed and sitting in the background, by tapping the notification to open it and by replying to the notifications directly. This should be tested for CRT and non-CRT

#### Release Note
```release-note
NONE
```

2022-08-03 20:16 UTC, mattermod commented
Building app in separate branch.

2022-08-03 20:20 UTC, mattermod commented
Successfully building:  
https://circleci.com/gh/mattermost/mattermost-mobile/24220  
https://circleci.com/gh/mattermost/mattermost-mobile/24219

2022-08-04 08:27 UTC, larkox requested changes
Looks great!
Just a few minor comments, and one change.

2022-08-04 08:27 UTC, larkox commented on app/screens/edit_post/edit_post.tsx
> +    const handleUIUpdates = useCallback((res: {error?: unknown}) => {
If res is always defined, there is no need for the optional chaining (`?.`) in the next line. If not, it should be optional here.

2022-08-04 13:30 UTC, larkox approved these changes

2022-08-04 20:08 UTC, josephbaylon commented
@enahum Initial observations.

iOS app seems to work fine on both CRT and non-CRT mode and also the notifications while app is closed. However, Android has several issues (see below).

1. Not sure if this is a bug but comparing behavior with v1, on both iOS and Android, in-app notifications doesn't happen anymore.
2. For Android only, on both CRT and non-CRT mode, the following observations are made
- When replying to a notification, the notification is not dismissed after reply is sent
![pr-6537-notif-not-dismissed](https://user-images.githubusercontent.com/487991/182942875-aad9058b-124a-4a5b-a12b-8dba73b85759.png)

- App crashes on logout
![pr-6537-logout-crash](https://user-images.githubusercontent.com/487991/182942912-b371cb51-46b5-47da-a899-33f0c2ee09e5.png)

- This is rather intermittent and I couldn't get the exact steps to replicate but sometimes when tapping on the notification and redirected to channel, the channel post list is empty and is still empty even when switching channels. The only way to see the channel post list is to close and re-open app.
![pr-6537-empty-posts](https://user-images.githubusercontent.com/487991/182942987-e16bfc0a-72f9-429f-8dbe-35b2d6ace361.png)

2022-08-05 13:12 UTC, enahum commented
@josephbaylon 
> on both iOS and Android, in-app notifications doesn't happen anymore.

![image](https://user-images.githubusercontent.com/6757047/183079523-f9e3cdba-2da5-4446-89dc-95c0972e8d0f.png)

is working just fine.

> When replying to a notification, the notification is not dismissed after reply is sent

This is the same in the current v2 beta app, no change made here

> App crashes on logout
Known issue in the current beta app see the convo here https://community.mattermost.com/core/pl/ey9p95urcf8udk1rew5bmhe8be

> This is rather intermittent and I couldn't get the exact steps to replicate but sometimes when tapping on the notification and redirected to channel, the channel post list is empty and is still empty even when switching channels. The only way to see the channel post list is to close and re-open app.

I wasn't able to reproduce this one at all, would you mind spending some time trying to identify the repro steps? Also can you confirm this is related to this PR and does not happen in the current build ?

2022-08-05 23:35 UTC, josephbaylon approved these changes
I'm still having trouble with in-app on Android (iOS now works). But since it's only happening on my device I'm going to go ahead and approve the PR.

Also, I can't seem to repro the intermittent issue I saw on Android regarding empty post list.

2022-08-08 13:06 UTC, merged