[Gekidou MM-46195] Fix team picker height
mattermost/mattermost-mobile pull request #6554
Opened 2022-08-06 15:22 UTC by jfrerich

#### Summary
This PR fixes the team picker height to account for the bottomSheet margins and title separator margins

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-46195

#### Checklist

- [ ] Added or updated unit tests (required for all new features)
- [ ] Has UI changes
- [ ] Includes text changes and localization file updates
- [ ] Have tested against the 5 core themes to ensure consistency between them.

#### Device Information
This PR was tested on: 

#### Screenshots

#### Release Note

```release-note

```

2022-08-06 16:10 UTC, matthewbirtch commented
> **QUESTION FOR ALL:** Why to we need the bottom screen to have the horizontal padding? I would think we should want the items to extend to the edge of the bottom screen.

I think you're right. The padding shouldn't be added the the bottom sheet itself, but to the items within so they span the full width of the sheet

2022-08-06 21:00 UTC, jfrerich commented
I added a ticket to make the padding change to the bottom sheet. https://mattermost.atlassian.net/browse/MM-46247

2022-08-06 21:02 UTC, matthewbirtch commented
> I added a ticket to make the padding change to the bottom sheet. https://mattermost.atlassian.net/browse/MM-46247

There's a ticket to look at all bottom sheets for consistency as well: https://mattermost.atlassian.net/browse/MM-44138

2022-08-06 21:08 UTC, jfrerich commented
That's a great document :)

2022-08-06 21:26 UTC, enahum commented
iPad screenshots?

Alsoplease do share screenshots of the add team bottom sheet (by pressing the + in the team sidebar) including there are no more teams to join for both phones and iPad.

Thanks!

2022-08-07 14:44 UTC, matthewbirtch approved these changes
Looks good to me!

2022-08-07 15:25 UTC, jfrerich commented on app/components/team_sidebar/add_team/add_team_slide_up.tsx
> +    const hasOtherTeams = Boolean(otherTeams.length);
This needs to be a boolean or TeamList is going to show and cause an error.

2022-08-07 15:26 UTC, jfrerich commented
> iPad screenshots?
> 
> Also please do share screenshots of the add team bottom sheet (by pressing the + in the team sidebar) including there are no more teams to join for both phones and iPad.
> 
> Thanks!

I added the screenshots and made one change inside `add_team_slide_up.tsx`, with a PR comment describing why.

2022-08-07 15:30 UTC, jfrerich commented
@enahum, those screenshots are from a user that is a sysadmin.  When I login as a member user, I don't see any team sidebar, which seems wrong. Shouldn't a member user also be able to change/join other teams?

<img width="412" alt="image" src="https://user-images.githubusercontent.com/7575921/183298600-3f037fee-e9c2-4d4f-88e5-feb15fa4f0d5.png">

2022-08-07 15:32 UTC, enahum commented
> @enahum, those screenshots are from a user that is a sysadmin.  When I login as a member user, I don't see any team sidebar, which seems wrong. Shouldn't a member user also be able to change/join other teams?
> 
> 
> 
> <img width="412" alt="image" src="https://user-images.githubusercontent.com/7575921/183298600-3f037fee-e9c2-4d4f-88e5-feb15fa4f0d5.png">

If the teams are opened then yes, check the team settings

2022-08-07 15:34 UTC, jfrerich commented
> > @enahum, those screenshots are from a user that is a sysadmin.  When I login as a member user, I don't see any team sidebar, which seems wrong. Shouldn't a member user also be able to change/join other teams?
> 
> If the teams are opened then yes, check the team settings

I have 3 teams set to `Anyone Can Join`

2022-08-07 15:38 UTC, jfrerich commented
I am getting this warning `Warning: An empty or undefined "groups" array has been passed to the handleGroups method`.  Perhaps that is the offender.

2022-08-07 15:39 UTC, enahum commented
> > > @enahum, those screenshots are from a user that is a sysadmin.  When I login as a member user, I don't see any team sidebar, which seems wrong. Shouldn't a member user also be able to change/join other teams?
> 
> > 
> 
> > If the teams are opened then yes, check the team settings
> 
> 
> 
> I have 3 teams set to `Anyone Can Join` 
> 
> 

Open a ticket, as it seems that if you are not a member of two teams the `+` option to join another team is not available.

@matthewbirtch if you can comment on the ticket where the option should be visible that'll be nice

2022-08-07 15:40 UTC, enahum commented
> I am getting this warning `Warning: An empty or undefined "groups" array has been passed to the handleGroups method`.  Perhaps that is the offender. 

Not at all, that means that we fetched groups the server returned an empty array, the warning is totally fine

2022-08-07 15:46 UTC, jfrerich commented
> > > > @enahum, those screenshots are from a user that is a sysadmin.  When I login as a member user, I don't see any team sidebar, which seems wrong. Shouldn't a member user also be able to change/join other teams?
> > 
> > > If the teams are opened then yes, check the team settings
> > 
> > 
> > I have 3 teams set to `Anyone Can Join`
> 
> Open a ticket, as it seems that if you are not a member of two teams the `+` option to join another team is not available.
> 
> @matthewbirtch if you can comment on the ticket where the option should be visible that'll be nice

Ticket created and I verified adding a user to two teams via the webapp adds the team sidebar on mobile.  https://mattermost.atlassian.net/browse/MM-46248

2022-08-07 22:07 UTC, matthewbirtch commented
> @matthewbirtch if you can comment on the ticket where the option should be visible that'll be nice

In the case where you are only part of one team, the team sidebar does not show. However, the team menu (which is supposed to open when you tap on the team name at the top of the Home Screen - but this is not done yet) was where a menu option will be to "join or creat another team".

2022-08-08 08:50 UTC, larkox requested changes
LGTM, just a minor refactor.

2022-08-08 08:50 UTC, larkox commented on app/screens/navigation.ts
> +    const BOTTOM_SHEET_TOP_PADDING = 20; // bottomSheet paddingTop
For sure, I would move the BOTTOM_SHEET_TOP_PADDING to the bottom sheet component, and make the style use the constant. The other margin, I am not sure where it comes from, so not sure if this is the right place to define it.

2022-08-08 10:29 UTC, enahum requested changes

2022-08-08 10:29 UTC, enahum commented on app/screens/navigation.ts
> +    const ADDITIONAL_BOTTOM_MARGIN = 34;
To me this looks like the bottom inset on an iphone, consider using that instead of a constant

2022-08-08 16:09 UTC, jfrerich commented on app/screens/navigation.ts
> +    insets: EdgeInsets;
I added as a prop because insets come from the `useSaveAreaInsets` hook and hooks are not allowed in a function, only a component.

2022-08-08 19:03 UTC, jfrerich commented on app/screens/navigation.ts
> +    insets: EdgeInsets;
you know, I agree and will pull this out and keep it contained to the the component.

2022-08-08 19:35 UTC, enahum approved these changes
lgtm

2022-08-08 19:35 UTC, enahum commented on app/components/team_sidebar/add_team/index.tsx
> +export const getTeamsSnapHeight = ({dimensions, teams, insets}: TeamsSnapProps) => {
0/5 I would probably move this to a helper or utility file

2022-08-10 10:03 UTC, larkox approved these changes

2022-08-10 11:32 UTC, merged