Fix MM-46309
mattermost/mattermost-mobile pull request #6567
Opened 2022-08-11 14:11 UTC by larkox

#### Summary
Fix MM-46309

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-46309

#### Release Note
```release-note
NONE
```

2022-08-11 14:51 UTC, enahum approved these changes
Overall looks good to me, left a couple of comments though to see if we take action

2022-08-11 14:51 UTC, enahum commented on app/utils/file/index.ts
> +            return `${FileSystem.CachesDirectoryPath}/${server}/${filename}-${file.id!}.${extension}`;
I think we should apply here the fix for https://mattermost.atlassian.net/browse/MM-46320 unless I'm mistaken and is not this one?

2022-08-11 14:51 UTC, enahum commented on app/utils/security.ts
> -export const hashCode = (str: string): string => {
I wonder if we should keep this and add a deprecated comment.

The reason to keep it as cause we can use it to delete the previous database files and cache folders.

2022-08-11 15:01 UTC, jupenur requested changes
Just one thing: we need to use the URL-compatible variant of Base64 that doesn't contain slashes: https://datatracker.ietf.org/doc/html/rfc4648#section-5

It's a pretty trivial change though. Instead of `base64.encode(serverUrl)` we just need to do `base64.encode(serverUrl).replace(/\+/g, '-').replace(/\//g, '_')` everywhere.

2022-08-11 15:56 UTC, enahum commented
Cool, perhaps a utility function to minimize the changes everywhere

2022-08-11 16:16 UTC, jupenur commented on app/utils/security.ts
> +export const hashServerUrl = (str: string): string => {
Nit: this isn't a hash. No reason to tie this to server URLs specifically either; there's a good chance we find more use cases for this type of encoding in the future.

A more accurate name would be something like `urlSafeBase64Encode`.

2022-08-15 10:58 UTC, jupenur approved these changes
Sorry for the delay. LGTM!

2022-08-15 14:55 UTC, enahum approved these changes

2022-08-15 14:55 UTC, merged