[MM-2287] change emoji picker logic/ui
mattermost/mattermost-mobile pull request #6591
Opened 2022-08-22 23:27 UTC by vdanylov

#### Summary

#### Ticket Link
JIRA ticket: https://mattermost.atlassian.net/browse/MM-22847

#### Checklist

- [ ] Added or updated unit tests (required for all new features)
- [x] Has UI changes
- [ ] Includes text changes and localization file updates
- [ ] Have tested against the 5 core themes to ensure consistency between them.

#### Device Information
Emulators: IPad 12,9 inch (5th generation), Iphone 13mini, Iphone 13 Pro Max

#### Screenshots
![image](https://user-images.githubusercontent.com/20551843/186035290-26f7f7f3-3d3a-4e7c-9440-3d36cf44cfd2.png)![image](https://user-images.githubusercontent.com/20551843/186035594-4bd6cc97-8dc3-49a2-b1f4-eab2ae944071.png)
#### Release Note

```release-note
There are a few unsolved issues:
 1. Bottom sheet doesn't allow to render static absolute component at the bottom. There is a problem to display emoji section in case of initial render:

![image](https://user-images.githubusercontent.com/20551843/186036553-5bc0abe0-f8fd-49be-a4da-e5f2fdc7a6d1.png)
 
2. openAsBottomSheet has no props to modify standard UI of the window.
3. Backdrop background of EmojiPicker disappears in case of change snap point to initial one after full height size.
4. App freezes after close modal (known issue for bottom sheet library)
 
```
P.S. @enahum I'm aware about leftover, but unfortunately it's out of scope 4-6 hours, we can discuss it after review or before. Thank You.

2022-08-22 23:27 UTC, mattermod commented
Hello @vdanylov,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2022-08-24 12:50 UTC, enahum requested changes
@vdanylov code looks good but it definitely has problems

1. Pressing the icons on the tab bar has a very very poor performance in comparison with the existing solution
2. On Android, using the search functionality is near to impossible and the SectionList does not scroll
3. the placement of the emojis does not look good in terms of spacing between them and the overall distribution across the the width of the screen

Definitely a good first effort but some work needs to be done in order to reach release quality

2022-08-25 13:18 UTC, vdanylov commented
> @vdanylov code looks good but it definitely has problems
> 
> 1. Pressing the icons on the tab bar has a very very poor performance in comparison with the existing solution
> 2. On Android, using the search functionality is near to impossible and the SectionList does not scroll
> 3. the placement of the emojis does not look good in terms of spacing between them and the overall distribution across the the width of the screen
> 
> Definitely a good first effort but some work needs to be done in order to reach release quality

Thanks for review, will improve my PR

2022-08-25 13:33 UTC, matthewbirtch requested changes
Thanks for the work on this @vdanylov. There are a few things I'd like to call out from a UX standpoint that we should resolve if possible. Let me know if you'd like to chat through any of these.

1. The transition for showing the emoji picker bottom sheet is quite delayed and doesn't animate properly. It should be much more responsive and snappy. Can you refer to the other bottom sheets to see how it should animate on? Here's what I'm seeing:

<img src="https://user-images.githubusercontent.com/2040554/186671894-b93208d8-c9ed-4cfe-87e4-bc5b28569a88.gif" width="450">

2. The bottom tab bar for emoji categories does not show until I slide the sheet up to full height. Is it possible to have the category tabs visible while the bottom sheet is in it's smallest height as per design? See comparison below:

<table>
<tr>
<th>Designed</th>
<th>Implemented</th>
</tr>
<tr>
<td>
<img src="https://user-images.githubusercontent.com/2040554/186674807-85e6fb5c-9853-4402-b6ad-f26208c4ea3d.png">
</td>
<td>
<img src="https://user-images.githubusercontent.com/2040554/186673380-14322475-36b4-47d6-9fad-b71183756a2a.png">
</td>
</tr>
</table>

4. As @enahum mentioned, the emojis are not spaced/distributed properly to fill out the available width. They are packed too tightly together and have lots of extra space on the right side.(see comparison above) Also, each emoji should be contained within a 48x48 container to ensure proper tapping space and prevent tapping the wrong one.

<img width="394" alt="image" src="https://user-images.githubusercontent.com/2040554/186677974-2681871b-88d5-4952-a3da-99995f7a8b63.png">


6.  The section titles for 'Recently Used', 'Smileys & Emoticons', etc are using the wrong font, color/opacity and size. They should also be all caps. (see comparison above)

7. Are we excluding the [skin tone selector](https://www.figma.com/file/chu9P5rBtYutfobO0ly1wE/MM-22847-Mobile-Emoji-Picker?node-id=1316%3A50381) from this PR? I don't see that functionality anywhere.

7. The search bar area doesn't look quite right compared to the design. The padding around it is larger than designed and there should be a divider below it (see comparison above).

8. Agree with @enahum that tapping on categories is not very responsive. Switching feels quite delayed.

9. Also, the active state for the categories is not quite right. The container box is misaligned and there should not be a border on it. Also, the icons shift around when switching tabs.
![2022-08-25 09 26 40](https://user-images.githubusercontent.com/2040554/186677251-3aa5a9e4-eb33-41a0-bc80-cba66544b591.gif)

2022-08-27 23:08 UTC, vdanylov commented
> Thanks for the work on this @vdanylov. There are a few things I'd like to call out from a UX standpoint that we should resolve if possible. Let me know if you'd like to chat through any of these.
> 
> 1. The transition for showing the emoji picker bottom sheet is quite delayed and doesn't animate properly. It should be much more responsive and snappy. Can you refer to the other bottom sheets to see how it should animate on? Here's what I'm seeing:
> 
> ![](https://user-images.githubusercontent.com/2040554/186671894-b93208d8-c9ed-4cfe-87e4-bc5b28569a88.gif) [ ![186671894-b93208d8-c9ed-4cfe-87e4-bc5b28569a88.gif](https://user-images.githubusercontent.com/2040554/186671894-b93208d8-c9ed-4cfe-87e4-bc5b28569a88.gif) ](https://user-images.githubusercontent.com/2040554/186671894-b93208d8-c9ed-4cfe-87e4-bc5b28569a88.gif) [ ](https://user-images.githubusercontent.com/2040554/186671894-b93208d8-c9ed-4cfe-87e4-bc5b28569a88.gif)
> 
> 2. The bottom tab bar for emoji categories does not show until I slide the sheet up to full height. Is it possible to have the category tabs visible while the bottom sheet is in it's smallest height as per design? See comparison below:
> 
> Designed	Implemented
> ![](https://user-images.githubusercontent.com/2040554/186674807-85e6fb5c-9853-4402-b6ad-f26208c4ea3d.png)	![](https://user-images.githubusercontent.com/2040554/186673380-14322475-36b4-47d6-9fad-b71183756a2a.png)
> 4. As @enahum mentioned, the emojis are not spaced/distributed properly to fill out the available width. They are packed too tightly together and have lots of extra space on the right side.(see comparison above) Also, each emoji should be contained within a 48x48 container to ensure proper tapping space and prevent tapping the wrong one.
> 
> <img alt="image" width="394" src="https://user-images.githubusercontent.com/2040554/186677974-2681871b-88d5-4952-a3da-99995f7a8b63.png">
> 
> 6. The section titles for 'Recently Used', 'Smileys & Emoticons', etc are using the wrong font, color/opacity and size. They should also be all caps. (see comparison above)
> 7. Are we excluding the [skin tone selector](https://www.figma.com/file/chu9P5rBtYutfobO0ly1wE/MM-22847-Mobile-Emoji-Picker?node-id=1316%3A50381) from this PR? I don't see that functionality anywhere.
> 8. The search bar area doesn't look quite right compared to the design. The padding around it is larger than designed and there should be a divider below it (see comparison above).
> 9. Agree with @enahum that tapping on categories is not very responsive. Switching feels quite delayed.
> 10. Also, the active state for the categories is not quite right. The container box is misaligned and there should not be a border on it. Also, the icons shift around when switching tabs.
>     ![2022-08-25 09 26 40](https://user-images.githubusercontent.com/2040554/186677251-3aa5a9e4-eb33-41a0-bc80-cba66544b591.gif)
>           
>             [
>               
>                 ![2022-08-25 09 26 40](https://user-images.githubusercontent.com/2040554/186677251-3aa5a9e4-eb33-41a0-bc80-cba66544b591.gif)
>               
>             ](https://user-images.githubusercontent.com/2040554/186677251-3aa5a9e4-eb33-41a0-bc80-cba66544b591.gif)
>             
>             
>               
>                 
>                   
>                 
>                 
>                   
>                   
>                 
>               
>               [
>                 
>                   
>                 
>               ](https://user-images.githubusercontent.com/2040554/186677251-3aa5a9e4-eb33-41a0-bc80-cba66544b591.gif)
> 11. I also noticed that the categories bar in the tablet layout doesn't have the correct padding/spacing as per [the design](https://www.figma.com/file/chu9P5rBtYutfobO0ly1wE/MM-22847-Mobile-Emoji-Picker?node-id=1316%3A137904):
> 
> <img alt="image" width="395" src="https://user-images.githubusercontent.com/2040554/186684173-27ce3339-ba29-4115-ba36-6687b32bf8db.png">

Thank You for the review, I've fixed some issues and further work need some discussion

2022-08-27 23:09 UTC, vdanylov commented
@matthewbirtch Thank You for the review, I've fixed some issues and further work need some discussion.

2022-09-07 01:00 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2022-10-06 09:21 UTC, enahum commented
Closing this PR

2022-10-06 09:21 UTC, closed without merging