Use always first the local channels
mattermost/mattermost-mobile pull request #6594
Opened 2022-08-24 11:05 UTC by larkox

#### Summary
Always use autocomplete local channels, and then append the remote channels.

This may cause some jumping of the channels, but that should not be common, since the only channels that will pop up are the channels we are not a member of.

This is related to https://github.com/mattermost/mattermost-mobile/pull/6593/

Also added some fixes here and there, that may be shared with the other linked PR (I will leave the fixes here, and we will see which one merge first).

#### Ticket Link
None

#### Release Note
```release-note
Improve autocomplete channels behaviour
```

2022-08-29 17:37 UTC, jfrerich approved these changes
LGTM and thanks for the 1:1 walkthrough!

2022-09-12 14:53 UTC, enahum approved these changes

2022-09-12 14:53 UTC, enahum commented
@larkox needs conflict resolution

2022-09-14 18:05 UTC, larkox commented
Back to dev review, since I added several changes to fix some bugs with corner cases.

2022-09-15 07:30 UTC, avinashlng1080 approved these changes

2022-09-17 12:53 UTC, enahum commented on app/components/autocomplete/at_mention/at_mention.tsx
> +const searchGroups = async (serverUrl: string, matchTerm: string, useGroupMentions: boolean, isChannelConstrained: boolean, isTeamConstrained: boolean, channelId?: string, teamId?: string) => {
Should we move this one to remote actions?

2022-09-17 12:53 UTC, enahum commented on app/components/autocomplete/channel_mention/channel_mention.tsx
> +            const aDisplay = 'display_name' in a ? a.display_name : a.displayName;
I think there is a sorting function for this already created, does that one qork here?

2022-09-26 15:54 UTC, mattermod commented
Building app in separate branch.

2022-09-26 15:59 UTC, mattermod commented
Successfully building:  
https://circleci.com/gh/mattermost/mattermost-mobile/24904  
https://circleci.com/gh/mattermost/mattermost-mobile/24903

2022-09-26 16:36 UTC, mattermod commented
Artifact links:  
https://output.circle-artifacts.com/output/job/752f9f4f-1c0d-4818-aa79-a2a76262c52a/artifacts/0/tmp/artifacts/Mattermost_Beta.ipa  
https://output.circle-artifacts.com/output/job/7322f86c-7e15-4d4c-9096-97687ea5882d/artifacts/0/tmp/artifacts/Mattermost_Beta.apk

2022-10-03 16:13 UTC, mattermod commented
Building app in separate branch.

2022-10-03 16:17 UTC, mattermod commented
Successfully building:  
https://circleci.com/gh/mattermost/mattermost-mobile/24942  
https://circleci.com/gh/mattermost/mattermost-mobile/24941

2022-10-03 22:02 UTC, enahum commented
@josephbaylon build ready

2022-10-03 22:26 UTC, josephbaylon requested changes
@larkox
1. Android works as expected. At-mention autocomplete now closes once user taps on an option. Also, autocomplete stays open as long as long as it matches a pattern.
2. iOS closes at-mention autocomplete once user taps on an option. However, when user types in characters which should keep the autocomplete open, the autocomplete closes and never shows up again. I couldn't figure out the pattern when it closes but at least on 2 occasions, the autocomplete closes on 2nd character and on third character (see images below).
![atmention-2-chars](https://user-images.githubusercontent.com/487991/193696767-514deae4-f9f4-47c2-a1fb-ef01f4c5bd5b.png)
![atmention-3-chars](https://user-images.githubusercontent.com/487991/193696769-d01c41fd-34be-4066-b83e-e91fccaecd75.png)

2022-10-04 14:27 UTC, larkox commented
@josephbaylon What you are experiencing seems out of the ordinary. Both apps should work the same.

What I am experiencing in my local is the server not returning the list of users (happens in my local, but not in community). Since users is still using the remote results, the behaviour is "correct" on the client: the server says there are no more users, so I show no more users. I will check if I find why the server is behaving this way.

2022-10-05 14:39 UTC, jfrerich approved these changes
I only have 1 nit after looking at the new code from my last review.

2022-10-05 14:39 UTC, jfrerich commented on app/components/autocomplete/at_mention/at_mention.tsx
> +            // If the channel is constrained, we only show groups for that channel
Something like will look less likely to fallthrough and possibly hit multiple if statements.

2022-10-21 08:51 UTC, josephbaylon commented
@larkox Did anything change? I don't think the issue I posted above has been resolved yet.

2022-10-21 10:11 UTC, larkox commented
@josephbaylon Sorry! I thought the issue was only on the server side, because what I was receiving was different the last time I tested it, but now I am seeing what you described. Taking a look right now.

2022-10-21 11:13 UTC, larkox commented
@josephbaylon Now should be ready. One piece of code apparently unneeded was creating a race condition.

2022-10-21 16:56 UTC, mattermod commented
Building app in separate branch.

2022-10-21 17:00 UTC, mattermod commented
Successfully building:  
https://circleci.com/gh/mattermost/mattermost-mobile/25341  
https://circleci.com/gh/mattermost/mattermost-mobile/25340

2022-10-21 17:25 UTC, mattermod commented
Artifact links:  
https://output.circle-artifacts.com/output/job/52b5fc1d-0458-48a2-ad50-cc216395c633/artifacts/0/tmp/artifacts/Mattermost_Beta.ipa  
https://output.circle-artifacts.com/output/job/31871533-8f47-4d3a-b677-338d0e899af8/artifacts/0/tmp/artifacts/Mattermost_Beta.apk

2022-10-21 18:06 UTC, josephbaylon approved these changes
LGTM. Issues found are now fixed. Also PR fixes issue of autocomplete not getting closed after user taps on item.

2022-10-24 08:55 UTC, merged