Update README.md
mattermost/mattermost-mobile pull request #6701
Opened 2022-10-25 22:26 UTC by amyblais

2022-10-25 22:28 UTC, amyblais commented
/release-note-none

2022-10-28 12:31 UTC, enahum requested changes
this needs to update the code as well

files:
- `app/constants/calls.ts`
- `app/contants/view.js` -> RequiredServer values.

2022-10-28 12:45 UTC, enahum approved these changes

2022-10-28 14:11 UTC, streamer45 approved these changes

2022-11-02 07:33 UTC, enahum approved these changes

2022-11-02 07:34 UTC, merged

2022-11-02 07:34 UTC, mattermod commented
Cherry pick is scheduled.