New UI for Emoji picker
mattermost/mattermost-mobile pull request #6933
Opened 2023-01-05 16:22 UTC by enahum

#### Summary
This moves the emoji picker as a bottom sheet

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-22847

#### Release Note
```release-note
NONE
```

2023-01-05 16:34 UTC, mattermod commented
Successfully building:  
https://circleci.com/gh/mattermost/mattermost-mobile/27253  
https://circleci.com/gh/mattermost/mattermost-mobile/27252

2023-01-05 17:03 UTC, avinashlng1080 approved these changes

2023-01-05 17:05 UTC, mattermod commented
Artifact links:  
https://output.circle-artifacts.com/output/job/ff9edc39-5345-4d62-82bc-8b5218230dfd/artifacts/0/tmp/artifacts/Mattermost_Beta.ipa  
https://output.circle-artifacts.com/output/job/ab7897da-b333-4711-9824-fee854407ee6/artifacts/0/tmp/artifacts/Mattermost_Beta.apk

2023-01-05 18:26 UTC, jfrerich approved these changes
LGTM!  I have a couple of non-block NITs.

2023-01-05 18:26 UTC, jfrerich commented on app/screens/emoji_picker/index.tsx
> +import EmojiSectionBar from './picker/footer';
```suggestion
import PickerFooter from './picker/footer';
```
Match the component name inside `picker/footer`

2023-01-05 18:26 UTC, jfrerich commented on app/screens/emoji_picker/picker/emoji_category_bar/index.tsx
> +const EmojiSectionBar = ({onSelect}: Props) => {
```suggestion
const EmojiCategoryBar = ({onSelect}: Props) => {
```

2023-01-05 18:26 UTC, jfrerich commented on app/screens/emoji_picker/picker/header/skintone_selector/tooltip.tsx
> +                    defaultMessage='You can now choose the skin tone you prefer to use for your emojis.'
I thought CI would have caught this, but didn't.  Need to run `npm run i18n-extract` and add a couple from this file.

2023-01-05 18:41 UTC, enahum commented on app/screens/bottom_sheet/index.tsx
> +    snapPoints = [1, '50%', '80%'],
not really.. in any case you can leave out the `snapPoints` prop and it will use this as the default.

2023-01-06 17:06 UTC, matthewbirtch commented
@enahum I just tested the build on my phone and as soon as I open the emoji picker bottom sheet nothing seems to be tappable and I can't seem to close the bottom sheet either. I have to restart the app to get out of that state. And restarting doesn't solve anything as the bug is reproducing every time for me

2023-01-06 17:08 UTC, enahum commented
@matthewbirtch you did not see the tooltip?

2023-01-06 17:43 UTC, matthewbirtch commented
> @matthewbirtch you did not see the tooltip?

No, no tooltip

2023-01-06 17:44 UTC, enahum commented
> > @matthewbirtch you did not see the tooltip?
> 
> 
> 
> No, no tooltip

Yeah that seems to be the cause of the block.. I'll check it on monday

2023-01-07 09:44 UTC, enahum commented
@matthewbirtch I just installed the iOS from the link found in the channel and it seems to be working just fine on my iphone 12

2023-01-07 12:54 UTC, matthewbirtch commented
Ok, I will reinstall and try again @enahum

2023-01-09 14:47 UTC, matthewbirtch requested changes
After re-installing, it seems to be working now for me. I see the tooltip and the emoji picker is fully functional. 

Now that I can review it, it's working great. Nice work @enahum. I have a few fairly minor changes to request:

1. The shadow on the tooltip isn't quite right. It's too dark. I wanted to play with the values, but don't see which file this shadow is applied. I looked in `screens/emoji_picker/picker/header/skinton_selector/tooltip.tst`, but I don't see the shadow style applied there anywhere.
2. In the tooltip, the padding inside the container seems bigger than designed. The inspector is showing 8px extra padding all around, but I can't figure out where that's being applied or how to remove that.
3. When choosing a different skin tone, there seems to be a bit of a delay before applying the change. It's more noticeable on the simulator, but it does seem to be slightly delayed on my device as well.
4. The skin tone emoji that appears next to the search bar seems like it's sitting a bit too low - not quite vertically aligned. Can we nude it up a few pixels to fix that?
5. The font for the category section titles need to be updated with the following changes
```
...typography('Heading', 75, 'SemiBold'),
textTransform: 'uppercase',
```
6. Right now, the grid isn't quite aligned perfectly. Can we make the `EMOJI_SIZE = 34`? This seems to make things align a bit better. Then if we can make the hitslop on each emoji 44x44 (or 48x48 if we can make that work)?
7. When I attempt to open the emoji picker, there seems to be a significant delay before it actually opens up. It's more noticeable in the simulator, but it's definitely noticeable on my device as well. Any way we can reduce the delay before the emoji picker bottom sheet opens up? 
8. On tablet, I wonder if we can increase the number of emojis that fit in a row? We can probably fit 9 wide on tablet as opposed to 7 on mobile. Is that doable? 
9. For the category bar on the bottom, can we reduce the padding on the left and right to 12 instead of 20?
10. Also, the icons for the category bar are a bit larger than designed and makes things feel a bit too crowded. Can we change the icon size to 20 instead of 24? Can we also adjust the  opacity on the icons to 0.56 for the non-selected state?

2023-01-10 15:51 UTC, enahum commented
@matthewbirtch 

> 1. The shadow on the tooltip isn't quite right. It's too dark. I wanted to play with the values, but don't see which file this shadow is applied. I looked in `screens/emoji_picker/picker/header/skinton_selector/tooltip.tst`, but I don't see the shadow style applied there anywhere.

Done. You can now find the shadow style in SkinToneSelector component

> 2. In the tooltip, the padding inside the container seems bigger than designed. The inspector is showing 8px extra padding all around, but I can't figure out where that's being applied or how to remove that.

Done. in the SkinToneSelector I've removed the padding added by the library that was of 8px as you mention.

> 3. When choosing a different skin tone, there seems to be a bit of a delay before applying the change. It's more noticeable on the simulator, but it does seem to be slightly delayed on my device as well.

Done.

> 4. The skin tone emoji that appears next to the search bar seems like it's sitting a bit too low - not quite vertically aligned. Can we nude it up a few pixels to fix that?

Done.

> 5. The font for the category section titles need to be updated with the following changes
> 
> ```
> ...typography('Heading', 75, 'SemiBold'),
> textTransform: 'uppercase',
> ```
> 

Done.

> 6. Right now, the grid isn't quite aligned perfectly. Can we make the `EMOJI_SIZE = 34`? This seems to make things align a bit better. Then if we can make the hitslop on each emoji 44x44 (or 48x48 if we can make that work)?

Done.

> 7. When I attempt to open the emoji picker, there seems to be a significant delay before it actually opens up. It's more noticeable in the simulator, but it's definitely noticeable on my device as well. Any way we can reduce the delay before the emoji picker bottom sheet opens up?

I couldn't do much here, yes on the sim takes forever but not on a release build (none developer mode) as it needs to render to many items on screen when it mounts

> 8. On tablet, I wonder if we can increase the number of emojis that fit in a row? We can probably fit 9 wide on tablet as opposed to 7 on mobile. Is that doable?

Done, rendering 9 emojis per row on tablets.

> 9. For the category bar on the bottom, can we reduce the padding on the left and right to 12 instead of 20?

Done.

> 10. Also, the icons for the category bar are a bit larger than designed and makes things feel a bit too crowded. Can we change the icon size to 20 instead of 24? Can we also adjust the  opacity on the icons to 0.56 for the non-selected state?

Done.

2023-01-10 16:58 UTC, mattermost-build commented
Building app in separate branch.

2023-01-10 17:02 UTC, mattermost-build commented
Successfully building:  
https://circleci.com/gh/mattermost/mattermost-mobile/27333  
https://circleci.com/gh/mattermost/mattermost-mobile/27332

2023-01-10 17:34 UTC, mattermost-build commented
Artifact links:  
https://output.circle-artifacts.com/output/job/4785734d-5ca8-423b-8bf1-c2b598b9cb05/artifacts/0/tmp/artifacts/Mattermost_Beta.ipa  
https://output.circle-artifacts.com/output/job/2832014b-179e-4d74-8c90-85711dfacc75/artifacts/0/tmp/artifacts/Mattermost_Beta.apk

2023-01-10 23:31 UTC, matthewbirtch requested changes
Awesome work @enahum. You resolved all the issues I identified earlier. I just noticed two other small things though:

1. When I open the skin tone selector and close it, the header height seems to change which causes the content below to jump up and down a little bit.
    ![2023-01-10 18 27 50](https://user-images.githubusercontent.com/2040554/211683876-9ae5a153-a707-4119-9d1b-941077c2b013.gif)

2. The scroll bar overlaps the emojis - is there a way to move it to the right in to the margin?
    <img width="590" alt="Screenshot 2023-01-10 at 6 29 30 PM" src="https://user-images.githubusercontent.com/2040554/211683838-d3fa8429-63e2-4fd8-8718-fe7b26b5b067.png">

2023-01-11 06:00 UTC, mattermost-build commented
Building app in separate branch.

2023-01-11 06:05 UTC, mattermost-build commented
Successfully building:  
https://circleci.com/gh/mattermost/mattermost-mobile/27340  
https://circleci.com/gh/mattermost/mattermost-mobile/27339

2023-01-11 06:29 UTC, mattermost-build commented
Artifact links:  
https://output.circle-artifacts.com/output/job/b6410bcb-36e9-4be1-8991-640b1c8a1192/artifacts/0/tmp/artifacts/Mattermost_Beta.apk  
https://output.circle-artifacts.com/output/job/1f642eb9-baf1-43f2-8709-04c16ec49532/artifacts/0/tmp/artifacts/Mattermost_Beta.ipa

2023-01-11 13:48 UTC, matthewbirtch commented
> 2\. The scroll bar overlaps the emojis - is there a way to move it to the right in to the margin?
>     <img alt="Screenshot 2023-01-10 at 6 29 30 PM" width="590" src="https://user-images.githubusercontent.com/2040554/211683838-d3fa8429-63e2-4fd8-8718-fe7b26b5b067.png">

@enahum I see the scrollbar position has slightly changed, but still feel tight and there is lots of white space on the right side to move it further. This is non-blocking for me though, so I'm going to approve this and we can fix that in a follow-up

2023-01-11 13:48 UTC, matthewbirtch approved these changes

2023-01-12 11:38 UTC, merged

2023-02-02 09:00 UTC, enahum commented
cherry-pick to 2.0 done