[MM-45625] Do not enable the Keyboard Search button unless there is text in the search bar
mattermost/mattermost-mobile pull request #6957
Opened 2023-01-12 02:46 UTC by jfrerich

#### Summary
This PR disables the keyboard search button until there is text in the search bar text input.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-45625

#### Checklist

- [ ] Added or updated unit tests (required for all new features)
- [ ] Has UI changes
- [ ] Includes text changes and localization file updates
- [ ] Have tested against the 5 core themes to ensure consistency between them.

#### Device Information
This PR was tested on: 

#### Screenshots

#### Release Note

```release-note

```

2023-01-12 06:54 UTC, enahum approved these changes

2023-01-12 06:56 UTC, enahum requested changes
This applies to all the search bars in the app instead of only applying in the search screen as in the ticket

2023-01-12 06:58 UTC, enahum commented
Unless we want to apply this to every search bar changes should be made. If we **do** want this to apply to all search bars, then I'll approve it

2023-01-12 09:05 UTC, larkox approved these changes
Apart of enahum's comments, LGTM

2023-01-13 13:15 UTC, jfrerich commented on app/screens/home/search/search.tsx
> +                enablesReturnKeyAutomatically={true}
I've added the new prop at this level now.

2023-01-13 13:19 UTC, jfrerich commented
> Unless we want to apply this to every search bar changes should be made. If we **do** want this to apply to all search bars, then I'll approve it
@enahum, I moved the prop to the Search Screen level just to be safe. 

I also sorted all the component props alphabetically because I didn't do that way back when I did the search screen.

I tested how `Find Channels` handles the empty search and it closes the keyboard if you search and a search term does not exist.  I propose to create a ticket if we want to have UX review all the behaviors or empty search terms across the product.

2023-01-13 13:25 UTC, enahum commented
> > Unless we want to apply this to every search bar changes should be made. If we **do** want this to apply to all search bars, then I'll approve it
> > @enahum, I moved the prop to the Search Screen level just to be safe.
> 
> I also sorted all the component props alphabetically because I didn't do that way back when I did the search screen.
> 
> I tested how `Find Channels` handles the empty search and it closes the keyboard if you search and a search term does not exist. I propose to create a ticket if we want to have UX review all the behaviors or empty search terms across the product.

Then I cannot approve this PR

2023-01-13 15:05 UTC, matthewbirtch commented
> Unless we want to apply this to every search bar changes should be made. If we **do** want this to apply to all search bars, then I'll approve it

I would think that this _should_ apply to every instance of the search bar. I can't think of a use case for enabling the search button when the field is empty.

2023-01-21 00:46 UTC, mattermost-build commented
Building app in separate branch.

2023-01-21 00:51 UTC, mattermost-build commented
Successfully building:  
https://circleci.com/gh/mattermost/mattermost-mobile/27553  
https://circleci.com/gh/mattermost/mattermost-mobile/27552

2023-01-21 01:15 UTC, mattermost-build commented
Artifact links:  
https://output.circle-artifacts.com/output/job/cecebe2e-f612-4394-9795-7c87155d63a3/artifacts/0/tmp/artifacts/Mattermost_Beta.apk  
https://output.circle-artifacts.com/output/job/32e474b5-4811-4d18-bc66-05732eeff135/artifacts/0/tmp/artifacts/Mattermost_Beta.ipa

2023-01-24 21:45 UTC, jgilliam17 commented
Thanks @jfrerich 
iPhone shows disabled Enter button when search bar is empty, but on iPad I can still tap Enter.
On Android, Enter also seems enabled.
![IMG_5D9DFF655029-1](https://user-images.githubusercontent.com/52937121/214427028-88c5fe36-06c1-4b43-9232-9a3873d66e87.jpeg)
<img width="367" alt="Screen Shot 2023-01-24 at 4 42 12 PM" src="https://user-images.githubusercontent.com/52937121/214427447-6d4c3371-c9ff-4da3-a06e-a8cc6c51cc97.png">
![IMG_6C7B80A35906-1](https://user-images.githubusercontent.com/52937121/214427653-88cc39c9-e750-47ec-bf18-230149e6801b.jpeg)

2023-02-15 07:05 UTC, enahum commented
closing for now

2023-02-15 07:05 UTC, closed without merging