Translations update from Mattermost Weblate
mattermost/mattermost-mobile pull request #7058
Opened 2023-01-30 15:23 UTC by weblate

Translations update from [Mattermost Weblate](https://translate.mattermost.com) for [mattermost-languages-shipped/mattermost-mobile-v2](https://translate.mattermost.com/projects/mattermost/mattermost-mobile-v2/).

Current translation status:

![Weblate translation status](https://translate.mattermost.com/widgets/mattermost/-/mattermost-mobile-v2/horizontal-auto.svg)

2023-01-30 15:23 UTC, mattermost-build commented
Hello @weblate,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2023-01-30 16:31 UTC, Willyfrog commented on assets/base/i18n/en.json
> +    "about.teamEditionLearn": "Join the Mattermost community a",
here is the culprit and it is even wrong, we should not introduce this

2023-01-30 16:46 UTC, Willyfrog requested changes
there are changes in the english version which will lead to conflicts, also the change done to that file is a typo

2023-01-31 09:19 UTC, m1lt0n commented on assets/base/i18n/en.json
> +    "about.date": "Build Date:",
Yes, exactly

2023-01-31 09:24 UTC, m1lt0n commented
/release-note-none

2023-01-31 10:00 UTC, m1lt0n commented on assets/base/i18n/en.json
> +    "about.date": "Build Date:",
@Willyfrog I've pushed a commit (from weblate) to fix the only different string. The indentation seems something that weblate did due to the change in the en.json file, if you check the language files, they have an indentation similar to the one of the en file. I think it's good to go now right?

2023-01-31 10:25 UTC, m1lt0n commented on assets/base/i18n/en.json
> +    "about.date": "Build Date:",
Also, checking the settings of the mobile project in weblate, it allowed editing the source file, so I unchecked this setting (as it is unchecked for server etc), so no more editing from translators will be possible.

2023-01-31 10:30 UTC, m1lt0n approved these changes

2023-01-31 10:31 UTC, Willyfrog approved these changes

2023-01-31 10:31 UTC, merged