fix: reset password bug
mattermost/mattermost-mobile pull request #7135
Opened 2023-02-15 17:37 UTC by Sudhanva-Nadiger

#### Summary
- Users on both the Mattermost public version and beta version are receiving an error message: "Unable to reset your password". However, at least for the beta version, the email sends successfuly but the error is still shown. On the mobile web app version and on desktop, no issue is present.

#### Ticket Link
- https://mattermost.atlassian.net/browse/MM-50501

#### Checklist

- [ ] Added or updated unit tests (required for all new features)
- [ ] Has UI changes
- [ ] Includes text changes and localization file updates
- [ ] Have tested against the 5 core themes to ensure consistency between them.

#### Device Information
This PR was tested on:  Realme 6 pro

#### Screenshots
https://user-images.githubusercontent.com/93595710/219104712-5a2205e9-7820-47e8-8e27-d0907279598b.mp4

#### Release Note

```release-note
Fix "Unable to reset your password"
```

2023-02-15 17:37 UTC, mattermost-build commented
Hello @Sudhanva-Nadiger,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2023-02-15 17:58 UTC, enahum approved these changes

2023-02-16 09:08 UTC, larkox requested changes
Great work! Just one minor change.

2023-02-16 09:08 UTC, larkox commented on app/actions/remote/session.ts
> +        data: response.status,
If what we are returning and checking is the status, I would also change the name of the variable, as:
```suggestion
        status: response.status,
```

2023-02-16 09:25 UTC, larkox approved these changes

2023-02-16 09:26 UTC, enahum approved these changes

2023-02-16 10:09 UTC, merged

2023-02-16 10:13 UTC, Sudhanva-Nadiger commented
Thanks @enahum and @larkox, It was my first contribution to matter most, I am very happy, Looking forward to learn contribute more in future 🤍

2023-02-16 10:16 UTC, enahum commented
Nicely done @Sudhanva-Nadiger is great to have you as a contributor of Mattermost. yay!!!