Updated onboarding text
mattermost/mattermost-mobile pull request #7138
Opened 2023-02-15 21:14 UTC by cwarnermm

#### Summary
Clarified onboarding text for new users.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-46606

#### Checklist
- [ ] Added or updated unit tests (required for all new features)
- [ ] Has UI changes
- [X] Includes text changes and localization file updates
- [ ] Have tested against the 5 core themes to ensure consistency between them.

#### Release Note

```release-note
NONE
```

2023-02-15 21:27 UTC, enahum requested changes

2023-02-15 21:36 UTC, enahum approved these changes

2023-02-16 13:11 UTC, saturninoabril approved these changes
Thanks Carrie! LGTM.

2023-02-16 13:15 UTC, saturninoabril commented on assets/base/i18n/en.json
> +  "mobile.components.select_server_view.msg_description": "A server is your team's communication hub accessed using a unique URL",
Hello @cwarnermm, I just noticed from the ticket that the new description has period (.). Might not be necessary but mentioning here.

Feel free to merge anytime.

2023-02-16 13:44 UTC, cwarnermm commented on assets/base/i18n/en.json
> +  "mobile.components.select_server_view.msg_description": "A server is your team's communication hub accessed using a unique URL",
Thanks, @saturninoabril! You have a great eye for detail :) I intentionally omitted the period feeling that it wouldn't add value based on how this text displays in-product.

2023-02-16 13:45 UTC, cwarnermm commented
@enahum - Feel free to merge this PR whenever it's convenient for you.

2023-02-16 13:55 UTC, merged