Detox: Android fix MM-T4728_2 - should match elements on channel list…
mattermost/mattermost-mobile pull request #7156
Opened 2023-02-23 15:44 UTC by metanerd

… screen

#### Summary

![Screenshot from 2023-02-23 16-39-44](https://user-images.githubusercontent.com/9913860/220957306-6b0bcbba-3ca1-4f44-8caf-0abf019454ce.png)

#### Ticket Link

#### Checklist

- [ ] Added or updated unit tests (required for all new features)
- [ ] Has UI changes
- [ ] Includes text changes and localization file updates
- [ ] Have tested against the 5 core themes to ensure consistency between them.

#### Device Information
This PR was tested on: 

#### Screenshots

#### Release Note

```release-note
NONE
```

2023-02-27 11:08 UTC, saturninoabril requested changes

2023-02-27 11:52 UTC, saturninoabril commented
/e2e-test

2023-02-27 11:52 UTC, mattermost-build commented
Successfully triggered e2e mobile testing!
https://git.internal.mattermost.com/qa/mobile-e2e-testing/-/pipelines/307463

2023-02-28 08:58 UTC, saturninoabril approved these changes
Thanks @metanerd, LGTM.

Looking at the results, [iOS all 9/9 passed](https://mattermost-detox-report.s3.amazonaws.com/307463-7856e59-mobile-pr-7156/jest-stare/ios-report.html) in this test file but [Android has 1/9 failed](https://mattermost-detox-report.s3.amazonaws.com/307463-7856e59-mobile-pr-7156/jest-stare/android-report.html) test. The flaky test might be related to a [build/test being in debug mode](https://git.internal.mattermost.com/qa/mobile-e2e-testing/-/blob/e2e-pr/scripts/run.sh#L43-53). How about try using the release mode: `npm run e2e:android-build-release` then `npm run e2e:android-test-release`?

Approving since those are not related to the change.

2023-03-07 20:25 UTC, furqanmlk approved these changes
Thanks, @metanerd 

Finally, I was able to run tests

![image](https://user-images.githubusercontent.com/6909890/223544172-3c05d052-cb61-46eb-b594-54cfa874c552.png)

2023-03-07 20:26 UTC, merged