Detox: Android - fix smoke server login test
mattermost/mattermost-mobile pull request #7157
Opened 2023-02-23 17:50 UTC by metanerd

#### Summary

![Screenshot from 2023-02-23 18-48-22](https://user-images.githubusercontent.com/9913860/220988663-86d2bf74-faa0-4f25-b81f-bbd819cb8db5.png)

#### Ticket Link

#### Checklist

- [ ] Added or updated unit tests (required for all new features)
- [ ] Has UI changes
- [ ] Includes text changes and localization file updates
- [ ] Have tested against the 5 core themes to ensure consistency between them.

#### Device Information
This PR was tested on: 

#### Screenshots

#### Release Note

```release-note
NONE
```

2023-02-27 09:17 UTC, larkox approved these changes

2023-02-27 10:32 UTC, saturninoabril requested changes

2023-02-27 10:32 UTC, saturninoabril commented on detox/e2e/test/smoke_test/server_login.e2e.ts
> +        await ServerListScreen.serverListTitle.swipe('up', 'fast', 0.1, 0.5, 0.3);
The change here and the other one failed on me in iOS due to bottom sheet not being pulled up fully causing the "Log Out" button to be partially covered (per Detox visibility check).
<img width="975" alt="Screenshot 2023-02-27 at 6 11 45 PM" src="https://user-images.githubusercontent.com/5334504/221539222-9d308736-c820-47cb-beaa-27238ec5a1ef.png">
<img width="416" alt="Screenshot 2023-02-27 at 6 11 29 PM" src="https://user-images.githubusercontent.com/5334504/221540197-18fe576e-c5c2-4c0c-bdfb-5457c93be79d.png">

However, the original code passed in iOS.
<img width="925" alt="Screenshot 2023-02-27 at 6 25 31 PM" src="https://user-images.githubusercontent.com/5334504/221539982-95d6c581-a28e-4105-92f4-ec61f7a4eca3.png">

How about change the swipe up action to Android only?

2023-02-27 11:03 UTC, saturninoabril approved these changes
Thanks @metanerd, LGTM.

2023-02-28 09:39 UTC, larkox commented
/update-branch

2023-02-28 09:43 UTC, larkox commented
@metanerd it seems you have some lint errors

2023-02-28 16:14 UTC, merged