Update members count on remove users
mattermost/mattermost-mobile pull request #7222
Opened 2023-03-20 12:50 UTC by larkox

#### Summary
When a member was removed from the channel, we refetched the channel stats, but before actually removing the user, so the value would stay the same until we refetch it again.

This makes sure we fetch the channel stats only after the user is removed.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-50289

#### Release Note
```release-note
Members count gets updated after removing users.
```

2023-03-20 12:52 UTC, enahum requested changes

2023-03-20 12:52 UTC, enahum commented on app/components/channel_actions/manage_members_label/manage_members_label.tsx
> +            () => fetchChannelStats(serverUrl, channelId, false),
this should only be called when the `removeMemberFromChannel` does not return an error.

2023-03-21 09:09 UTC, M-ZubairAhmed approved these changes

2023-03-21 10:16 UTC, larkox commented on app/components/channel_actions/manage_members_label/manage_members_label.tsx
> +        removeMemberFromChannel(serverUrl, channelId, userId).then(
Mainly is me being conservative on the current behavior.

If we use await, we would be waiting for remove channel to be handled (remote call, so may take some time depending on the connection) before closing the screen, which will affect the perceived performance.

We could also move it to the end of the function to use await, but I preferred keeping the order. 0/5 on the best approach.

2023-03-21 11:32 UTC, enahum approved these changes

2023-03-29 21:59 UTC, furqanmlk approved these changes
Thanks @larkox 
Working as expected.

https://user-images.githubusercontent.com/6909890/228677108-656b04f9-546c-4bfc-b97c-e02ac07f6df2.mp4

2023-03-30 09:10 UTC, merged

2023-03-30 09:10 UTC, mattermost-build commented
Cherry pick is scheduled.