MM-49540: drafts migration adding metadata
mattermost/mattermost-mobile pull request #7240
Opened 2023-03-29 18:15 UTC by koox00

#### Summary
Adds a drafts table migration adding the column "metadata". This column is going to be primarily used to store the draft's metadata priority field.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-49540

#### Checklist

- [ ] Added or updated unit tests (required for all new features)
- [ ] Has UI changes
- [ ] Includes text changes and localization file updates
- [ ] Have tested against the 5 core themes to ensure consistency between them.

#### Device Information
This PR was tested on: 

#### Release Note

```release-note
NONE
```

2023-03-29 18:17 UTC, enahum requested changes

2023-03-29 18:17 UTC, enahum commented on app/database/migration/server/index.ts
> +        toVersion: 3,
```suggestion
        toVersion: 2,
```

no need to bump as the previous migration has not been shipped

2023-03-29 18:17 UTC, enahum commented on app/database/schema/server/test.ts
> +            version: 3,
```suggestion
            version: 2,
```

2023-03-29 18:18 UTC, koox00 commented
> no need to bump as the previous migration has not been shipped

@enahum should I add the migration in the steps array of migration 2?

2023-03-29 18:18 UTC, enahum commented
Also missing the changes in `types/database/models/servers/draft.ts`

2023-03-29 19:02 UTC, enahum approved these changes

2023-03-30 09:23 UTC, larkox approved these changes

2023-03-30 09:42 UTC, merged