Update NOTICE.txt
mattermost/mattermost-mobile pull request #7241
Opened 2023-03-29 22:52 UTC by amyblais

2023-03-29 22:52 UTC, amyblais commented
/release-note-none

2023-03-30 13:24 UTC, cpoile approved these changes
Probably should point to the repo that's being included. I'm 0/5 for calling it `mattermost/calls-common` rather than `@mattermost/calls` in the `NOTICE.txt`.

Thanks Amy!

2023-03-30 13:24 UTC, cpoile commented on NOTICE.txt
> +  * https://github.com/mattermost/mattermost-plugin-calls
```suggestion
  * https://github.com/mattermost/calls-common
```

2023-03-30 13:28 UTC, enahum commented
> Probably should point to the repo that's being included. I'm 0/5 for calling it `mattermost/calls-common` rather than `@mattermost/calls` in the `NOTICE.txt`.
> 
> 
> 
> Thanks Amy!

This means that the package name should also change

2023-03-30 13:30 UTC, enahum requested changes

2023-03-30 14:30 UTC, cpoile commented on NOTICE.txt
> +  * https://github.com/mattermost/calls-common
@enahum I'm not sure what you mean? It does (you can try it)

2023-03-30 14:51 UTC, cpoile approved these changes

2023-03-30 16:54 UTC, merged

2023-03-30 16:54 UTC, mattermost-build commented
Cherry pick is scheduled.