[MM-42565] Toast - Follow/Unfollow thread with undo functionality
mattermost/mattermost-mobile pull request #7267
Opened 2023-04-04 12:22 UTC by tanmaythole

#### Summary

This PR adds the snack bar whenever the user follows/unfollows a thread. On top of that, the user is able to undo the previous action.

#### Ticket Link

https://github.com/mattermost/mattermost-server/issues/21241

#### Checklist

- [ ] Added or updated unit tests (required for all new features)
- [X] Has UI changes
- [X] Includes text changes and localization file updates
- [X] Have tested against the 5 core themes to ensure consistency between them.

#### Device Information
This PR was tested on: Android 12 - One UI Core 4.1

#### Screenshots

https://user-images.githubusercontent.com/72058456/229788750-293e448c-7096-4637-ab03-60af9882c530.mp4

#### Release Note

```release-note
Users can follow or unfollow a thread and undo the action if needed.
```

2023-04-04 16:25 UTC, enahum requested changes
two minor comments, other than that LGTM

2023-04-04 16:46 UTC, tanmaythole commented on app/actions/remote/thread.ts
> +import {showThreadFollowingSnackbar} from '@app/utils/snack_bar';
Done 👍🏻

2023-04-04 16:46 UTC, tanmaythole commented on app/actions/remote/thread.ts
> +export const updateThreadFollowing = async (serverUrl: string, teamId: string, threadId: string, state: boolean, showSnackBar = false) => {
Done 👍🏻

2023-04-04 16:49 UTC, enahum approved these changes

2023-04-04 16:49 UTC, enahum commented
@tanmaythole this file needs changing app/screens/thread/thread_follow_button/thread_follow_button.tsx:59:9

2023-04-04 17:11 UTC, enahum submitted a review, later dismissed

2023-04-04 17:45 UTC, matthewbirtch commented
> Do we not require a snack bar in the thread screen after following/unfollowing?
>> Do we? that would be odd to me, but I'll defer to @matthewbirtch to answer that question, for now just set it to false as that is how it used to be even after you changes.

I don't think we do since the follow/unfollow button has a visible change

2023-04-04 17:45 UTC, mattermost-build commented
Building app in separate branch.

2023-04-04 17:50 UTC, mattermost-build commented
Successfully building:  
https://circleci.com/gh/mattermost/mattermost-mobile/28619  
https://circleci.com/gh/mattermost/mattermost-mobile/28618

2023-04-04 18:15 UTC, mattermost-build commented
Artifact links:  
https://output.circle-artifacts.com/output/job/ebf785f0-1717-4e8e-a512-eb1cd21bc927/artifacts/0/tmp/artifacts/Mattermost_Beta.ipa  
https://output.circle-artifacts.com/output/job/4fd39386-07db-4ef3-80c5-8171e70b711f/artifacts/0/tmp/artifacts/Mattermost_Beta.apk

2023-04-04 23:10 UTC, enahum commented
> Looks good @tanmaythole. The only thing I notice is that the `Undo` button is too close to the right edge of the toast. Can you add 6 padding on the right side of the `Undo` button so there is a bit more breathing room on the right side of the toast?
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/2040554/229926582-aea0f146-5d97-4b69-9699-ce896de6b891.png)
> 
> 

That would affect all snackbars with undo, is that expected?

2023-04-06 00:28 UTC, matthewbirtch commented
> > Looks good @tanmaythole. The only thing I notice is that the `Undo` button is too close to the right edge of the toast. Can you add 6 padding on the right side of the `Undo` button so there is a bit more breathing room on the right side of the toast?
> > ![image](https://user-images.githubusercontent.com/2040554/229926582-aea0f146-5d97-4b69-9699-ce896de6b891.png)
> 
> That would affect all snackbars with undo, is that expected?

Yes @enahum. I'm not sure if the position of the undo here has changed or if it just wasn't noticed before, but it's too close to the edge

2023-04-06 21:42 UTC, matthewbirtch approved these changes
Looks good to me!

2023-04-14 14:01 UTC, enahum approved these changes

2023-04-14 14:07 UTC, enahum commented
@M-ZubairAhmed can you review this PR, I would like to include this in today's beta build.

2023-04-14 15:43 UTC, M-ZubairAhmed approved these changes

2023-04-14 16:28 UTC, merged