Fixed Interactive dialog radio buttons style
mattermost/mattermost-mobile pull request #7331
Opened 2023-05-05 12:34 UTC by nixusUM

#### Summary

#### Ticket Link

#### Checklist

- [ ] Added or updated unit tests (required for all new features)
- [x] Has UI changes
- [ ] Includes text changes and localization file updates
- [ ] Have tested against the 5 core themes to ensure consistency between them.

#### Device Information
This PR was tested on: 

#### Screenshots

2023-05-05 12:34 UTC, mattermost-build commented
Hello @nixusUM,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

Per the [Mattermost Contribution Guide](https://developers.mattermost.com/contribute/getting-started/), we need to add you to the list of [approved contributors](https://docs.google.com/spreadsheets/d/1NTCeG-iL_VS9bFqtmHSfwETo5f-8MQ7oMDE5IUYJi_Y/pubhtml?gid=0&single=true) for the Mattermost project.

**Please help complete the Mattermost [contribution license agreement](http://www.mattermost.org/mattermost-contributor-agreement/)?**
Once you have signed the CLA, please comment with `/check-cla` and confirm that the CLA check is green.

This is a standard procedure for many open source projects.

Please let us know if you have any questions.

We are very happy to have you join our growing community! If you're not yet a member, please consider joining our [Contributors community channel](https://pre-release.mattermost.com/core/channels/tickets) to meet other contributors and discuss new opportunities with the core team.

2023-05-05 12:52 UTC, enahum commented
/check-cla

2023-05-05 12:54 UTC, enahum requested changes

2023-05-05 12:54 UTC, enahum commented on app/components/settings/radio_setting/radio_entry.tsx
> +        },
```suggestion
        text: {
            fontSize: 12,
            color: theme.centerChannelColor,
        },
```

2023-05-05 14:11 UTC, nixusUM commented
/check-cla

2023-05-05 14:28 UTC, nixusUM commented on app/components/settings/radio_setting/radio_entry.tsx
> +        },
fixed

2023-05-05 15:58 UTC, nixusUM commented
> /check-cla

2023-05-10 08:21 UTC, nixusUM commented
/check-cla

2023-05-10 08:29 UTC, nixusUM commented
/check-cla

2023-05-10 10:31 UTC, enahum commented
Hi @nixusUM you have some linting issues, can you address them please?

2023-05-10 12:34 UTC, nixusUM commented
> Hi @nixusUM you have some linting issues, can you address them please?

hi, I fixed linting issues, but build failed again and I don't understand what need to do now

2023-05-17 05:52 UTC, nixusUM commented
@enahum Hi, any update?

2023-05-17 05:55 UTC, enahum approved these changes

2023-05-17 07:10 UTC, larkox approved these changes

2023-05-17 09:11 UTC, asaadmahmood approved these changes
LGTM, though the checkmark seems small, but I know that's not part of this PR.

2023-05-18 10:39 UTC, merged