Remove output redirection to resolve stuck behavior in pod-install
mattermost/mattermost-mobile pull request #7393
Opened 2023-06-04 11:13 UTC by M-ZubairAhmed

#### Summary
The purpose of the &> /dev/null redirection was to suppress output, including error messages and standard output. However, this redirection caused an issue where the command appeared to get stuck until pressing ["Enter" to proceed](https://community.mattermost.com/core/pl/8znnbqkwujgrxx61zxuis7t9tc). This behaviour might be due to buffering, where the output is not immediately displayed but is flushed upon pressing "Enter." It could be that there may not be any problem with the script itself; rather, it gave the perception of being stuck. Also, it seems that Cocoapods installation takes [a long time](https://stackoverflow.com/questions/23755974/cocoapods-pod-install-takes-forever). Given these factors, it is more reasonable to remove the output redirection and run the script with the complete output.

#### Ticket Link

#### Checklist

- [ ] Added or updated unit tests (required for all new features)
- [ ] Has UI changes
- [ ] Includes text changes and localization file updates
- [ ] Have tested against the 5 core themes to ensure consistency between them.

#### Device Information
This PR was tested on: 

#### Screenshots

#### Release Note

```release-note
NONE
```

2023-06-04 11:42 UTC, enahum requested changes
I'm not against this although the output is long and horrible

If this is the case, shouldn't this also be done for the Gem installation with bunlder?

2023-06-04 11:42 UTC, enahum commented on scripts/postinstall.sh
> +function getCocoaPodsFormacOS() {
`installPods` reads much better

2023-06-04 11:42 UTC, enahum commented on scripts/postinstall.sh
> +function getCocoaPodsFormacOSM1() {
`installPodsM1`

2023-06-04 11:56 UTC, M-ZubairAhmed commented
> If this is the case, shouldn't this also be done for the Gem installation with bunlder?

Didnt notice it was also used in `build.sh`, will change

2023-06-26 03:45 UTC, M-ZubairAhmed commented on scripts/postinstall.sh
> +function getCocoaPodsFormacOS() {
Done ✅

2023-06-26 03:45 UTC, M-ZubairAhmed commented on scripts/postinstall.sh
> +function getCocoaPodsFormacOSM1() {
Done ✅

2023-06-26 04:07 UTC, M-ZubairAhmed commented
/update-branch

2023-06-26 04:09 UTC, M-ZubairAhmed commented
/update-branch

2023-06-26 04:15 UTC, enahum approved these changes

2023-06-26 19:18 UTC, merged