use useAndroidHardwareBackHnd on Files and Members
mattermost/mattermost-mobile pull request #7455
Opened 2023-07-14 19:06 UTC by EduardoSellanes

#### Summary

there is an issue on Android, when we press the hardware back button in the Members and Files UI of a channel, the App goes to background instead of redirecting to the channel information.

Pinned messages UI works fine
please take a look to the screenshots, 

Files UI => app goes to background
![Files_UI](https://github.com/mattermost/mattermost-mobile/assets/5940718/b6cb8323-5593-4a7e-8158-e38f5d74e8cf)

Members UI => app goes to background
![Members_UI](https://github.com/mattermost/mattermost-mobile/assets/5940718/a1092bae-c01b-4ba9-8ffa-00be5dd91ee0)

Pinned UI => app goes to channel info (OK)
![Pinned_UI](https://github.com/mattermost/mattermost-mobile/assets/5940718/f161ddc5-e4ce-46e7-9e4d-0bd53b1c3198)

#### Ticket Link

#### Checklist

- [ ] Added or updated unit tests (required for all new features)
- [ ] Has UI changes
- [ ] Includes text changes and localization file updates
- [ ] Have tested against the 5 core themes to ensure consistency between them.

#### Device Information
This PR was tested on: 

#### Screenshots

#### Release Note

```release-note

```

2023-07-14 19:06 UTC, mattermost-build commented
Hello @EduardoSellanes,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2023-07-14 19:09 UTC, enahum requested changes

2023-07-14 19:09 UTC, enahum commented on app/screens/channel_files/channel_files.tsx
> +import useAndroidHardwareBackHandler from '@app/hooks/android_back_handler';
```suggestion
import useAndroidHardwareBackHandler from '@hooks/android_back_handler';
```

and sort

2023-07-14 19:09 UTC, enahum commented on app/screens/channel_files/channel_files.tsx
> +    const close = () => {
this should use a `useCallback`

2023-07-14 19:09 UTC, enahum commented on app/screens/manage_channel_members/manage_channel_members.tsx
> +import useAndroidHardwareBackHandler from '@app/hooks/android_back_handler';
```suggestion
import useAndroidHardwareBackHandler from '@hooks/android_back_handler';
```

and sort

2023-07-14 19:09 UTC, enahum commented on app/screens/manage_channel_members/manage_channel_members.tsx
> +    const close = () => {
`useCallback`

2023-07-14 19:29 UTC, enahum approved these changes

2023-07-17 07:28 UTC, larkox approved these changes

2023-07-17 07:43 UTC, mattermost-build commented
Building app in separate branch.

2023-07-17 12:50 UTC, yasserfaraazkhan approved these changes
thank you for the changes.

the back button take user to 'channel info' from files, pinned messages, members, edit channel screens.

2023-07-17 13:01 UTC, merged

2023-07-17 13:01 UTC, larkox commented
Thank you @EduardoSellanes for the contribution!