[MM-54599] Fix Servers bottom sheet
mattermost/mattermost-mobile pull request #7609
Opened 2023-10-17 13:25 UTC by Paul-vrn

#### Summary

Modified `BottomSheetFlatList` style in `app/screens/home/channel_list/servers/server_list/index.tsx` to add a bottom margin and prevent the "+Add server" bottom sheet from covering a server item.

Modified `onPress` function from `app/screens/home/channel_list/servers/index.tsx` to pre-calculate the "Your servers" Bottom sheet's height depending on the number of server items (and pushAlertText if present) up to a height of 60% of the screen. Above 60%, the sheet can be extended up to 80% of the screen.

#### Ticket Link

Fixes [https://github.com/mattermost/mattermost/issues/24668](https://github.com/mattermost/mattermost/issues/24668)
Jira [MM-54599](https://mattermost.atlassian.net/browse/MM-54599)

#### Checklist

- [ ] Added or updated unit tests (required for all new features)
- [x] Has UI changes
- [ ] Includes text changes and localization file updates
- [ ] Have tested against the 5 core themes to ensure consistency between them.

#### Device Information
This PR was tested on: Iphone 15, iOS 17.0 (using Simulator 15.0 on Mac)

#### Screenshots

<img width="250" alt="one_server" src="https://github.com/mattermost/mattermost-mobile/assets/78180340/d11b0ab1-3a5a-4e80-9982-7dbefaaa46aa">
<img width="250" alt="two_servers" src="https://github.com/mattermost/mattermost-mobile/assets/78180340/0a16c2a8-b1b3-421a-bde9-f1755b67fb4f">
<img width="250" alt="three_servers" src="https://github.com/mattermost/mattermost-mobile/assets/78180340/779f2eb7-b202-414e-8712-bb4e2a5bd99b">
<img width="250" alt="four_servers" src="https://github.com/mattermost/mattermost-mobile/assets/78180340/feb017f0-c28e-4e26-a64a-7922fce58b44">

https://github.com/mattermost/mattermost-mobile/assets/78180340/79c6c44f-a9a6-4a3e-8de6-000686e35e64

#### Release Note

```release-note
NONE
```

2023-10-17 13:41 UTC, enahum requested changes

2023-10-17 13:41 UTC, enahum commented on app/screens/home/channel_list/servers/servers_list/index.tsx
> +import {BUTTON_HEIGHT} from '@app/screens/bottom_sheet';
```suggestion
import {BUTTON_HEIGHT} from '@screens/bottom_sheet';
```

And sort the import

2023-10-17 13:41 UTC, enahum commented on app/screens/home/channel_list/servers/index.tsx
> +import {BUTTON_HEIGHT, TITLE_HEIGHT} from '@app/screens/bottom_sheet';
Remove
```suggestion
```

2023-10-17 13:41 UTC, enahum commented on app/screens/home/channel_list/servers/index.tsx
> -import {BUTTON_HEIGHT, TITLE_HEIGHT} from '@screens/bottom_sheet';
Keep

2023-10-17 13:41 UTC, enahum commented on app/screens/home/channel_list/servers/index.tsx
> +                    (registeredServers.current.filter((s: ServersModel) => s.lastActiveAt).length * 42),
Add the 42 to a constant name, same as the 75 to clearly identify what it means

2023-10-17 14:00 UTC, enahum approved these changes

2023-10-18 05:54 UTC, mattermost-build commented
Building app in separate branch.

2023-10-19 07:10 UTC, lindalumitchell approved these changes
Verified on the PR builds on Android and iOS that after adding enough servers to cause the list to scroll, I can open the bottom sheet to view the servers, pull it up to expand the list taller, and scroll through the server list without issue. Also double-checked that functions from that list such as editing server name, removing server, and logging out of a server work as expected with no issues. 👍

2023-10-30 01:03 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2023-10-30 03:53 UTC, merged