chore: migrate AWS SDK for JavaScript v2 APIs to v3
mattermost/mattermost-mobile pull request #7653
Opened 2023-11-08 08:42 UTC by trivikr

#### Summary

This PR migrates AWS SDK for JavaScript v2 APIs to v3 using [aws-sdk-js-codemod](https://www.npmjs.com/package/aws-sdk-js-codemod).

```console
$ npx aws-sdk-js-codemod@0.26.1 -t v2-to-v3 detox/utils/artifacts.js
```

Similar to https://github.com/mattermost/mattermost/pull/25301

#### Ticket Link

From AWS SDK for JavaScript v2 [README](https://github.com/aws/aws-sdk-js):
> We are formalizing our plans to make the Maintenance Announcement (Phase 2) for AWS SDK for JavaScript v2 in 2023.

#### Checklist
- [ ] Added or updated unit tests (required for all new features)
- [ ] Has UI changes
- [ ] Includes text changes and localization file updates
- [ ] Have tested against the 5 core themes to ensure consistency between them.

#### Device Information
N/A

#### Screenshots
N/A

#### Release Note
```release-note
NONE
```

2023-11-08 08:42 UTC, mattermost-build commented
Hello @trivikr,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2023-11-10 11:10 UTC, saturninoabril requested changes
Thanks @trivikr! Changes LGTM, just need to fix lint error.

2023-11-16 12:55 UTC, saturninoabril approved these changes
Thanks @trivikr, LGTM.

2023-11-17 00:05 UTC, enahum approved these changes

2023-12-01 01:02 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2024-02-16 18:34 UTC, trivikr commented
cc @saturninoabril @enahum Is this ready to merge?

I just rebased it from main branch.

2024-02-19 10:29 UTC, saturninoabril commented
Thanks @trivikr for your contribution!

2024-02-19 10:29 UTC, merged