Push react native to 0.73.6
mattermost/mattermost-mobile pull request #7863
Opened 2024-03-13 16:13 UTC by larkox

#### Summary
Push react native dependency and other dependencies that were needed for this push.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-57195

#### Release Note
```release-note
NONE
```

2024-03-14 04:11 UTC, enahum requested changes
1. We should document that jdk 17 is now needed in the dev docs
2. iOS is not compiling on Xcode 15.3 due to an issue with `@react-native-community/datetimepicker` see https://github.com/react-native-datetimepicker/datetimepicker/issues/866

2024-03-14 08:49 UTC, larkox commented on android/app/src/debug/java/com/mattermost/flipper/ReactNativeFlipper.java
I was following https://react-native-community.github.io/upgrade-helper/?from=0.72.7&to=0.73.6

That is why I removed this. I tried flipper and worked, but didn't look into the network or database.

2024-03-14 08:50 UTC, larkox commented on android/gradlew
Similar as my previous comment. I was following https://react-native-community.github.io/upgrade-helper/?from=0.72.7&to=0.73.6 and there were no changes to the gradlew.bat .

2024-03-14 08:52 UTC, larkox commented on patches/@mattermost+react-native-network-client+1.5.0.patch
Yes, sorry about that. This was an interim change to have the PR working and reviewable. Will update the network library.

2024-03-14 08:59 UTC, larkox commented on package.json
Based on https://hub.mattermost.com/private-core/pl/iup8yky9btguuyuhecw1zzo63y I understood it was relatively urgent to update the dependencies of React Native. That is why I updated those dependencies first, and postpone the rest.

If you think it is better to update all dependencies at once, let me know.

2024-03-14 09:25 UTC, larkox commented on patches/react-native-navigation+7.38.3.patch
I missed those patch files because I expected something to complain if we have a patch for something we are not using :facepalm: 

Will look into it.

2024-03-19 11:14 UTC, larkox commented on patches/react-native-video+5.2.1.patch
I don't follow what you mean here. In theory I just added a few patches on top of what existed. Every existing patch should still be in the file.

2024-03-19 11:25 UTC, larkox commented on patches/react-native-navigation+7.38.3.patch
Apparently this was applying correctly both patch files (to the point where patching it again only added to the patch files the "new differences"). Either way, I deleted the previous patch, run again the patch files, and have it in one single file.

2024-03-19 11:47 UTC, larkox commented on android/app/src/debug/java/com/mattermost/flipper/ReactNativeFlipper.java
Database seems to work just fine. The network plugin is the first time I try to use, and doesn't seem to be working correctly (I checked it is working on main). May be related to the changes to the network library, so 0/5. Will look into it.

2024-03-19 11:48 UTC, larkox commented on app/hooks/gallery.ts
> -function useRemoteContext<T extends object>(initialValue: T) {
Weird, I cannot reproduce. It seems to dismiss just fine for me.

2024-04-01 23:18 UTC, enahum commented
@larkox conflicts

2024-04-12 11:20 UTC, larkox commented on patches/react-native-navigation+7.39.1.patch
> -             mPermissionListener = null;
This change has been removed because it is already upstream.

2024-04-16 02:44 UTC, enahum approved these changes
Overall looks really good, great job

question: there are new library updates, should we update them with this PR or do you prefer to push to the next dep updates

2024-04-16 09:39 UTC, larkox commented
@enahum Let's update them in the next round of updates. This PR has already taken too long :stuck_out_tongue:

2024-04-16 09:40 UTC, larkox commented
@yasserfaraazkhan This updates many libraries, so a full smoke tests and maybe running the e2e tests we have would be awesome.

No functionality should have changed, but since it is a dependency update "anything" could break.

2024-04-21 20:50 UTC, yasserfaraazkhan approved these changes
[Zephyr link](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin:com.kanoah.test-manager__main-project-page#!/testPlayer/MM-R8447)

Executed mobile test cycle.

2024-04-22 10:44 UTC, merged