add mute all to participant list
mattermost/mattermost-mobile pull request #7945
Opened 2024-05-08 13:25 UTC by cpoile

#### Summary
- Add the mute all command in the participant list for hosts
- Designs: https://www.figma.com/file/8C0ojMc778Zx3a0nm66Edw/MM-56584-Host-Controls?node-id=1270%3A54648&mode=dev

<img src="https://github.com/mattermost/mattermost-mobile/assets/1490756/dcb1b149-12f9-49de-b29a-e8e9568721d0" width="200">

#### Ticket Link
- https://mattermost.atlassian.net/browse/MM-57470

#### Checklist
- [ ] Added or updated unit tests (required for all new features)
- [x] Has UI changes
- [x] Includes text changes and localization file updates
- [x] Have tested against the 5 core themes to ensure consistency between them.

#### Device Information
- Android: 13, Pixel 6
- Android: 13, Galaxy Tab s7+
- iOS: 16.5.1, iPhone 14

#### Release Note
```release-note
Calls: Host controls, mute all option added to participants list
```

2024-05-08 19:29 UTC, cpoile commented on app/products/calls/screens/participants_list/participants_list.tsx
> +        hostMuteAll(callServerUrl, callChannelId);
Ah, good catch, thank you. Fixed.

2024-05-08 20:04 UTC, matthewbirtch requested changes
This looks good to me @cpoile. The only thing I'm thinking is that `Mute all` should not mute the host who has clicked mute all. I think the main use case is to mute everyone except yourself. Thoughts?

Other than that, I think this is working well

2024-05-09 18:27 UTC, streamer45 approved these changes
Looks good, pending label changes.

2024-05-09 19:49 UTC, cpoile commented
@matthewbirtch Updated label, logic is same as https://github.com/mattermost/mattermost-plugin-calls/pull/726, screenshot in summary updated

2024-05-09 20:40 UTC, matthewbirtch approved these changes

2024-05-10 20:51 UTC, merged

2024-05-10 20:51 UTC, mattermost-build commented
Cherry pick is scheduled.