[MM-58314] [MM-43784] Markdown and file preview in thread list
mattermost/mattermost-mobile pull request #7963
Opened 2024-05-21 07:34 UTC by Boruus

#### Summary
Allowing markdown in thread list (for at mentions, links, and markdown tables) and add of file preview (for text, images, audio, video, pdf, etc).

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-58314
https://mattermost.atlassian.net/browse/MM-43784

#### Checklist

- [ ] Added or updated unit tests (required for all new features)
- [x] Has UI changes
- [x] Includes text changes and localization file updates
- [ ] Have tested against the 5 core themes to ensure consistency between them.

#### Device Information
This PR was tested on: iPhone 15 Pro, iOS 17.4 

#### Screenshots
|  before  |  after  |
|----|----|
| <img width="408" alt="image" src="https://github.com/mattermost/mattermost-mobile/assets/97885032/95e05bda-f301-4122-937e-67237b894c16"> | <img width="408" alt="Capture d’écran 2024-05-21 à 09 13 35" src="https://github.com/mattermost/mattermost-mobile/assets/97885032/53e87d16-3232-44c2-8096-2688763620f0"> |
| <img width="408" alt="image" src="https://github.com/mattermost/mattermost-mobile/assets/97885032/f37c2f45-8f12-4732-b099-19d6fa33c6df"> | <img width="408" alt="image" src="https://github.com/mattermost/mattermost-mobile/assets/97885032/0586c91b-5150-4459-9ea2-40ec4d8e9cd3"> |
 

#### Release Note

```release-note
Markdown and file preview in thread list
```

2024-05-22 06:37 UTC, Boruus commented
> Hello @Boruus,
> 
> Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).
> 
> Per the [Mattermost Contribution Guide](https://developers.mattermost.com/contribute/getting-started/), we need to add you to the list of [approved contributors](https://docs.google.com/spreadsheets/d/1NTCeG-iL_VS9bFqtmHSfwETo5f-8MQ7oMDE5IUYJi_Y/pubhtml?gid=0&single=true) for the Mattermost project.
> 
> **Please help complete the Mattermost [contribution license agreement](http://www.mattermost.org/mattermost-contributor-agreement/)?** Once you have signed the CLA, please comment with `/check-cla` and confirm that the CLA check is green.
> 
> This is a standard procedure for many open source projects.
> 
> Please let us know if you have any questions.
> 
> We are very happy to have you join our growing community! If you're not yet a member, please consider joining our [Contributors community channel](https://pre-release.mattermost.com/core/channels/tickets) to meet other contributors and discuss new opportunities with the core team.

/check-cla

2024-06-05 01:02 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2024-08-30 21:10 UTC, marianunez commented
@Boruus thank you for your contribution. Can you sign the CLA? Seems that is still missing.

2024-09-03 09:38 UTC, Boruus commented
> @Boruus thank you for your contribution. Can you sign the CLA? Seems that is still missing.

Hi, sorry for my long response, i've already signed it for webapp mattermost, do I need to sign it again for mobile ? 
![image](https://github.com/user-attachments/assets/15b61c20-887d-4553-9c73-ebf20998e296)

2024-09-03 10:03 UTC, enahum commented
/check-cla

2024-09-05 10:06 UTC, abhijit-singh commented
@larkox Could you approve the workflow action here - https://github.com/mattermost/mattermost-mobile/actions/runs/10708019777?

2024-10-05 01:02 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2024-10-28 11:18 UTC, larkox commented
I created this other branch to get the builds: https://github.com/mattermost/mattermost-mobile/pull/8293

Heads up @Boruus that I merged main into your branch.

2024-10-28 12:04 UTC, larkox commented
@Boruus It seems your changes are breaking one test. Could you take a look at it? I think some changes have to be made to keep the previous behavior (but not 100% sure the previous behavior is the desired one).

2025-01-03 11:02 UTC, Boruus commented
@larkox 
Hi, excuse me for my late reply, I pushed what seems to me correct the test that fails.

and to explain quickly my point : 
- the aim is to display the file preview (or text) when a thread starts with a file (or text): 
   
- it works correctly except for the svg thumbnail which doesn't return a `thumbnailUri`(called with the `buildFileThumbnailUrl` function directly on the server) 

- so when the `thumbnailUri` doesn't exist, I display instead the basic icon of the file obtained with the `FileIcon` component

- that's why I've created a new type especially for svg files, so I can detect them and display another preview

- this is also the case for other file types such as PDFs or videos

Don't hesitate if you have any further questions !

2025-01-07 16:03 UTC, larkox commented
@Boruus Another small thing. We simplified how things get imported, and that introduced some minor failures in your PR. The change you need to do is pretty simple. Just remove the `app/` part of the imports that have it. For example...

```
import FileIcon from '@app/components/files/file_icon';
```
should change into
```
import FileIcon from '@components/files/file_icon';
```

2025-01-08 16:27 UTC, Boruus commented
@larkox 
Yes I forgot that, It should be better now, let me know if there's anything else to adjust.

2025-01-10 12:14 UTC, larkox commented
@Boruus It seems there are still a couple of files that have the `app/` prefix in the imports. In particular...
- app/screens/global_threads/threads_list/file_card/styles.ts
- app/screens/global_threads/threads_list/thread/thread.tsx

2025-01-12 12:29 UTC, Boruus commented
@larkox 

Sorry, must be fine now, is there a way to see those errors locally or is it only on CI ?

2025-01-15 11:39 UTC, larkox commented
@Boruus The errors should show when you run `npm run lint` (or `npm run fix`) for linter errors, and `npm run tsc` for typescript errors. You can also run `npm run check` and should check both.

2025-01-15 12:16 UTC, larkox requested changes
Great work! A few questions about the implementation, and some minor things.

2025-01-15 12:16 UTC, larkox commented on app/screens/global_threads/threads_list/file_card/file_card.tsx
> +    }, [post]);
This works, but it won't react to changes in the files until the post changes. In practice, I think that will never happen, but just in case we should do this "the correct way".

For that you should add a watermelon db HOC, like the one in `app/components/common_post_options/copy_permalink_option/index.tsx`, and return there something like `post.files.observe()`. If you need more indications for this, let me know.

2025-01-22 16:02 UTC, Boruus commented on app/screens/global_threads/threads_list/file_card/file_card.tsx
@larkox I thought it was cleaner to create a new component rather than integrate it into File (there would have been too much logic in it), do you think I should move all the logic into the File component?

2025-01-23 11:31 UTC, larkox commented on app/screens/global_threads/threads_list/file_card/file_card.tsx
Moving all the logic inside the already existing component seems off, you are right. Would it be possible to wrap the existing component to add this new logic? Or would that require too deep changes in the existing component?

2025-01-23 15:32 UTC, Boruus commented on app/screens/global_threads/threads_list/file_card/file_card.tsx
@larkox I think it could be possible, i'll give it a try

2025-09-10 11:59 UTC, Boruus commented
Hi, sorry for the wait.

@larkox I pushed a new version. As mentioned here https://github.com/mattermost/mattermost-mobile/pull/7963#discussion_r1916446829, I just reused the `Files` component, and there is already `isCard` property that gave me the preview, which made the PR much simpler.
I only had to make some of the component's properties optional to achieve this. I also removed the `onClick` from the previews, assuming that we wouldn't need it here.

Would that be better now ?

2025-10-27 12:37 UTC, larkox approved these changes
Codewise, no real concerns. Waiting on whether UX is happy with the feature.

2025-10-27 12:37 UTC, larkox commented on app/screens/global_threads/threads_list/thread/index.ts
> +    const validateFiles = (fs: FileModel[], userId: string) => from$(filesLocalPathValidation(fs, userId));
We can have this created outside of `withObservables`.

2025-10-27 12:37 UTC, larkox commented on app/screens/global_threads/threads_list/thread/thread.tsx
> +            postBody = (
If I am understanding right, this will show only the first file, right?

2025-10-28 10:50 UTC, Boruus commented on app/screens/global_threads/threads_list/thread/thread.tsx
> +            postBody = (
Yes, only the first file is shown when the first post contains multiple files.

2025-10-28 10:57 UTC, Boruus commented on app/screens/global_threads/threads_list/thread/thread.tsx
> +
@larkox I found a case where the file isn’t loaded.
When you start the app and switch to the thread view, if you’ve received a thread with a file while you were disconnected, the file doesn’t load.
It looks like we only update the local DB for files when switching to a thread or when a new thread is received via WebSocket.
I added this useEffect, which seems to fix the issue. What do you think?
I tried to target the problem as precisely as possible to avoid unnecessary calls.

2025-10-29 11:04 UTC, larkox commented on app/screens/global_threads/threads_list/thread/thread.tsx
> +
@enahum Do you know if this particular case will be fixed by https://github.com/mattermost/mattermost-mobile/pull/9243 ? I know you added some code to add some potentially missing data when receiving notifications.

2025-10-29 13:47 UTC, enahum commented on app/screens/global_threads/threads_list/thread/thread.tsx
> +
The code mostly will skip the problem and not crash but does not ensure consistency of the data

2025-10-30 12:40 UTC, Boruus commented on app/screens/global_threads/threads_list/thread/thread.tsx
> +
So, should I keep this logic?
I don’t really see another way to ensure file info consistency other than fetching the root post of the thread when opening the Global Thread view.
This guarantees that the file attached to the root post is loaded in the local DB at initialization, and afterwards it will stay consistent through WebSocket updates.
Maybe you have another idea ?

2025-10-31 10:07 UTC, larkox commented on app/screens/global_threads/threads_list/thread/thread.tsx
> +
Looking at the code, the problem is that you will have a burst of requests when watching the list, right? All the rendered threads that have no files, will try to fetch the thread.

Also, you are fetching the whole thread, instead of just the root post, which is where the file infos you need are.

Since we don't have a good way to solve this scenario, I would revert this part, and rethink this later.

2025-11-11 01:06 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2025-11-11 16:13 UTC, Boruus commented on app/screens/global_threads/threads_list/thread/thread.tsx
> +
Yes, you're right. I was thinking about maybe doing the same approach as on the web app:
https://github.com/mattermost/mattermost/blob/a9c9953439af08004b20b5507068dc36683e1965/webapp/channels/src/packages/mattermost-redux/src/actions/threads.ts#L79

https://github.com/mattermost/mattermost/blob/a9c9953439af08004b20b5507068dc36683e1965/webapp/channels/src/packages/mattermost-redux/src/actions/files.ts#L21

When entering thread view, we only fetch the file info for a thread’s post if it has a `file_ids`. I can look into implementing this solution.

(Otherwise, I can revert, but in that case, will this PR be accepted or not? (while waiting for the proper solution))

2026-06-22 19:28 UTC, enahum commented
do we still want this? if we do, some conflicts needs to be resolved, if we don't feel free to close the PR

2026-06-22 19:30 UTC, closed without merging