Fix insecure BiometricPrompt usage in Credentials class
mattermost/mattermost-mobile pull request #7964
Opened 2024-05-21 13:29 UTC by bruhdev1290

Summary
This pull request addresses the insecure usage of the BiometricPrompt API in the Mattermost Android application, identified in HackerOne report #2503621. While biometric authentication is not fully implemented in the current application, this fix prevents vulnerable code from being sent to production if biometrics are fully developed as a feature in the future. The changes ensure the secure implementation of biometric authentication by providing a valid CryptoObject parameter and improving error handling. This maintains the existing functionality of the app while enhancing security to prevent potential bypasses. For more details on the sensitivity and impact of these changes, refer to the HackerOne ticket or the manual disclosure email.

Changes
✅ implemented secure usage of the BiometricPrompt API by providing a valid CryptoObject parameter.
✅Improved error handling to prevent bypassing biometric authentication.
✅Added caching mechanism to improve performance and security.

Affected Files
com/mattermost/helpers/Credentials.java

patches/react-native-keychain+8.2.0.patch

Timeline
2024-05-14 01:08:11 UTC: Initial report (#2503621) submitted by the reporter on HackerOne outlining the insecure use of BiometricPrompt API in the Mattermost Android application.
2024-05-14 02:39:00 UTC: The reporter provides additional references and materials for understanding and reproducing the issue.
2024-05-16 08:06:49 UTC: HackerOne triage team acknowledges receipt of the report and begins review.
2024-05-16 08:42:09 UTC: @h1_analyst_jan responds, initially closing the report as informative, stating that the issue does not present a significant security risk under their current policy.
2024-05-16 12:12:11 UTC: The reporter responds, addressing the concerns raised by the triage team, emphasizing the potential risk even without physical access or rooted devices.
2024-05-16 12:14:22 UTC: The reporter clarifies the intent to prevent the vulnerable code from being fully implemented in production.
2024-05-17 21:39:09 UTC: The reporter attempts to dispute the decision with the information given above, but receives no response from the triage team nor the manual responsible disclosure email.

For additional details, refer to the original HackerOne ticket (#2503621) or the manual disclosure email.

✅ The code follows the code style of this project.
 Documentation has been updated to reflect the changes.
✅ All new and existing tests passed.
N/A Added or updated unit tests (required for all new features)
 N/A Has UI changes
 N/A Includes text changes and localization file updates
N/A Have tested against the 5 core themes to ensure consistency between them.
Device Information

This PR was tested on:
Samsung Tab A7 Lite, Android 14, and Google Pixel 7a

```release-note
Improves Handling of Authentication of the Android Client
```

2024-05-21 13:29 UTC, mattermost-build commented
Hello @bruhdev1290,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

Per the [Mattermost Contribution Guide](https://developers.mattermost.com/contribute/getting-started/), we need to add you to the list of [approved contributors](https://docs.google.com/spreadsheets/d/1NTCeG-iL_VS9bFqtmHSfwETo5f-8MQ7oMDE5IUYJi_Y/pubhtml?gid=0&single=true) for the Mattermost project.

**Please help complete the Mattermost [contribution license agreement](http://www.mattermost.org/mattermost-contributor-agreement/)?**
Once you have signed the CLA, please comment with `/check-cla` and confirm that the CLA check is green.

This is a standard procedure for many open source projects.

Please let us know if you have any questions.

We are very happy to have you join our growing community! If you're not yet a member, please consider joining our [Contributors community channel](https://pre-release.mattermost.com/core/channels/tickets) to meet other contributors and discuss new opportunities with the core team.

2024-05-21 13:34 UTC, bruhdev1290 commented
/check-cla

2024-05-21 13:37 UTC, enahum requested changes

2024-05-21 13:37 UTC, enahum commented on android/app/src/main/java/com/mattermost/helpers/Credentials.java
> +        authenticateUserWithBiometrics(context, new BiometricPrompt.AuthenticationCallback() {
This does not seem optional, also irrc some functions from push notifications do make use of this function as well as createThumbnail for videos and I'm not sure this does not disrupt the current flow.

2024-05-21 13:37 UTC, enahum commented on patches/react-native-keychain+8.2.0.patch
>     function setInternetCredentials(
There seems to be no changes in this file

2024-05-22 11:38 UTC, larkox requested changes
The idea looks good, but a few comments.

2024-05-22 11:38 UTC, larkox commented on android/app/src/main/java/com/mattermost/helpers/Credentials.java
> -        // KeyChain module fails if `authenticationPrompt` is not set
Any strong reason to remove this comment?

2024-05-22 11:38 UTC, larkox commented on android/app/src/main/java/com/mattermost/helpers/Credentials.java
> +                    keychainModule.getGenericPasswordForOptions(options, promise);
This block is the same as the block in lines 45-52. Any chance we can refactor it out?

2024-05-22 11:38 UTC, larkox commented on patches/react-native-keychain+8.2.0.patch.o9ATfpc
Are these patches files intended or a bad commit?

2024-05-23 09:12 UTC, larkox commented on patches/react-native-keychain+8.2.0.patch.o9ATfpc
There are still some patch files that I don't understand in the changelog. Are these intended?

2024-05-23 13:22 UTC, bruhdev1290 commented
> Also, what is with all the patch files...

I needed the excess patch file due to it not compiling on my end however it was due to system configuration on my end that caused the problem I removed the excess patch files in the latest commit

2024-06-05 01:02 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2024-09-16 03:07 UTC, enahum commented
I'm going to close this PR as is not really fixing anything nor adding functionality

2024-09-16 03:07 UTC, closed without merging