Use UUID native functions
mattermost/mattermost-mobile pull request #8032
Opened 2024-06-19 14:43 UTC by larkox

#### Summary
Use the UUID native functions to generate UUIDs.

#### Ticket Link
Fix https://mattermost.atlassian.net/browse/MM-58743

#### Release Note
```release-note
Improve how we generate UUIDs
```

2024-06-19 15:11 UTC, esarafianou approved these changes

2024-06-19 15:40 UTC, enahum requested changes
Podfile.lock needs to be updated

2024-06-19 15:40 UTC, enahum commented on package.json
> +    "expo-crypto": "13.0.2"
not that it matters much.. but it would be good to sort this

2024-06-20 07:14 UTC, larkox commented
@enahum Podfile.lock is updated. Am I missing anything there?

2024-06-20 10:22 UTC, enahum approved these changes
My bad, missed it

2024-06-20 10:22 UTC, merged