MM-60705 DB migration: added update_at column to draft table for mobile
mattermost/mattermost-mobile pull request #8237
Opened 2024-09-30 08:08 UTC by Rajat-Dabade

#### Summary
Added `update_at` column to the draft table for mobile. 

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-60705

#### Checklist

- [ ] Added or updated unit tests (required for all new features)
- [ ] Has UI changes
- [ ] Includes text changes and localization file updates
- [ ] Have tested against the 5 core themes to ensure consistency between them.
- [ ] Have run E2E tests by adding label `E2E iOS tests for PR`.

#### Device Information
This PR was tested on: 
Andriod: 15 and iOS: 17.5

#### Release Note

```release-note
Added a new column `update_at` to the Drafts Table.
```

2024-09-30 10:59 UTC, larkox approved these changes

2024-09-30 11:00 UTC, larkox commented
@Rajat-Dabade I think you are still missing the docs updates for this PR

2024-09-30 11:04 UTC, Rajat-Dabade commented
@larkox will be updating it today.

2024-10-02 00:36 UTC, yasserfaraazkhan approved these changes

2024-10-10 07:52 UTC, enahum requested changes

2024-10-10 07:52 UTC, enahum commented on app/components/post_draft/index.ts
> +        switchMap((cId) => queryDraft(database, cId, rootId).observeWithColumns(['update_at']).pipe(
Not part of this PR, correct?

2024-10-10 07:52 UTC, enahum commented on app/database/operator/server_data_operator/transformers/post.ts
> +        draft.updateAt = raw.update_at;
```suggestion
        draft.updateAt = raw?.update_at || Date.now();
```

2024-10-10 10:31 UTC, Rajat-Dabade commented on app/components/post_draft/index.ts
> +        switchMap((cId) => queryDraft(database, cId, rootId).observeWithColumns(['update_at']).pipe(
Yes, reverting back the changes.

2024-10-10 10:32 UTC, Rajat-Dabade commented on app/database/operator/server_data_operator/transformers/post.ts
> +        draft.updateAt = raw.update_at;
Done.

2024-10-10 10:53 UTC, enahum requested changes

2024-10-10 10:53 UTC, enahum commented on app/database/operator/server_data_operator/transformers/post.ts
> +        draft.updateAt = raw.update_at || Date.now();
```suggestion
        draft.updateAt = raw.update_at ?? Date.now();
```

I guess 0 is a valid value

2024-10-10 10:56 UTC, Rajat-Dabade commented on app/database/operator/server_data_operator/transformers/post.ts
> +        draft.updateAt = raw.update_at || Date.now();
Make sense.

2024-10-10 11:16 UTC, enahum approved these changes

2024-10-15 14:19 UTC, merged