Unit test for mobile draft
mattermost/mattermost-mobile pull request #8363
Opened 2024-11-20 11:59 UTC by Rajat-Dabade

#### Summary
Added unit test for mobile in draft PR: https://github.com/mattermost/mattermost-mobile/pull/8280

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-61735

#### Checklist

- [x] Added or updated unit tests (required for all new features)
- [ ] Has UI changes
- [ ] Includes text changes and localization file updates
- [ ] Have tested against the 5 core themes to ensure consistency between them.
- [ ] Have run E2E tests by adding label `E2E iOS tests for PR`.

#### Release Note
```release-note
NONE
```

2024-12-19 04:32 UTC, enahum requested changes
looks like this PR needs conflict resolution and to cover all the changes in the base PR

2025-01-15 10:20 UTC, larkox approved these changes
Great work!
Nothing blocking, but a couple of things that can be improved.

2025-01-15 10:20 UTC, larkox commented on app/components/draft_post_header/channel_info.test.tsx
> +        };
You could have the base props predefined (be it in a function or an object) and just set the "relevant props for the test". For example...

```
function getBaseProps() {
    return {
            channel: {type: General.DM_CHANNEL, displayName: 'Direct Message Channel'} as ChannelModel,
            draftReceiverUser: undefined,
            updateAt: 1633024800000,
            rootId: undefined,
            testID: 'channel-info',
            currentUser: {timezone: 'UTC'} as unknown as UserModel,
            isMilitaryTime: true,
        };
}

...
   it(..., () => {
        const props = getBaseProps();
        props.channel = {type: General.DM_CHANNEL, displayName: 'Direct Message Channel'} as ChannelModel,
        const wrapper = render(<DraftPostHeader {...props}/>);
        ....
```
Or if you prefer the object route...
```
const baseProps = {
    ...
};

...
    it(..., () => {
        const props = {
            ...baseProps,
            channel: {type: General.DM_CHANNEL, displayName: 'Direct Message Channel'} as ChannelModel,
        }
        const wrapper = render(<DraftPostHeader {...props}/>);
        ...
```

2025-01-15 10:20 UTC, larkox commented on app/components/draft_post_header/profile_avatar.test.tsx
> +const mockUseServerUrl = require('@context/server').useServerUrl;
Why using require instead of normal imports?

2025-01-15 10:20 UTC, larkox commented on app/screens/draft_options/draft_options.test.tsx
> +    it('should render the draft options component', () => {
It is hard to see the difference between the two tests.

2025-01-15 10:20 UTC, larkox commented on app/screens/draft_options/send_draft.test.tsx
> +    it('should call dismissBottmSheet after sending the draft', () => {
Same comment about this only checking for dismissBottomSheet.

2025-01-15 10:20 UTC, larkox commented on app/screens/draft_options/send_draft.test.tsx
> +    it('should call dismissBottmSheet after sending the draft', () => {
```suggestion
    it('should call dismissBottomSheet after sending the draft', () => {
```

2025-01-27 16:22 UTC, rahimrahman reviewed
I'm 4/5 that snapshots don't really bring any values unless use with something like toMatchSnapshotDiff().  So I recommend removing all snapshot in favor of better meaningful tests like observed changes when using one prop vs another (via re-render).

Also, since most of the tests are component tests, it usually is very easy to get 100% coverage.  Can you display the coverage output for the components?

2025-01-27 16:22 UTC, rahimrahman commented on app/components/draft/draft.test.tsx
> +        const {getByText} = wrapper;
nit: can destructure directly or perhaps use wrapper.getByText?
```suggestion
        const {getByText} = renderWithEverything(
            <Draft
                channel={props.channel}
                location={props.location}
                draft={props.draft}
                layoutWidth={props.layoutWidth}
                isPostPriorityEnabled={props.isPostPriorityEnabled}
            />
            , {database},
        );
```

2025-01-27 16:22 UTC, rahimrahman commented on app/components/draft/draft.test.tsx
> +        expect(wrapper.toJSON()).toMatchSnapshot();
Is having snapshot adding any more value?

2025-01-27 16:22 UTC, rahimrahman commented on app/components/draft/draft.test.tsx
> +        expect(wrapper.toJSON()).toMatchSnapshot();
Same as above:
```suggestion
        const {getAllByTestId, toJSON} = renderWithEverything(
            <Draft
                channel={props.channel}
                location={props.location}
                draft={props.draft}
                layoutWidth={props.layoutWidth}
                isPostPriorityEnabled={props.isPostPriorityEnabled}
            />
            , {database},
        );
        expect(getAllByTestId('file_attachment')).toHaveLength(2);
        expect(toJSON()).toMatchSnapshot();
```

2025-01-27 16:22 UTC, rahimrahman commented on app/components/draft/draft.test.tsx
> +        expect(wrapper.toJSON()).toMatchSnapshot();
Same question throughout, how would the snapshot help understand that there are two files?

2025-01-27 16:22 UTC, rahimrahman commented on app/components/draft/draft_post/draft_post.test.tsx
> +describe('Draft Post', () => {
Agreed, there should be more specific test here.  Like the existence of DraftFiles when there are files, etc.

2025-05-29 08:31 UTC, Rajat-Dabade commented
Closing the PR, as the test are been covered in this PR: https://github.com/mattermost/mattermost-mobile/pull/8887

2025-05-29 08:31 UTC, closed without merging